"""Precompute the HONEST training-coverage region for the ch1.1 covariate-shift toy.

The toy (site/src/components/PlateIsland.tsx) draws "the region of block poses the
demonstrations actually covered" as an overlay, and reads a live "distance from
training data" meter off it. Both MUST reflect the real training distribution, not
an invented shape (root CLAUDE.md: numbers have provenance).

WHAT THE TRAINING DATA IS
-------------------------
bc.py trains on (obs, action) pairs generated by gen_demos.py, which rolls the
scripted expert over episodes seeded `--seed + i`, each episode reset via
PushTEnv.reset(seed). So the exact set of block poses the policy ever saw is:
the union of block (tee_x, tee_y) positions VISITED along every scripted-expert
trajectory, starting from PushTEnv.reset's block distribution (a uniform annulus
r in [0.10, 0.24] around the target at the origin, uniform yaw) and pushed toward
the target. We reproduce that here with the SAME env + expert and record every
visited block xy.

WHY A RADIAL ENVELOPE
---------------------
The target is fixed at the origin; every demo starts on the annulus and the
expert drives the block inward toward it, so the visited cloud is star-shaped
about the origin (dense at the center, bounded outward by the start annulus plus
a little push overshoot). We therefore summarize coverage as a radial envelope:
for each of K angular bins, the outer radius the demos reached. This is:
  * honest  — it is the empirical outer edge of the real visited cloud;
  * legible — it draws as one filled region and yields a trivial distance meter;
  * faithful as a distance metric — for a block dragged OUTWARD (the covariate
    shift the toy induces), the nearest demonstrated block position lies along
    the same ray at the envelope, so `max(0, r - r_env(theta))` equals the
    nearest-neighbor distance to the training cloud (verified below vs a brute
    nearest-neighbor on a grid of query points).

Yaw is NOT the shift axis: reset samples yaw uniformly on [-pi, pi), so every
orientation is in-distribution. The toy exposes POSITION as the one variable,
and this envelope is over block position. (Recorded in the JSON provenance.)

Usage:
    ../.venv/bin/python scripts/gen_coverage.py            # writes src/data/pusht_coverage.json
    ../.venv/bin/python scripts/gen_coverage.py --episodes 200
"""
from __future__ import annotations

import argparse
import json
import subprocess
import sys
from datetime import date
from pathlib import Path

import numpy as np

_PUSHT = Path(__file__).resolve().parents[2] / "curriculum" / "common" / "envs" / "pusht"
sys.path.insert(0, str(_PUSHT))

import mujoco  # noqa: E402
from pusht_env import PushTEnv  # noqa: E402
from scripted_expert import ScriptedExpert  # noqa: E402

K_BINS = 64  # angular resolution of the radial envelope (5.625 deg/bin)


def rollout_visited(episodes: int, seed0: int) -> tuple[np.ndarray, np.ndarray, int]:
    """Return (visited_xy [N,2], start_xy [episodes,2], successes) over demo episodes.

    Byte-for-byte the trajectory distribution gen_demos.py writes: same reset,
    same ScriptedExpert, same seed-per-episode. `--noise 0` (gen_demos default),
    so these are the deterministic expert paths the dataset is built from.
    """
    env = PushTEnv()
    visited: list[np.ndarray] = []
    starts: list[np.ndarray] = []
    successes = 0
    for i in range(episodes):
        seed = seed0 + i
        env.reset(seed)
        starts.append(env.tee_pose[:2].copy())
        expert = ScriptedExpert(noise=0.0, seed=seed)
        done = False
        info: dict = {}
        while not done:
            visited.append(env.tee_pose[:2].copy())  # block xy BEFORE this action
            action = expert.action(env)
            _, _, done, info = env.step(action)
        visited.append(env.tee_pose[:2].copy())  # final resting pose
        successes += bool(info.get("success"))
    return np.array(visited), np.array(starts), successes


def radial_envelope(visited: np.ndarray, k_bins: int, pct: float) -> np.ndarray:
    """Per-angular-bin outer radius (pct-th percentile) of the visited cloud.

    A high percentile (not the raw max) so a single physics overshoot cannot
    inflate the boundary; documented in provenance.
    """
    r = np.hypot(visited[:, 0], visited[:, 1])
    theta = np.arctan2(visited[:, 1], visited[:, 0])  # [-pi, pi)
    bin_idx = np.floor((theta + np.pi) / (2 * np.pi) * k_bins).astype(int)
    bin_idx = np.clip(bin_idx, 0, k_bins - 1)
    env_r = np.zeros(k_bins)
    for b in range(k_bins):
        rb = r[bin_idx == b]
        env_r[b] = float(np.percentile(rb, pct)) if len(rb) else 0.0
    # Light circular smoothing (3-tap) so the drawn boundary is not jagged from
    # bin-count noise; preserves the empirical scale.
    sm = np.convolve(np.r_[env_r[-1], env_r, env_r[0]], [0.25, 0.5, 0.25], mode="valid")
    return sm


def dist_beyond_envelope(x: float, y: float, env_r: np.ndarray) -> float:
    """The toy's live metric, in Python, for validation: 0 inside, else r - r_env."""
    k = len(env_r)
    r = float(np.hypot(x, y))
    theta = float(np.arctan2(y, x))
    b = int(np.clip(np.floor((theta + np.pi) / (2 * np.pi) * k), 0, k - 1))
    return max(0.0, r - env_r[b])


def validate_metric(visited: np.ndarray, env_r: np.ndarray, n: int = 4000) -> dict:
    """Confirm the radial metric ~ brute nearest-neighbor distance to the cloud,
    on random OUTWARD query points (the covariate-shift regime the toy induces)."""
    rng = np.random.Generator(np.random.PCG64(12345))
    # sample query points across the reachable workspace (|x|,|y| < 0.40)
    q = rng.uniform(-0.40, 0.40, size=(n, 2))
    sub = visited[rng.integers(0, len(visited), size=min(len(visited), 20000))]
    errs = []
    for x, y in q:
        radial = dist_beyond_envelope(x, y, env_r)
        if radial <= 0:
            continue  # in-distribution; nearest-neighbor is ~0, not informative
        nn = float(np.min(np.hypot(sub[:, 0] - x, sub[:, 1] - y)))
        errs.append(abs(radial - nn))
    errs = np.array(errs)
    return {
        "outward_query_points": int(len(errs)),
        "mean_abs_diff_m": float(errs.mean()),
        "p95_abs_diff_m": float(np.percentile(errs, 95)),
        "max_abs_diff_m": float(errs.max()),
    }


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--episodes", type=int, default=200)
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--k-bins", type=int, default=K_BINS)
    ap.add_argument("--pct", type=float, default=99.0,
                    help="per-bin outer-radius percentile (robust to overshoot flukes)")
    ap.add_argument("--out", type=Path,
                    default=Path(__file__).resolve().parent.parent / "src" / "data" / "pusht_coverage.json")
    args = ap.parse_args(argv)

    visited, starts, successes = rollout_visited(args.episodes, args.seed)
    env_r = radial_envelope(visited, args.k_bins, args.pct)
    start_r = np.hypot(starts[:, 0], starts[:, 1])
    check = validate_metric(visited, env_r)

    try:
        git_sha = subprocess.check_output(
            ["git", "rev-parse", "--short", "HEAD"], cwd=str(_PUSHT), text=True
        ).strip()
    except Exception:
        git_sha = "unknown"

    out = {
        "schema": "z2r-coverage-1",
        "task": "pusht",
        "chapter": "ch1.1-bc",
        "variable": "block_position_xy",
        "world_half_extent_m": 0.45,
        "target_xy": [0.0, 0.0],
        "k_bins": args.k_bins,
        # radial envelope: outer radius (m) per angular bin, bin b covers
        # theta in [-pi + 2pi*b/K, -pi + 2pi*(b+1)/K); theta = atan2(y, x).
        "envelope_radius_m": [round(float(v), 5) for v in env_r],
        # distance-from-training metric the toy renders:
        #   r = hypot(x, y); b = bin(atan2(y,x)); dist = max(0, r - envelope[b])
        "metric": "radial_beyond_envelope",
        "provenance": {
            "derived_from": "real scripted-expert demonstration rollouts — the exact "
                            "distribution gen_demos.py writes the BC training set from",
            "env": "curriculum/common/envs/pusht/pusht_env.py (PushTEnv.reset annulus "
                   "r in [0.10,0.24], uniform yaw) + scripted_expert.py (noise=0)",
            "generator": "site/scripts/gen_coverage.py",
            "generator_command": f"../.venv/bin/python scripts/gen_coverage.py "
                                 f"--episodes {args.episodes} --seed {args.seed} "
                                 f"--k-bins {args.k_bins} --pct {args.pct}",
            "episodes": args.episodes,
            "seed0": args.seed,
            "visited_block_positions": int(len(visited)),
            "envelope_percentile": args.pct,
            "expert_success_rate": round(successes / args.episodes, 3),
            "start_radius_m": {
                "min": round(float(start_r.min()), 4),
                "mean": round(float(start_r.mean()), 4),
                "max": round(float(start_r.max()), 4),
                "annulus_spec": [0.10, 0.24],
            },
            "envelope_radius_m_summary": {
                "min": round(float(env_r.min()), 4),
                "mean": round(float(env_r.mean()), 4),
                "max": round(float(env_r.max()), 4),
            },
            "yaw_note": "reset samples yaw uniformly on [-pi, pi), so orientation is "
                        "fully in-distribution; the shift axis this toy exposes is "
                        "block POSITION, hence a position-only coverage region.",
            "metric_validation_vs_nearest_neighbor": check,
            "versions": {"mujoco": mujoco.__version__, "numpy": np.__version__},
            "generated": str(date.today()),
            "pusht_git": git_sha,
        },
    }

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(out, indent=2) + "\n")
    print(f"wrote {args.out}")
    print(f"  episodes={args.episodes} visited={len(visited)} "
          f"expert_success={successes}/{args.episodes}")
    print(f"  envelope r: min={env_r.min():.3f} mean={env_r.mean():.3f} max={env_r.max():.3f} m")
    print(f"  metric vs NN: mean|dr|={check['mean_abs_diff_m']*100:.2f} cm  "
          f"p95={check['p95_abs_diff_m']*100:.2f} cm (over {check['outward_query_points']} OOD queries)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
