/**
 * ch3.5 "Build a Physics Engine III: Contact" — the PENALTY-vs-LCP honesty toy
 * (`demo: contact_quality`). A sibling of ch2.3's MJX toy and ch1.5's flow ring:
 * it renders REAL, pre-computed trajectories — never invented shapes — as pure SVG
 * + design tokens, so it is theme-aware for free and the server-rendered default
 * IS the JS-off experience.
 *
 * HONESTY — THIS IS RECORDED DATA, replayed, not a live sim. contact.py's engine
 * is ~400 lines of pure numpy (no WASM/MuJoCo in the dynamics), so instead of
 * running it in the browser we REPLAY the trajectories it measured at seed 0 on
 * CPU — regenerated by site/scripts/vizdata/ch3.5_contact.py into the co-located
 * vizdata.json, verified against meta.yaml (penalty max-pen 0.2513 / rest 0.00981,
 * lcp 0.0567 / 0.0, dt_crit 0.02, penalty explodes +2625x at dt_crit). Every panel
 * says so. Frictionless normal contact only; the lcp solve is fixed-iteration
 * projected Gauss-Seidel, not a true LCP pivot — stated plainly in the limits note.
 *
 * THREE linked panels (embed.yaml's contact_quality):
 *   1. THE DROP — a ball falling onto the table under PENALTY vs LCP, side by side.
 *      Penalty drives ~1/4 of its radius INTO the table, rings, and rests SUNK by
 *      mg/k; LCP catches it in ~one step and holds it exactly on the surface. A
 *      scrubber/▶ replays the recorded fall (auto-plays unless reduced-motion).
 *   2. PENETRATION over time — the honesty metric, both methods, from that drop:
 *      penalty plunges below the surface and rings; lcp barely dips, then holds ~0.
 *   3. THE dt CLIFF (the interactive headline) — a slider over the timestep. Penalty
 *      is stable while dt < ~2*sqrt(m/k); dragged past dt_crit its energy DETONATES
 *      (0 -> 267x -> 2625x) while LCP stays bounded. Boots at a calm dt so the first
 *      drag over the edge is the aha.
 *
 * Colour discipline (contact.py COLORS / embed.yaml): --alert red = PENALTY (it
 * sinks, rings, explodes); --entity-target green = LCP (it holds); --signal blue =
 * the one live handle (the sliders / focus); neutral ink = the table, axes, grid.
 */
import "./contact-toy.css";
import { useEffect, useRef, useState } from "preact/hooks";
// Real recorded trajectories from contact.py, seed 0, cpu — see the file's
// `provenance` and the generator site/scripts/vizdata/ch3.5_contact.py. Small text, no binary.
import viz from "../../../../curriculum/phase3_advanced/ch3.5_contact/demo/vizdata.json";

// ---------------------------------------------------------------- typed vizdata
interface DropTrace {
  height: number[];
  pen_frac: number[];
  max_pen_frac: number;
  rest_pen_frac: number;
}
interface SweepPoint {
  dt: number;
  max_pen_frac: number | null;
  energy_excess: number | null;
  stable: boolean;
}
const RADIUS: number = viz.radius; // 0.1 m — the ball radius the table sits a ×radius depth into
const DROP = viz.drop as { t: number[]; window_s: number; penalty: DropTrace; lcp: DropTrace };
const SWEEP = viz.dt_sweep as {
  dt: number[];
  dt_crit: number;
  steps: number;
  default_dt: number;
  penalty: SweepPoint[];
  lcp: SweepPoint[];
};
const N_FRAMES = DROP.t.length; // 201
const REPLAY_MS = 28; // ~= the 8 ms recorded frame spacing, slowed a touch for the eye
// First frame the recorded penalty ball touches the table — where an unstable dt
// stops falling calmly and the explicit-spring integration begins to diverge.
const IMPACT_IDX = Math.max(0, DROP.penalty.pen_frac.findIndex((p) => p > 0)); // 54

// ------------------------------------------------------------- drop-lane geometry
// Two side-by-side lanes: the ball falls from ~1.05 m onto the table at world y = 0.
// World +y up; the ball CENTER rests at y = RADIUS (the ball sitting ON the table).
const LANE = { w: 320, h: 300 };
const FLOOR_Y = 250; // svg y of the table surface (world y = 0)
const WORLD_TOP = 1.12; // a hair above the drop height, so the ball starts near the top
const PPM = (FLOOR_Y - 26) / WORLD_TOP; // px per metre
const BALL_PX = RADIUS * PPM; // ~19.6 px
const LANE_CX = { penalty: 88, lcp: 232 }; // lane centres
const worldToSvgY = (wy: number) => FLOOR_Y - wy * PPM;

// ------------------------------------------------------------- penetration chart
const PV = { w: 460, h: 172 };
const PP = { l: 46, r: 16, t: 16, b: 30 };
const PVW = PV.w - PP.l - PP.r;
const PVH = PV.h - PP.t - PP.b;
const PEN_MAX = 0.28; // deepest ×radius the axis shows (penalty peaks at 0.251)
const penX = (t: number) => PP.l + (t / DROP.window_s) * PVW;
const penY = (frac: number) => PP.t + (frac / PEN_MAX) * PVH; // 0 (surface) at top, deep downward

// ------------------------------------------------------------------- cliff geometry
const CV = { w: 460, h: 244 };
const CP = { l: 54, r: 18, t: 26, b: 44 };
const CVW = CV.w - CP.l - CP.r;
const CVH = CV.h - CP.t - CP.b;
const N_DT = SWEEP.dt.length;
const cliffX = (i: number) => CP.l + (N_DT === 1 ? 0 : (i / (N_DT - 1)) * CVW);
const CLIFF_Y0 = CP.t + CVH; // baseline (stable / no excess)
const STABLE_BAND = 10.0; // energy excess below this is "bounded" — pinned to the baseline
const LOG_TOP = Math.log10(50000); // headroom above the worst measured explosion (~33000x)
/** Energy-excess -> svg y. Stable runs sit on the baseline; exploded runs lift off
 *  it and climb on a log scale, so the flat-then-detonate cliff shape is unmissable. */
function cliffY(excess: number | null): number {
  if (excess == null || excess >= STABLE_BAND) {
    const e = excess == null ? 60000 : Math.max(excess, STABLE_BAND);
    const f = (Math.log10(e) - 1) / (LOG_TOP - 1); // log10(10)=1 -> baseline-ish, LOG_TOP -> top
    return CLIFF_Y0 - (0.1 + 0.86 * Math.min(1, f)) * CVH; // small gap so exploded clearly lifts off
  }
  return CLIFF_Y0; // bounded -> the baseline
}
const DT_CRIT_IDX = SWEEP.dt.findIndex((d) => Math.abs(d - SWEEP.dt_crit) < 1e-9);
const DEFAULT_DT_IDX = Math.max(0, SWEEP.dt.findIndex((d) => Math.abs(d - SWEEP.default_dt) < 1e-9));
const PAST_CLIFF_IDX = SWEEP.dt.findIndex((d) => Math.abs(d - 0.03) < 1e-9); // the "push it over" target
const fmtDt = (d: number) => (d < 0.01 ? d.toFixed(3) : d.toFixed(3)).replace(/0+$/, "").replace(/\.$/, "");
const fmtX = (n: number) => (n >= 1000 ? `${Math.round(n / 1000)}k` : n >= 10 ? Math.round(n).toString() : n.toFixed(2));

// =============================================================== Panel 1: the drop
// `dtPoint` is the currently-selected timestep's penalty result. When it is unstable
// (dt past dt_crit) the LEFT lane stops replaying the calm recorded fall and instead
// DETONATES: the explicit spring flings the ball above the table one step and slams it
// deep below the next, the signature of the explicit-Euler blow-up. The swing shape is
// schematic, but the DEPTH (radii) and ENERGY multiplier printed on it are the real,
// measured sweep values for that dt — so pushing dt over the cliff shows a visible
// detonation in the ball view, not only a number in Panel 3.
function DropLanes({ frame, dtPoint, unstable }: { frame: number; dtPoint: SweepPoint; unstable: boolean }) {
  const lane = (key: "penalty" | "lcp") => {
    const tr = DROP[key];
    const wy = tr.height[frame];
    const cy = worldToSvgY(wy);
    const cx = LANE_CX[key];
    const pen = tr.pen_frac[frame]; // ×radius currently into the table
    const sunk = pen > 1e-4;
    return (
      <g class={`ck-lane ck-${key}`}>
        {/* the fall guide (faint), from the recorded drop height down to the table */}
        <line class="ck-fall" x1={cx} y1={worldToSvgY(tr.height[0])} x2={cx} y2={FLOOR_Y} />
        {/* the ball */}
        <circle class="ck-ball" cx={cx} cy={cy.toFixed(1)} r={BALL_PX.toFixed(1)} />
        {/* penetration caret: a small tick showing how deep the underside is */}
        {sunk && (
          <text class="ck-pen-tag" x={cx} y={FLOOR_Y + 20} text-anchor="middle">
            {pen >= 0.01 ? `−${pen.toFixed(2)}r` : "≈0"}
          </text>
        )}
        <text class="ck-lane-lab" x={cx} y={22} text-anchor="middle">{key}</text>
      </g>
    );
  };

  // The penalty lane in its blown-up state, driven by the dt slider (not the record).
  const blownPenaltyLane = () => {
    const cx0 = LANE_CX.penalty;
    // Before contact the ball still just falls (the shared recorded approach).
    if (frame < IMPACT_IDX) {
      const cy = worldToSvgY(DROP.penalty.height[frame]);
      return (
        <g class="ck-lane ck-penalty">
          <line class="ck-fall" x1={cx0} y1={worldToSvgY(DROP.penalty.height[0])} x2={cx0} y2={FLOOR_Y} />
          <circle class="ck-ball" cx={cx0} cy={cy.toFixed(1)} r={BALL_PX.toFixed(1)} />
          <text class="ck-lane-lab" x={cx0} y={22} text-anchor="middle">penalty</text>
        </g>
      );
    }
    // From contact on: a diverging oscillation whose amplitude ramps up fast.
    const swing = (k: number) => {
      const gr = Math.min(1, Math.pow(Math.max(0, k) / 11, 1.35)); // 0 → full swing within ~11 frames
      const wob = Math.sin(k * 1.9);
      const cy = FLOOR_Y - gr * wob * (FLOOR_Y + 46);              // wob>0 launches above, wob<0 slams below
      const cx = cx0 + gr * 13 * Math.sin(k * 3.3);               // violent lateral jitter
      return { cx, cy: Math.max(-BALL_PX - 6, Math.min(LANE.h - 4, cy)) };
    };
    const g = frame - IMPACT_IDX;
    const now = swing(g);
    const echoes = [g - 1, g - 2, g - 3].filter((k) => k >= 0).map(swing); // vibration smear
    const penetrating = now.cy > FLOOR_Y + 2;
    const depth = dtPoint.max_pen_frac;     // real radii of penetration for this dt
    const energy = dtPoint.energy_excess;   // real phantom-energy multiplier for this dt
    return (
      <g class="ck-lane ck-penalty ck-blown">
        {echoes.map((e, i) => (
          <circle class="ck-ball ck-ball-echo" cx={e.cx.toFixed(1)} cy={e.cy.toFixed(1)} r={BALL_PX.toFixed(1)} opacity={0.24 - i * 0.06} />
        ))}
        {/* launch trail when the spring flings the ball up off the table */}
        {now.cy < FLOOR_Y - 34 && <line class="ck-launch" x1={now.cx.toFixed(1)} y1={now.cy.toFixed(1)} x2={now.cx.toFixed(1)} y2={Math.min(FLOOR_Y, now.cy + 72).toFixed(1)} />}
        <circle class="ck-ball ck-ball-blown" cx={now.cx.toFixed(1)} cy={now.cy.toFixed(1)} r={BALL_PX.toFixed(1)} />
        {penetrating && depth != null && (
          <text class="ck-pen-tag" x={now.cx.toFixed(1)} y={FLOOR_Y + 20} text-anchor="middle">−{depth.toFixed(1)}r</text>
        )}
        <text class="ck-lane-lab" x={cx0} y={22} text-anchor="middle">penalty</text>
        {/* the unmissable state badge — real measured depth + energy for this dt */}
        <g class="ck-blown-badge">
          <rect class="ck-blown-bg" x={cx0 - 58} y={104} width={116} height={34} rx={5} />
          <text class="ck-blown-title" x={cx0} y={121} text-anchor="middle">BLEW UP</text>
          <text class="ck-blown-sub" x={cx0} y={132} text-anchor="middle">
            {energy == null ? "energy off the chart" : `energy +${Math.round(energy).toLocaleString()}×`}
          </text>
        </g>
      </g>
    );
  };

  return (
    <svg
      class={`ck-drop-svg${unstable ? " is-blown" : ""}`}
      viewBox={`0 0 ${LANE.w} ${LANE.h}`}
      role="img"
      aria-label={
        unstable
          ? "Two side-by-side lanes. With the timestep past dt_crit the PENALTY lane (left) has blown up: the explicit " +
            "spring flings the ball above the table and slams it many radii below the surface, diverging, while the LCP " +
            "solve (right) still catches the ball and holds it exactly on the surface."
          : "Two side-by-side lanes: a ball dropping onto a table under the PENALTY spring (left) and the LCP impulse " +
            "solve (right). On impact the penalty ball drives about a quarter of its radius into the table and settles " +
            "sunk below the surface, while the LCP ball catches on the surface in about one step and rests exactly on it."
      }
    >
      {/* mid divider */}
      <line class="ck-divider" x1={LANE.w / 2} y1={30} x2={LANE.w / 2} y2={FLOOR_Y} />
      {unstable ? blownPenaltyLane() : lane("penalty")}
      {lane("lcp")}
      {/* the table: an opaque-ish band the sunk ball shows through, + a crisp surface line */}
      <rect class="ck-table" x={0} y={FLOOR_Y} width={LANE.w} height={LANE.h - FLOOR_Y} />
      <line class="ck-surface" x1={0} y1={FLOOR_Y} x2={LANE.w} y2={FLOOR_Y} />
      <text class="ck-surface-lab" x={LANE.w - 6} y={FLOOR_Y - 6} text-anchor="end">table surface</text>
    </svg>
  );
}

// ============================================================ Panel 2: penetration
function PenetrationChart({ frame }: { frame: number }) {
  const curve = (key: "penalty" | "lcp", upto: number | null) => {
    const tr = DROP[key];
    const n = upto == null ? DROP.t.length : Math.min(upto + 1, DROP.t.length);
    return DROP.t.slice(0, n).map((t, i) => `${penX(t).toFixed(1)},${penY(tr.pen_frac[i]).toFixed(1)}`).join(" ");
  };
  const y0 = penY(0);
  return (
    <svg
      class="ck-pen-svg"
      viewBox={`0 0 ${PV.w} ${PV.h}`}
      role="img"
      aria-label={
        "Line chart: penetration depth into the table, as a fraction of the ball radius, versus time. Down is deeper. " +
        "The penalty curve plunges to about 0.25 of a radius on impact, rings, and settles about 0.0098 below the surface " +
        "(mg over k — it lives inside the table). The LCP curve barely dips, about 0.057, then holds at zero on the surface."
      }
    >
      {/* surface (0) + depth grid */}
      <line class="ck-pen-surface" x1={PP.l} y1={y0} x2={PV.w - PP.r} y2={y0} />
      <text class="ck-pen-surflab" x={PP.l - 6} y={y0 + 3} text-anchor="end">0</text>
      <text class="ck-pen-surfnote" x={PV.w - PP.r} y={y0 - 4} text-anchor="end">surface</text>
      {[0.1, 0.2].map((g) => (
        <g>
          <line class="ck-pen-grid" x1={PP.l} y1={penY(g)} x2={PV.w - PP.r} y2={penY(g)} />
          <text class="ck-pen-ylab" x={PP.l - 6} y={penY(g) + 3} text-anchor="end">{g.toFixed(1)}</text>
        </g>
      ))}
      <text class="ck-pen-ytitle" transform={`translate(13 ${PP.t + PVH / 2}) rotate(-90)`} text-anchor="middle">
        depth (×radius)
      </text>

      {/* full faint curves (the complete story — the JS-off frame), then the replayed portion */}
      <polyline class="ck-pen-ghost ck-lcp-stroke" points={curve("lcp", null)} />
      <polyline class="ck-pen-ghost ck-penalty-stroke" points={curve("penalty", null)} />
      <polyline class="ck-pen-line ck-lcp-stroke" points={curve("lcp", frame)} />
      <polyline class="ck-pen-line ck-penalty-stroke" points={curve("penalty", frame)} />
      {/* heads at the current frame */}
      <circle class="ck-pen-head ck-lcp-fill" cx={penX(DROP.t[frame])} cy={penY(DROP.lcp.pen_frac[frame])} r={3} />
      <circle class="ck-pen-head ck-penalty-fill" cx={penX(DROP.t[frame])} cy={penY(DROP.penalty.pen_frac[frame])} r={3.2} />

      <text class="ck-pen-xtitle" x={PP.l + PVW / 2} y={PV.h - 4} text-anchor="middle">time (s)</text>
    </svg>
  );
}

// ============================================================== Panel 3: the cliff
function CliffChart({ sel, onPick }: { sel: number; onPick: (i: number) => void }) {
  const penPts = SWEEP.penalty.map((p, i) => `${cliffX(i).toFixed(1)},${cliffY(p.energy_excess).toFixed(1)}`);
  const lcpY = cliffY(0); // lcp is bounded everywhere -> flat on the baseline
  const critX = DT_CRIT_IDX >= 0 ? cliffX(DT_CRIT_IDX) : null;
  return (
    <svg
      class="ck-cliff-svg"
      viewBox={`0 0 ${CV.w} ${CV.h}`}
      role="img"
      aria-label={
        "Line chart, the timestep cliff: the penalty spring's phantom energy gain versus the timestep dt. " +
        "It stays flat at zero (bounded) up to about dt 0.012, then detonates past dt_crit = 0.02 — 267 times, " +
        "then 2625 times the drop energy. The LCP solve stays flat on zero across every dt: no spring to blow up."
      }
    >
      {/* baseline + axes */}
      <line class="ck-ax" x1={CP.l} y1={CLIFF_Y0} x2={CV.w - CP.r} y2={CLIFF_Y0} />
      <line class="ck-ax" x1={CP.l} y1={CP.t} x2={CP.l} y2={CLIFF_Y0} />
      <text class="ck-cliff-ylab" x={CP.l - 6} y={CLIFF_Y0 + 3} text-anchor="end">0</text>
      {[100, 10000].map((e) => (
        <g>
          <line class="ck-cliff-grid" x1={CP.l} y1={cliffY(e)} x2={CV.w - CP.r} y2={cliffY(e)} />
          <text class="ck-cliff-ylab" x={CP.l - 6} y={cliffY(e) + 3} text-anchor="end">{fmtX(e)}×</text>
        </g>
      ))}
      <text class="ck-cliff-ytitle" transform={`translate(14 ${CP.t + CVH / 2}) rotate(-90)`} text-anchor="middle">
        phantom energy gain
      </text>

      {/* dt_crit marker — 2*sqrt(m/k) */}
      {critX != null && (
        <g class="ck-crit">
          <line class="ck-crit-line" x1={critX} y1={CP.t} x2={critX} y2={CLIFF_Y0} />
          <text class="ck-crit-lab" x={critX} y={CP.t - 8} text-anchor="middle">dt_crit = 2√(m/k)</text>
        </g>
      )}

      {/* LCP — flat, bounded, holds (green) */}
      <line class="ck-lcp-stroke ck-cliff-lcp" x1={cliffX(0)} y1={lcpY} x2={cliffX(N_DT - 1)} y2={lcpY} />
      <text class="ck-cliff-lcplab" x={cliffX(N_DT - 1)} y={lcpY + 14} text-anchor="end">lcp holds · bounded</text>

      {/* PENALTY — flat then detonates (red) */}
      <polyline class="ck-penalty-stroke ck-cliff-pen" points={penPts.join(" ")} />
      {SWEEP.penalty.map((p, i) => {
        const active = i === sel;
        const x = cliffX(i), y = cliffY(p.energy_excess);
        return (
          <g class={`ck-cliff-node${active ? " is-active" : ""}${p.stable ? " is-stable" : " is-blown"}`} onClick={() => onPick(i)}>
            {active && <line class="ck-cliff-drop" x1={x} y1={y} x2={x} y2={CLIFF_Y0} />}
            <circle class="ck-cliff-hit" cx={x} cy={y} r={12} />
            <circle cx={x} cy={y.toFixed(1)} r={active ? 5 : 3} />
            {(i % 2 === 0 || active) && (
              <text class="ck-cliff-xlab" x={x} y={CV.h - CP.b + 15} text-anchor="middle">{fmtDt(p.dt)}</text>
            )}
          </g>
        );
      })}
      <text class="ck-cliff-xtitle" x={CP.l + CVW / 2} y={CV.h - 3} text-anchor="middle">timestep dt (s)</text>
    </svg>
  );
}

// ==================================================================== the island
function Toy() {
  const [frame, setFrame] = useState(N_FRAMES - 1); // SSR = the settled frame (the poster)
  const [playing, setPlaying] = useState(false);
  const [dtSel, setDtSel] = useState(DEFAULT_DT_IDX); // boot on a calm dt — dragging over the cliff is the aha
  const timer = useRef<number | null>(null);

  // Post-hydration: rewind and replay the drop — unless the visitor prefers reduced
  // motion, in which case we keep the settled frame (the full curves already tell it).
  useEffect(() => {
    const reduce = typeof matchMedia === "function" && matchMedia("(prefers-reduced-motion: reduce)").matches;
    if (reduce) return;
    setFrame(0);
    setPlaying(true);
    return () => { if (timer.current != null) clearInterval(timer.current); };
  }, []);

  useEffect(() => {
    if (!playing) return;
    const id = window.setInterval(() => {
      setFrame((f) => {
        if (f >= N_FRAMES - 1) { setPlaying(false); return f; }
        return f + 1;
      });
    }, REPLAY_MS);
    timer.current = id;
    return () => clearInterval(id);
  }, [playing]);

  const prefersReduced = () =>
    typeof matchMedia === "function" && matchMedia("(prefers-reduced-motion: reduce)").matches;
  const replay = () => {
    if (prefersReduced()) { setPlaying(false); setFrame(N_FRAMES - 1); return; } // static settled/blown frame
    setFrame(0);
    setPlaying(true);
  };
  // push dt over the cliff AND replay the drop, so the detonation plays out in the ball view
  const pushOverCliff = () => { setDtSel(PAST_CLIFF_IDX); replay(); };
  const onScrub = (e: Event) => {
    setPlaying(false);
    setFrame(parseInt((e.currentTarget as HTMLInputElement).value, 10));
  };
  const onDt = (e: Event) => setDtSel(parseInt((e.currentTarget as HTMLInputElement).value, 10));

  const pen = SWEEP.penalty[dtSel];
  const dtVal = pen.dt;
  const penFrac = DROP.penalty.pen_frac[frame];
  const lcpFrac = DROP.lcp.pen_frac[frame];

  // aria-live: the drop replay, coarse phases so the reader isn't spammed per-frame
  const t = DROP.t[frame];
  const dropSay =
    frame >= N_FRAMES - 1
      ? `Settled: the penalty ball rests ${(DROP.penalty.rest_pen_frac).toFixed(4)} of a radius INSIDE the table (mg over k); ` +
        `the LCP ball rests exactly on the surface, zero penetration.`
      : t < 0.4
        ? "Falling: both balls drop toward the table."
        : penFrac > 0.15
          ? `Impact: the penalty ball is ${penFrac.toFixed(2)} of a radius into the table; the LCP ball ${lcpFrac.toFixed(2)}.`
          : "Settling: the penalty spring rings while the LCP solve already holds.";
  // when the selected dt is unstable, the ball view detonates — say so
  const blownSay = !pen.stable
    ? ` At the selected timestep dt ${fmtDt(dtVal)}, past dt_crit, the penalty ball in the drop view BLOWS UP: the spring ` +
      `flings it off the table and slams it ${pen.max_pen_frac == null ? "many" : pen.max_pen_frac.toFixed(1)} radii deep, ` +
      `phantom energy ${pen.energy_excess == null ? "off the chart" : `${Math.round(pen.energy_excess).toLocaleString()} times`} the drop energy.`
    : "";

  // aria-live: the dt cliff selection (the stability readout)
  const cliffSay =
    `Timestep dt ${fmtDt(dtVal)} seconds` +
    (dtVal >= SWEEP.dt_crit ? ` — at or past dt_crit ${SWEEP.dt_crit}. ` : `, below dt_crit ${SWEEP.dt_crit}. `) +
    (pen.stable
      ? `Penalty is stable: energy gain bounded. `
      : `Penalty EXPLODES: phantom energy gain ${pen.energy_excess == null ? "off the chart" : `${Math.round(pen.energy_excess)} times`} the drop energy` +
        `${pen.max_pen_frac == null ? "" : `, ${pen.max_pen_frac.toFixed(1)} radii of penetration`}. `) +
    `The LCP solve stays bounded and holds the ball.`;

  return (
    <div class="ck">
      {/* honesty banner — recorded, replayed, not a live sim */}
      <p class="ck-recorded">
        recorded run · seed 0 · cpu — <b>replayed, not live</b>: contact.py's engine is ~400 lines of pure numpy, matched to meta.yaml
      </p>

      {/* ---- Panel 1: the drop, penalty vs lcp ------------------------------ */}
      <figure class={`ck-panel ck-panel-drop${pen.stable ? "" : " is-blown"}`}>
        <figcaption class="ck-cap">
          the drop · a ball onto the table · <span class="ck-e-pen">penalty</span> vs <span class="ck-e-lcp">lcp</span>
          {pen.stable
            ? <span class="ck-cap-hint"> · drag the dt slider below past dt_crit to detonate the penalty ball</span>
            : <span class="ck-cap-hint ck-e-pen"> · dt {fmtDt(dtVal)}s past dt_crit — penalty BLEW UP</span>}
        </figcaption>
        <DropLanes frame={frame} dtPoint={pen} unstable={!pen.stable} />
        <div class="ck-scrub-row">
          <button type="button" class="ck-btn ck-btn--primary" onClick={replay}>
            {playing ? "playing…" : "▶ replay the drop"}
          </button>
          <input
            class="ck-scrub"
            type="range"
            min={0}
            max={N_FRAMES - 1}
            step={1}
            value={frame}
            onInput={onScrub}
            aria-label="Scrub the recorded drop. Drag to step through the fall and watch the penalty ball sink into the table while the LCP ball holds on the surface."
            aria-valuetext={`Time ${DROP.t[frame].toFixed(2)} of ${DROP.window_s} seconds; penalty ${penFrac.toFixed(3)} radii into the table, lcp ${lcpFrac.toFixed(3)}`}
          />
          <span class="ck-scrub-val">{DROP.t[frame].toFixed(2)}s</span>
        </div>
        <p class="ck-drop-note">
          the calm drop is the recorded dt=0.002s run; past dt_crit the penalty lane shows the blow-up — the swing is
          schematic, the depth and energy printed on it are the real measured sweep values
        </p>
      </figure>

      {/* ---- Panel 2: penetration over time (linked to the same replay frame) */}
      <figure class="ck-panel ck-panel-pen">
        <figcaption class="ck-cap">penetration depth over time · penalty allows real penetration <b>by design</b></figcaption>
        <PenetrationChart frame={frame} />
        <div class="ck-pen-read" aria-hidden="true">
          <span class="ck-read ck-e-pen">penalty: peak −{DROP.penalty.max_pen_frac.toFixed(2)}r · rests −{DROP.penalty.rest_pen_frac.toFixed(4)}r (mg/k)</span>
          <span class="ck-read ck-e-lcp">lcp: peak −{DROP.lcp.max_pen_frac.toFixed(3)}r · rests on the surface (0)</span>
        </div>
      </figure>

      {/* ---- Panel 3: the dt cliff (the interactive headline) --------------- */}
      <figure class="ck-panel ck-panel-cliff">
        <figcaption class="ck-cap">the dt cliff · drag the timestep past dt_crit and only <span class="ck-e-pen">penalty</span> detonates</figcaption>
        <CliffChart sel={dtSel} onPick={setDtSel} />
        <div class="ck-cliff-read" aria-hidden="true">
          <div class="ck-cliff-dt">dt = <b>{fmtDt(dtVal)}s</b>{dtVal >= SWEEP.dt_crit ? " ▲ past dt_crit" : ""}</div>
          <div class={`ck-cliff-state ck-e-pen ${pen.stable ? "" : "is-blown"}`}>
            penalty: {pen.stable
              ? "stable · energy bounded"
              : <>EXPLODES · energy +{pen.energy_excess == null ? "∞" : `${Math.round(pen.energy_excess).toLocaleString()}×`}{pen.max_pen_frac != null ? ` · ${pen.max_pen_frac.toFixed(1)}r deep` : ""}</>}
          </div>
          <div class="ck-cliff-state ck-e-lcp">lcp: holds · energy bounded</div>
        </div>
        <div class="ck-cliff-controls">
          <div class="ck-slider-row">
            <label class="ck-slider-label" for="ck-dt">timestep <b>dt</b></label>
            <input
              id="ck-dt"
              class="ck-slider"
              type="range"
              min={0}
              max={N_DT - 1}
              step={1}
              value={dtSel}
              onInput={onDt}
              list="ck-dt-ticks"
              aria-label="The simulation timestep dt. Slide right, past the critical timestep at 0.02 seconds, to watch the penalty spring's energy detonate while the LCP solve stays bounded."
              aria-valuetext={cliffSay}
            />
            <datalist id="ck-dt-ticks">
              {SWEEP.dt.map((d, i) => <option value={i} label={fmtDt(d)} />)}
            </datalist>
            <span class={`ck-dt-val ${pen.stable ? "" : "ck-dt-blown"}`}>{fmtDt(dtVal)}s</span>
          </div>
          <div class="ck-btn-row">
            {PAST_CLIFF_IDX >= 0 && (
              <button type="button" class="ck-btn" onClick={pushOverCliff}>
                push dt over the cliff →
              </button>
            )}
            <button type="button" class="ck-btn" onClick={() => setDtSel(DEFAULT_DT_IDX)}>reset dt</button>
            <span class="ck-note">
              penalty stable to dt≈{fmtDt(viz.stability.penalty_stable_dt)}s · lcp to ≈{fmtDt(viz.stability.lcp_stable_dt)}s · poster reads with JS off
            </span>
          </div>
        </div>
      </figure>

      {/* honest limits — the trade, and what neither solver does */}
      <p class="ck-limits">
        Honest limits: <b>frictionless normal contact only</b> (point masses with a radius — no rotation, no friction cone),
        and the LCP solve is a fixed-iteration <b>projected Gauss-Seidel</b>, not a true LCP pivot. LCP still penetrates
        ~one step of approach velocity on a fast impact (no continuous collision detection) and leans on a hand-tuned
        Baumgarte push — it is <b>better, not exact</b>. The penalty-vs-complementarity trade is the payoff: penalty is
        trivial but stiff and brittle; hard complementarity holds but is a solve; MuJoCo's soft convex contact is the
        principled middle.
      </p>

      {/* non-visual paths to the two ahas (the drop, and the stability cliff) */}
      <div class="bk-sr" aria-live="polite">{dropSay}{blownSay}</div>
      <div class="bk-sr" aria-live="polite">{cliffSay}</div>
    </div>
  );
}

export default function ContactToy() {
  return <Toy />;
}
