/**
 * ch0.5 "Inspecting Your Dataset" — the DATASET-INSPECTOR concept-toy
 * (`demo: pusht-inspect`).
 *
 * A RECORDED-DATA sibling of ch1.7's VLA browser: no MuJoCo-WASM, no inference, no
 * lazy heavy import. The chapter trains NO policy — its artifact loads a recorded
 * LeRobot v3 dataset back and reads it. So this island is a pure DATA-INSPECTION
 * panel over a small, committed, TEXT-ONLY JSON (curriculum/.../demo/vizdata.json,
 * regenerated by site/scripts/vizdata/ch0.5_inspect.py from inspect.py's OWN
 * provision/load/inspect functions, seed 0, cpu — matching meta.yaml ex1). The
 * whole toy server-renders, so with JS off you get episode 1's first frame, the
 * full dataset-stats panel, and the lesson — the entire experience; JS only adds
 * scrub/step/replay + the episode selector.
 *
 * It teaches what a demonstration dataset IS, in three panels:
 *   1. SCRUB an episode — step frame-by-frame through a recorded demonstration. A
 *      top-down arena is DECODED from the raw 10-D observation the robot stored
 *      (pusher xy = obs[0:2], block xy = obs[2:4], block yaw = atan2(sin, cos) =
 *      obs[4:6] — the one correct read, "seeing like a robot"), and the recorded
 *      action [vx, vy] rides along as a blue arrow off the pusher + a bar readout.
 *      The faint magenta trail is the block's whole recorded path.
 *   2. DATASET STATS — the honest shape: episode count, per-episode lengths, total
 *      frames, and the success rate RECONSTRUCTED from the terminal frame (the
 *      dataset stores no reward/success column), plus per-dim state + action ranges.
 *   3. THE LESSON — these (state, action) pairs, and nothing more, are what
 *      behavior cloning fits a function between.
 *
 * a11y: the scrub slider is a native range (screen readers get frame + pos-err via
 * aria-valuetext); prev/next/replay/episode are native buttons; the arena region
 * takes ← → to step and Home/End to jump. An aria-live region announces the
 * episode (its length + reconstructed reached), not per-frame spam. Theme-aware:
 * reads the page's flipping design tokens with light fallbacks; the entity hues get
 * a dark-mode brighten in the co-located CSS. Reduced-motion: replay auto-advance
 * is disabled and bar/path transitions are cut.
 */
import "./DatasetInspectToy.css";
import { useEffect, useMemo, useRef, useState } from "preact/hooks";
import vizRaw from "../../../../curriculum/phase0_foundations/ch0.5_inspect/demo/vizdata.json";

// ------------------------------------------------------------------- data shape
interface DiFrame {
  i: number;
  state: number[];   // 10-D observation.state the robot stored
  action: number[];  // 2-D recorded action [pusher_vx, pusher_vy]
  tee_yaw: number;   // decoded atan2(sin, cos) — radians
  pos_err: number;
  ang_err: number;
}
interface DiEpisode {
  index: number;
  length: number;
  reached: boolean;
  final_pos_err: number;
  final_ang_err: number;
  frames: DiFrame[];
}
interface DiRange { name: string; min: number; max: number; mean: number; }
interface DiData {
  provenance: Record<string, unknown>;
  task: string;
  schema: {
    obs_dim: number; act_dim: number; fps: number;
    feature_keys: string[]; state_names: string[]; action_names: string[];
  };
  tolerances: { pos_tol_m: number; ang_tol_rad: number };
  target: { x: number; y: number; yaw: number };
  world_half_extent_m: number;
  stats: {
    n_episodes: number; n_frames: number; episode_lengths: number[];
    mean_episode_length: number; n_reached: number; success_rate: number;
    success_rate_yaw_swap: number; reached: boolean[];
    final_pos_err: number[]; final_ang_err: number[];
  };
  state_ranges: DiRange[];
  action_ranges: DiRange[];
  episodes: DiEpisode[];
}
const DATA = vizRaw as unknown as DiData;

// ------------------------------------------------------------------- geometry
// World → SVG px, same convention as PlateIsland's poster: square viewBox, world
// +y is up (SVG y is down, so we subtract). One fixed frame for every episode, so
// scrubbing never reflows.
const V = 360;
const HALF = DATA.world_half_extent_m;
const S = V / (2 * HALF);
const w2s = (x: number, y: number): [number, number] => [V / 2 + x * S, V / 2 - y * S];
const RAD2DEG = 180 / Math.PI;

// tee "T" geometry in world metres (matches inspect.py _TEE_HALF / PlateIsland):
// bar 0.12×0.03, stem 0.03×0.09 hanging toward the block's −y.
const BAR_W = 0.12 * S, BAR_H = 0.03 * S;
const STEM_W = 0.03 * S, STEM_H = 0.09 * S, STEM_OFF = 0.06 * S;
const ACT_SCALE = 0.11 * S; // an |action|=1 m/s arrow spans ~0.11 m on the arena

const fmt = (v: number, d = 2) => (v >= 0 ? "+" : "−") + Math.abs(v).toFixed(d);
const clamp = (v: number, lo: number, hi: number) => Math.max(lo, Math.min(hi, v));

/** A PushT "T" at world (x,y) rotated by yaw (radians). filled|outline styles. */
function Tee({ x, y, yaw, cls }: { x: number; y: number; yaw: number; cls: string }) {
  const [cx, cy] = w2s(x, y);
  return (
    <g class={cls} transform={`translate(${cx.toFixed(1)} ${cy.toFixed(1)}) rotate(${(-yaw * RAD2DEG).toFixed(1)})`}>
      <rect x={-BAR_W / 2} y={-BAR_H / 2} width={BAR_W} height={BAR_H} rx={2} />
      <rect x={-STEM_W / 2} y={STEM_OFF - STEM_H / 2} width={STEM_W} height={STEM_H} rx={2} />
    </g>
  );
}

// ================================================================ THE ARENA
/** Top-down replay of ONE frame, decoded from the raw observation, with the
 *  block's whole recorded path behind it and the recorded action as an arrow. */
function Arena({ ep, f }: { ep: DiEpisode; f: number }) {
  const fr = ep.frames[f];
  const [px, py] = fr.state;         // pusher
  const [, , tx, ty] = fr.state;     // block (tee) centre
  const [avx, avy] = fr.action;

  // the recorded block trail (all frames) — makes "this is a recorded episode" visible
  const trail = ep.frames.map((g) => w2s(g.state[2], g.state[3]).map((n) => n.toFixed(1)).join(",")).join(" ");
  const [ppx, ppy] = w2s(px, py);
  const [aex, aey] = w2s(px + avx * (ACT_SCALE / S), py + avy * (ACT_SCALE / S));
  const aLen = Math.hypot(aex - ppx, aey - ppy);
  const target = DATA.target;

  const grid = Array.from({ length: 9 }, (_, i) => ((i + 1) * V) / 10);

  return (
    <svg
      class="di-arena"
      viewBox={`0 0 ${V} ${V}`}
      role="img"
      aria-label={
        `Top-down PushT arena, frame ${fr.i + 1} of episode ${ep.index + 1}. The magenta T-block sits ` +
        `${fr.pos_err.toFixed(3)} metres from the green target with a ${fr.ang_err.toFixed(2)} radian yaw error; ` +
        `the amber pusher carries the recorded action arrow. A faint magenta trail shows the block's whole recorded path.`
      }
    >
      <rect class="di-bg" x={1} y={1} width={V - 2} height={V - 2} rx={6} />
      <g class="di-grid">
        {grid.map((v) => <line x1={v} y1={2} x2={v} y2={V - 2} />)}
        {grid.map((v) => <line x1={2} y1={v} x2={V - 2} y2={v} />)}
      </g>

      {/* the recorded block path (behind everything) */}
      <polyline class="di-trail" points={trail} />

      {/* target pose — dashed green outline at the origin */}
      <Tee x={target.x} y={target.y} yaw={target.yaw} cls="di-target" />
      <text class="di-lab di-lab-target" x={w2s(target.x + 0.02, target.y + 0.03)[0]} y={w2s(target.x + 0.02, target.y + 0.03)[1]}>target</text>

      {/* the block (decoded from obs[2:6]) */}
      <Tee x={tx} y={ty} yaw={fr.tee_yaw} cls="di-tee" />

      {/* the pusher (obs[0:2]) + the recorded action arrow (signal blue) */}
      <g transform={`translate(${ppx.toFixed(1)} ${ppy.toFixed(1)})`}>
        <circle class="di-pusher-ring" r={0.03 * S} />
        <circle class="di-pusher" r={0.016 * S} />
      </g>
      {aLen > 1.5 && (
        <g class="di-action">
          <line x1={ppx.toFixed(1)} y1={ppy.toFixed(1)} x2={aex.toFixed(1)} y2={aey.toFixed(1)} marker-end="url(#di-arrow)" />
        </g>
      )}
      <defs>
        <marker id="di-arrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse">
          <path d="M0 0 L10 5 L0 10 z" />
        </marker>
      </defs>
    </svg>
  );
}

// ================================================================ ACTION BARS
/** The recorded action [vx, vy] as diverging bars around a centre zero (±1 scale). */
function ActionBars({ action, names }: { action: number[]; names: string[] }) {
  return (
    <div class="di-actbars">
      {action.map((v, i) => {
        const w = clamp(Math.abs(v), 0, 1) * 50;
        const pos = v >= 0;
        return (
          <div class="di-actrow" key={i}>
            <span class="di-actlab">{names[i]}</span>
            <div class="di-acttrack">
              <span class="di-actzero" />
              <span class="di-actfill" data-pos={pos} style={`width:${w}%; ${pos ? "left:50%" : "right:50%"}`} />
            </div>
            <span class="di-actval">{fmt(v)}</span>
          </div>
        );
      })}
    </div>
  );
}

// ================================================================ RANGE ROWS
/** Per-dim min–max range as a bar on a shared symmetric scale, with the mean tick. */
function RangeRows({ rows, span }: { rows: DiRange[]; span: number }) {
  const map = (v: number) => ((v + span) / (2 * span)) * 100;
  return (
    <div class="di-ranges">
      {rows.map((r) => (
        <div class="di-rangerow" key={r.name}>
          <span class="di-rangelab">{r.name}</span>
          <div class="di-rangetrack">
            <span class="di-rangezero" />
            <span class="di-rangebar" style={`left:${map(r.min).toFixed(1)}%; right:${(100 - map(r.max)).toFixed(1)}%`} />
            <span class="di-rangemean" style={`left:${map(r.mean).toFixed(1)}%`} />
          </div>
          <span class="di-rangeval">{r.min.toFixed(2)} … {r.max.toFixed(2)}</span>
        </div>
      ))}
    </div>
  );
}

// ==================================================================== THE ISLAND
function DatasetInspect() {
  const eps = DATA.episodes;
  const stats = DATA.stats;
  const schema = DATA.schema;
  const [epIdx, setEpIdx] = useState(0);
  const [f, setF] = useState(0);
  const [playing, setPlaying] = useState(false);
  const [announce, setAnnounce] = useState("");
  const arenaRef = useRef<HTMLDivElement>(null);

  const ep = eps[epIdx];
  const nF = ep.frames.length;
  const fr = ep.frames[clamp(f, 0, nF - 1)];

  const reduce = useMemo(
    () => typeof window !== "undefined" && window.matchMedia
      && window.matchMedia("(prefers-reduced-motion: reduce)").matches,
    [],
  );

  // switching episode resets the scrub + stops replay
  const pickEpisode = (i: number) => { setEpIdx(i); setF(0); setPlaying(false); };

  // announce the EPISODE (length + reconstructed reached), not per-frame spam — the
  // slider's aria-valuetext carries the live per-frame numbers for screen readers.
  useEffect(() => {
    setAnnounce(
      `Episode ${epIdx + 1} of ${stats.n_episodes}. ${ep.length} frames. ` +
      `Reconstructed from its final frame, this demonstration ${ep.reached ? "reached" : "did not reach"} the target ` +
      `(final position error ${ep.final_pos_err.toFixed(3)} metres). Use the arrow keys or the slider to scrub.`,
    );
  }, [epIdx]);

  // recorded replay: auto-advance the scrub. Skipped entirely under reduced-motion
  // (the button is hidden there); manual scrubbing always works.
  useEffect(() => {
    if (!playing || reduce) return;
    let raf = 0, last = performance.now();
    const step = (now: number) => {
      if (now - last >= 120) { // ~8 subsampled frames/s — a watchable replay
        last = now;
        setF((p) => {
          if (p >= nF - 1) { setPlaying(false); return p; }
          return p + 1;
        });
      }
      raf = requestAnimationFrame(step);
    };
    raf = requestAnimationFrame(step);
    return () => cancelAnimationFrame(raf);
  }, [playing, epIdx, reduce, nF]);

  const onScrub = (e: Event) => { setF(parseInt((e.currentTarget as HTMLInputElement).value, 10)); setPlaying(false); };
  const onKeyDown = (e: KeyboardEvent) => {
    if (e.key === "ArrowRight" || e.key === "ArrowDown") { e.preventDefault(); setPlaying(false); setF((p) => Math.min(nF - 1, p + 1)); }
    else if (e.key === "ArrowLeft" || e.key === "ArrowUp") { e.preventDefault(); setPlaying(false); setF((p) => Math.max(0, p - 1)); }
    else if (e.key === "Home") { e.preventDefault(); setPlaying(false); setF(0); }
    else if (e.key === "End") { e.preventDefault(); setPlaying(false); setF(nF - 1); }
  };

  // symmetric range span for the state/action range bars (whole-dataset shape)
  const stateSpan = Math.max(1e-6, ...DATA.state_ranges.flatMap((r) => [Math.abs(r.min), Math.abs(r.max)]));
  const actSpan = 1; // actions are clipped to ±1 by the env

  return (
    <div class="di">
      {/* ============================ PANEL 1 — SCRUB AN EPISODE ================= */}
      <div class="di-panels">
        <figure class="di-figure">
          <figcaption class="di-cap" aria-hidden="true">
            <span>scrub a recorded demonstration</span>
            <b>episode {epIdx + 1}/{stats.n_episodes} · frame {fr.i + 1}/{ep.length}</b>
          </figcaption>
          <div
            class="di-arena-wrap"
            ref={arenaRef}
            tabIndex={0}
            role="group"
            aria-label="Recorded PushT demonstration. Use the arrow keys to step frames, Home and End to jump to the first or last frame."
            onKeyDown={onKeyDown}
          >
            <Arena ep={ep} f={clamp(f, 0, nF - 1)} />
          </div>

          {/* the scrub control — a native range so screen readers get frame + pos-err */}
          <div class="di-scrub">
            <button type="button" class="di-icon" aria-label="Previous frame" onClick={() => { setPlaying(false); setF((p) => Math.max(0, p - 1)); }}>‹</button>
            {!reduce && (
              <button type="button" class="di-icon di-play" aria-pressed={playing} aria-label={playing ? "Pause replay" : "Play the recorded episode"} onClick={() => { if (f >= nF - 1) setF(0); setPlaying((v) => !v); }}>
                {playing ? "❚❚" : "▶"}
              </button>
            )}
            <input
              class="di-slider"
              type="range"
              min={0}
              max={nF - 1}
              step={1}
              value={clamp(f, 0, nF - 1)}
              onInput={onScrub}
              aria-label="Scrub the recorded episode frame by frame"
              aria-valuetext={`frame ${fr.i + 1} of ${ep.length}, block ${fr.pos_err.toFixed(3)} metres from target`}
            />
            <button type="button" class="di-icon" aria-label="Next frame" onClick={() => { setPlaying(false); setF((p) => Math.min(nF - 1, p + 1)); }}>›</button>
          </div>

          {/* per-frame readout: the raw obs the robot saw + the recorded action */}
          <div class="di-frame" aria-hidden="true">
            <div class="di-frame-k">→ recorded action · {schema.act_dim}-D (m/s)</div>
            <ActionBars action={fr.action} names={schema.action_names} />
            <div class="di-frame-row">
              <span>block → target</span>
              <b class={fr.pos_err < DATA.tolerances.pos_tol_m ? "di-ok" : ""}>{fr.pos_err.toFixed(3)} m</b>
            </div>
            <div class="di-frame-row">
              <span>yaw error (from sin/cos)</span>
              <b class={fr.ang_err < DATA.tolerances.ang_tol_rad ? "di-ok" : ""}>{fr.ang_err.toFixed(2)} rad</b>
            </div>
            <div class="di-state" title="the raw observation.state the robot stored">
              {fr.state.map((v, i) => (
                <span class="di-statev" key={i} title={schema.state_names[i]}>{fmt(v)}</span>
              ))}
            </div>
            <div class="di-frame-note">obs[0:2] pusher · obs[2:4] block · obs[4:6] sin/cos yaw · obs[6:10] target</div>
          </div>
        </figure>

        {/* ============================ PANEL 2 — DATASET STATS ================= */}
        <figure class="di-figure di-stats">
          <figcaption class="di-cap" aria-hidden="true">
            <span>the honest dataset shape</span>
            <b>LeRobot v3 · seed 0</b>
          </figcaption>

          {/* headline tiles */}
          <div class="di-tiles">
            <div class="di-tile"><span class="di-tile-v">{stats.n_episodes}</span><span class="di-tile-k">episodes</span></div>
            <div class="di-tile"><span class="di-tile-v">{stats.n_frames}</span><span class="di-tile-k">frames</span></div>
            <div class="di-tile"><span class="di-tile-v">{Math.round(stats.mean_episode_length)}</span><span class="di-tile-k">mean length</span></div>
            <div class="di-tile"><span class="di-tile-v di-ok">{Math.round(stats.success_rate * 100)}%</span><span class="di-tile-k">reached *</span></div>
          </div>

          {/* per-episode lengths — a tiny bar chart; the active episode is highlighted */}
          <div class="di-lenrow" aria-hidden="true">
            <span class="di-mini-k">episode lengths (frames)</span>
            <div class="di-lens">
              {stats.episode_lengths.map((L, i) => {
                const h = (L / Math.max(...stats.episode_lengths)) * 100;
                return (
                  <button type="button" key={i} class="di-lenbar" data-active={i === epIdx} data-reached={stats.reached[i]}
                    style={`height:${h}%`} aria-hidden="true" tabIndex={-1} onClick={() => pickEpisode(i)}>
                    <span class="di-lenval">{L}</span>
                  </button>
                );
              })}
            </div>
          </div>

          {/* schema — what every frame IS */}
          <div class="di-schema">
            <span class="di-chip">observation.state · {schema.obs_dim}-D</span>
            <span class="di-chip">action · {schema.act_dim}-D</span>
            <span class="di-chip">{schema.fps} Hz</span>
            <span class="di-chip di-muted">no success/reward column</span>
          </div>

          {/* per-dim ranges — the actual span the numbers cover */}
          <div class="di-mini-k">action range · clipped to ±1 m/s</div>
          <RangeRows rows={DATA.action_ranges} span={actSpan} />
          <div class="di-mini-k di-mt">state range · per observation dim</div>
          <RangeRows rows={DATA.state_ranges} span={stateSpan} />
        </figure>
      </div>

      {/* episode selector — the one browsing control (keyboard-native segmented) */}
      <div class="di-controls">
        <span class="di-seg-label">episode</span>
        <div class="di-seg" role="group" aria-label="Choose a recorded demonstration to inspect">
          {eps.map((e, i) => (
            <button type="button" class="di-seg-btn" aria-pressed={i === epIdx} data-reached={e.reached} onClick={() => pickEpisode(i)}>
              {i + 1}
            </button>
          ))}
        </div>
        <span class="di-note">3 recorded demonstrations · scrub with ← → · {stats.n_frames} (state, action) pairs total</span>
      </div>

      {/* ============================ PANEL 3 — THE LESSON ==================== */}
      <p class="di-lesson">
        This is the whole dataset: <b>{stats.n_frames} (state, action) pairs</b> across {stats.n_episodes} demonstrations —
        no labels, no reward. Behavior cloning fits a function <b>state → action</b> to exactly these rows. The{" "}
        <b className="di-ok">{Math.round(stats.success_rate * 100)}% reached *</b> is not stored anywhere; it is
        RECONSTRUCTED from each demo's terminal frame with the env's own tolerances (pos &lt; {DATA.tolerances.pos_tol_m} m,
        yaw &lt; {DATA.tolerances.ang_tol_rad} rad). Read that same yaw backwards — atan2(cos, sin) — and it collapses to{" "}
        {Math.round(stats.success_rate_yaw_swap * 100)}%: seeing like a robot is decoding the numbers the robot saw.
        Real rows from inspect.py (seed 0, cpu); poster reads with JS off.
      </p>

      {/* non-visual path: one polite announcement per episode change */}
      <div class="bk-sr" aria-live="polite">{announce}</div>
    </div>
  );
}

// ============================================================================
// WIRE ME IN — PlateIsland.tsx (the shared dispatch; do NOT edit here):
//   import DatasetInspectToy from "./toys/DatasetInspectToy";            // with the other toy imports
//   if (demo === "pusht-inspect") return <DatasetInspectToy />;         // ch0.5 inspect a recorded dataset
// (No lazy/heavy deps: this toy is a static-JSON data panel, safe to import eagerly
//  like the other toy posters; it fully server-renders for the JS-off path.)
// ============================================================================
export default function DatasetInspectToy() {
  return <DatasetInspect />;
}
