/**
 * ch3.7 "Datasets at Scale" — the DATA-SCALE concept-toy (`demo: scale_data_coverage`).
 * A recorded-data sibling of ch3.3's engine-drift and ch1.6's eval-bands 2D toys:
 * "data is the policy, scaled" made visual. No WASM — pure SVG over numbers
 * scale_data.py itself produced.
 *
 * THREE panels, ONE control (the view toggle: source-only ↔ source + augmented):
 *   1. THE DATA-SCALE EFFECT (headline): two BC-success bars — SOURCE-ONLY vs
 *      SOURCE+AUGMENTED — with ch1.6-style whiskers (the seed 0–2 range) and the
 *      per-seed dots. Augmentation lifts the coverage-starved policy from a mean
 *      ~0.08 to ~0.21, higher on EVERY seed. The absolute numbers are small on
 *      purpose: 12 source demos is a coverage-starved regime, and the small
 *      honest gain IS the lesson (the ch1.2 thesis scaled), not a hero number.
 *   2. COVERAGE (why it helps): the PushT object-spawn annulus with the REAL
 *      start poses — 12 sparse source-demo starts, then the ~94 re-solved,
 *      success-filtered augmented starts the MimicGen-style perturb-and-re-solve
 *      tiled it with. A polar coverage grid counts it honestly: source fills
 *      12 of 36 cells, source+augmented 32 of 36. The toggle hides/shows the
 *      augmented cloud so you watch coverage — and the bar — fill together.
 *   3. CROSS-EMBODIMENT padding: PushT acts in 2 dims, ALOHA in 6 — one shared
 *      tensor padded to 6 with an action_mask marking the real dims (the ch1.7
 *      trick). A shared policy transfers STRUCTURE, never the semantics of a raw
 *      dimension; OXE/DROID are this exact picture at a million trajectories.
 *
 * Like ch3.3 this needs NO WASM: it renders REAL numbers from scale_data.py — the
 * coverage starts come from a live wrangle+augment run (seed 0, cpu), the success
 * bars from meta.yaml's reference_run (seeds 0–2, full config) — regenerated by
 * site/scripts/vizdata/ch3.7_scale_data.py into the co-located vizdata.json,
 * verified to match meta.yaml (STOP-on-drift). So it is pure SVG + design tokens:
 * theme-aware for free, and the server-rendered default (source + augmented) IS
 * the JS-off experience — only the toggle goes inert without hydration. Colour by
 * MEANING: source = --ink-mute neutral (the starved baseline), augmented =
 * --signal blue (the one variable — the added data), target = --entity-target.
 */
import "./DataScaleToy.css";
import { useMemo, useState } from "preact/hooks";
// Real numbers from scale_data.py — coverage from a seed-0 cpu wrangle+augment
// run, success from meta.yaml reference_run — see the file's `provenance` and the
// generator site/scripts/vizdata/ch3.7_scale_data.py. Committed small text, no binary.
import viz from "../../../../curriculum/phase3_advanced/ch3.7_scale_data/demo/vizdata.json";

// ---------------------------------------------------------------- typed vizdata
interface Success {
  seeds: number[]; source: number[]; augmented: number[]; delta: number[];
  source_mean: number; augmented_mean: number; scale_effect_mean: number;
  source_min: number; source_max: number; augmented_min: number; augmented_max: number;
}
interface Grid { rings: number; sectors: number; total_cells: number; source_cells: number; augmented_cells: number; }
interface Coverage {
  seed: number; spawn_r: number[]; clip_r: number[];
  source_starts: number[][]; augmented_starts: number[][];
  source_n: number; augmented_n: number; kept: number; attempts: number; yield: number; grid: Grid;
}
interface Emb { name: string; act_dim: number; frames: number; }
interface Cross {
  embodiments: Emb[]; padded_action_dim: number; mixed_frames: number;
  pusht_mask_density: number; mixed_mask_density: number; obs_dim: number;
}

const SUCC = viz.success as Success;
const COV = viz.coverage as Coverage;
const CROSS = viz.cross_embodiment as Cross;

type View = "source" | "augmented";

// ------------------------------------------------------------ number formatting
const pct = (v: number) => `${Math.round(v * 100)}%`;
const pct1 = (v: number) => `${(v * 100).toFixed(1)}%`;
const signedPct = (v: number) => `${v >= 0 ? "+" : ""}${(v * 100).toFixed(1)} pts`;

// ================================================================ SUCCESS PANEL
const SW = 300, SH = 250;
const SPAD = { l: 40, r: 14, t: 20, b: 40 };
const SPW = SW - SPAD.l - SPAD.r;
const SPH = SH - SPAD.t - SPAD.b;
const Y_MAX = 0.4; // fixed 0..0.4 so the honest small numbers are not exaggerated

interface Bar { key: View; label: string; mean: number; min: number; max: number; seeds: number[]; }
const BARS: Bar[] = [
  { key: "source", label: "source-only", mean: SUCC.source_mean, min: SUCC.source_min, max: SUCC.source_max, seeds: SUCC.source },
  { key: "augmented", label: "source + augmented", mean: SUCC.augmented_mean, min: SUCC.augmented_min, max: SUCC.augmented_max, seeds: SUCC.augmented },
];

function SuccessPanel({ view }: { view: View }) {
  const y = (v: number) => SPAD.t + (1 - Math.min(v, Y_MAX) / Y_MAX) * SPH;
  const yTicks = [0, 0.1, 0.2, 0.3, 0.4];
  const bandW = SPW / BARS.length;
  const barW = 54;

  return (
    <svg
      class="ds-svg"
      viewBox={`0 0 ${SW} ${SH}`}
      role="img"
      aria-label={
        `Bar chart of behavior-cloning rollout success. Source-only (12 demos) reaches a mean ${pct(SUCC.source_mean)}; ` +
        `source plus augmented reaches a mean ${pct(SUCC.augmented_mean)} — higher on every seed. ` +
        "Whiskers show the seed 0 to 2 range. The absolute numbers are small because 12 demos is a coverage-starved regime; " +
        "the point is the ordering."
      }
    >
      {/* y gridlines + ticks */}
      {yTicks.map((t) => (
        <g>
          <line class="ds-grid" x1={SPAD.l} y1={y(t)} x2={SW - SPAD.r} y2={y(t)} />
          <text class="ds-tick" x={SPAD.l - 6} y={y(t) + 3} text-anchor="end">{pct(t)}</text>
        </g>
      ))}
      <line class="ds-axis" x1={SPAD.l} y1={SPAD.t} x2={SPAD.l} y2={SH - SPAD.b} />
      <text class="ds-axis-title" x={SPAD.l - 32} y={SPAD.t - 8}>BC success</text>

      {BARS.map((b, i) => {
        const cx = SPAD.l + bandW * (i + 0.5);
        const x0 = cx - barW / 2;
        const active = b.key === view;
        const cls = b.key === "augmented" ? "ds-b-aug" : "ds-b-src";
        return (
          <g class={active ? "ds-bar-active" : "ds-bar-dim"}>
            {/* the mean bar */}
            <rect
              class={`ds-bar ${cls}`}
              x={x0} y={y(b.mean)} width={barW} height={Math.max(0, SH - SPAD.b - y(b.mean))} rx={2}
            />
            {/* seed-range whisker (ch1.6-style) */}
            <line class="ds-whisker" x1={cx} y1={y(b.min)} x2={cx} y2={y(b.max)} />
            <line class="ds-whisker" x1={cx - 7} y1={y(b.max)} x2={cx + 7} y2={y(b.max)} />
            <line class="ds-whisker" x1={cx - 7} y1={y(b.min)} x2={cx + 7} y2={y(b.min)} />
            {/* the three per-seed dots (jittered horizontally) */}
            {b.seeds.map((s, k) => (
              <circle class={`ds-seed ${cls}`} cx={cx + (k - 1) * 8} cy={y(s)} r={2.4} />
            ))}
            {/* value label */}
            <text class={`ds-bar-val ${active ? "ds-bar-val-on" : ""}`} x={cx} y={y(b.mean) - 8} text-anchor="middle">
              {pct1(b.mean)}
            </text>
            <text class="ds-bar-lab" x={cx} y={SH - SPAD.b + 15} text-anchor="middle">{b.label}</text>
          </g>
        );
      })}

      {/* the delta bracket between the two bars */}
      <text class="ds-delta" x={SPAD.l + SPW / 2} y={y(SUCC.augmented_mean) - 26} text-anchor="middle">
        {signedPct(SUCC.scale_effect_mean)} mean
      </text>
    </svg>
  );
}

// ================================================================ COVERAGE PANEL
const CV = 300;
const CPAD = 16;
const WORLD_HALF = 0.28; // holds the clip radius 0.26 + a margin
const cscale = (CV / 2 - CPAD) / WORLD_HALF;
const cmap = (x: number, y: number): [number, number] => [CV / 2 + x * cscale, CV / 2 - y * cscale];

function CoveragePanel({ showAug }: { showAug: boolean }) {
  const [rIn, rOut] = COV.spawn_r;
  const src = useMemo(() => COV.source_starts.map(([x, y]) => cmap(x, y)), []);
  const aug = useMemo(() => COV.augmented_starts.map(([x, y]) => cmap(x, y)), []);
  const [ox, oy] = cmap(0, 0);

  return (
    <svg
      class="ds-svg ds-cov-svg"
      viewBox={`0 0 ${CV} ${CV}`}
      role="img"
      aria-label={
        `Top-down map of the PushT object-spawn annulus. ${COV.source_n} sparse source-demo start positions fill ` +
        `${COV.grid.source_cells} of ${COV.grid.total_cells} coverage cells. ` +
        (showAug
          ? `The ${COV.augmented_n} re-solved augmented starts fill it in to ${COV.grid.augmented_cells} of ${COV.grid.total_cells} cells.`
          : "The augmented starts are hidden; toggle to show how they fill the coverage in.")
      }
    >
      {/* the spawn annulus band the demos tile */}
      <circle class="ds-annulus" cx={ox} cy={oy} r={rOut * cscale} />
      <circle class="ds-annulus-inner" cx={ox} cy={oy} r={rIn * cscale} />
      {/* target at the origin */}
      <line class="ds-target" x1={ox - 7} y1={oy} x2={ox + 7} y2={oy} />
      <line class="ds-target" x1={ox} y1={oy - 7} x2={ox} y2={oy + 7} />
      <text class="ds-target-lab" x={ox + 9} y={oy - 5}>target</text>

      {/* augmented starts (the added coverage) — signal blue, drawn under the source */}
      {showAug && aug.map(([x, y]) => <circle class="ds-dot ds-dot-aug" cx={x.toFixed(1)} cy={y.toFixed(1)} r={2.6} />)}
      {/* source starts — neutral, always on top so the sparse baseline stays legible */}
      {src.map(([x, y]) => <circle class="ds-dot ds-dot-src" cx={x.toFixed(1)} cy={y.toFixed(1)} r={3.6} />)}
    </svg>
  );
}

// ============================================================ CROSS-EMBODIMENT
function ActionCells({ used, total }: { used: number; total: number }) {
  return (
    <span class="ds-cells" aria-hidden="true">
      {Array.from({ length: total }, (_, i) => (
        <span class={`ds-cell ${i < used ? "ds-cell-on" : "ds-cell-pad"}`} />
      ))}
    </span>
  );
}

function CrossEmbodiment() {
  const pad = CROSS.padded_action_dim;
  return (
    <div class="ds-cross">
      <div class="ds-cross-h">cross-embodiment: one pile, two action spaces</div>
      <div class="ds-cross-rows">
        {CROSS.embodiments.map((e) => (
          <div class="ds-cross-row">
            <span class="ds-cross-name">{e.name}</span>
            <ActionCells used={e.act_dim} total={pad} />
            <span class="ds-cross-dims">{e.act_dim} of {pad} dims{e.act_dim < pad ? " · rest padded + masked" : ""}</span>
          </div>
        ))}
      </div>
      <p class="ds-cross-note">
        PushT acts in <b>2</b> dims, ALOHA in <b>6</b> — one shared tensor padded to <b>{pad}</b> with an
        <b> action_mask</b> marking the real dims (the ch1.7 trick). A PushT row uses just{" "}
        <b>{pct(CROSS.pusht_mask_density)}</b> of the padded width. A shared policy transfers <b>structure</b>,
        never the semantics of a raw dimension — and it normalizes <b>per embodiment</b>. OXE/DROID are this exact
        picture at a million trajectories, named here, never downloaded.
      </p>
    </div>
  );
}

// ==================================================================== THE ISLAND
function DataScaleToy() {
  const [view, setView] = useState<View>("augmented");
  const showAug = view === "augmented";
  const g = COV.grid;

  // aria-live: the qualitative comparison (+ the honest small-numbers framing), never per-frame spam.
  const announce = showAug
    ? `Source plus augmented: the ${COV.augmented_n} re-solved augmented starts fill coverage from ${g.source_cells} ` +
      `to ${g.augmented_cells} of ${g.total_cells} cells, and BC success rises from a mean ${pct(SUCC.source_mean)} to ` +
      `${pct(SUCC.augmented_mean)} — higher on every seed (delta ${signedPct(SUCC.scale_effect_mean)}). ` +
      "The numbers are small because 12 demos is a coverage-starved regime; the ordering is the point."
    : `Source-only: ${COV.source_n} demos fill just ${g.source_cells} of ${g.total_cells} coverage cells and reach ` +
      `a mean BC success of ${pct(SUCC.source_mean)}. This is the coverage-starved baseline augmentation improves on.`;

  return (
    <div class="ds">
      {/* --- the one control: the view toggle --- */}
      <div class="ds-controls">
        <span class="ds-seg-label">view</span>
        <div class="ds-seg" role="group" aria-label="Show source-only or source plus augmented data">
          <button type="button" class="ds-seg-btn" aria-pressed={view === "source"} onClick={() => setView("source")}>
            source-only
          </button>
          <button type="button" class="ds-seg-btn" aria-pressed={view === "augmented"} onClick={() => setView("augmented")}>
            + augmented
          </button>
        </div>
        <span class="ds-seg-hint">
          {showAug ? "the augmented cloud fills coverage — and the bar" : "the coverage-starved baseline: 12 sparse demos"}
        </span>
      </div>

      {/* --- the two headline panels --- */}
      <div class="ds-panels">
        <figure class="ds-panel">
          <figcaption class="ds-cap">
            <span>the data-scale effect</span>
            <b>BC success · seeds 0–2</b>
          </figcaption>
          <SuccessPanel view={view} />
          <div class="ds-readout" aria-hidden="true">
            <div class="ds-row">
              <span class="ds-lg ds-l-src"><span class="ds-lg-name">source-only</span></span>
              <span class="ds-v">{pct1(SUCC.source_mean)}</span>
            </div>
            <div class="ds-row">
              <span class="ds-lg ds-l-aug"><span class="ds-lg-name">source + augmented</span></span>
              <span class="ds-v ds-good">{pct1(SUCC.augmented_mean)}</span>
            </div>
            <div class="ds-row ds-row-delta">
              <span class="ds-lg-name">scale effect (mean)</span>
              <span class="ds-v ds-good">{signedPct(SUCC.scale_effect_mean)}</span>
            </div>
          </div>
        </figure>

        <figure class="ds-panel">
          <figcaption class="ds-cap">
            <span>coverage · object spawn annulus</span>
            <b>{showAug ? `${g.augmented_cells}/${g.total_cells} cells` : `${g.source_cells}/${g.total_cells} cells`}</b>
          </figcaption>
          <CoveragePanel showAug={showAug} />
          <div class="ds-readout" aria-hidden="true">
            <div class="ds-row">
              <span class="ds-lg ds-l-src"><span class="ds-lg-name">source starts</span></span>
              <span class="ds-v">{COV.source_n} · {g.source_cells}/{g.total_cells} cells</span>
            </div>
            <div class="ds-row" data-off={!showAug}>
              <span class="ds-lg ds-l-aug"><span class="ds-lg-name">augmented starts</span></span>
              <span class="ds-v ds-good">+{COV.augmented_n} · {g.augmented_cells}/{g.total_cells} cells</span>
            </div>
            <div class="ds-row ds-row-delta">
              <span class="ds-lg-name">augmentation yield</span>
              <span class="ds-v">{pct(COV.yield)} · kept {COV.kept}/{COV.attempts}</span>
            </div>
          </div>
        </figure>
      </div>

      {/* --- panel 3: the cross-embodiment padding note --- */}
      <CrossEmbodiment />

      {/* non-visual path to the same aha — the qualitative comparison only */}
      <div class="bk-sr" aria-live="polite">{announce}</div>

      <p class="ds-note">
        <b>Data is the policy, scaled.</b> The policy did not change between the two bars — only the data did.
        The absolute success is small on purpose: 12 source demos is a <b>coverage-starved</b> regime, so the
        DATA effect is visible and honest, not a hero number. Every augmented demo is a real scripted-expert
        solution of a real perturbed start (success-filtered, kept {COV.kept}/{COV.attempts}) — no fabricated actions.
        Coverage from a seed-0 cpu run of scale_data.py; success from meta.yaml (seeds 0–2). Poster reads with JS off.
      </p>
    </div>
  );
}

export default function DataScale() {
  return <DataScaleToy />;
}
