/**
 * ch3.4 "Build a Physics Engine II: Joints & Constraints" — the CONSTRAINT +
 * CHAOTIC-YET-DETERMINISTIC double-pendulum concept-toy (`demo: constraint_drift`).
 * A sibling of ch2.3's mjx toy: it renders REAL, pre-computed trajectories — never
 * an invented swing — as pure SVG + design tokens, so it is theme-aware for free and
 * the server-rendered final frame IS the JS-off experience.
 *
 * HONESTY — THIS IS RECORDED DATA, replayed, not a live solver. The dynamics are
 * ~350 lines of pure numpy (constraints.py); we could solve them in-browser, but the
 * toy REPLAYS trajectories constraints.py measured at seed 0/1 on CPU — regenerated by
 * site/scripts/vizdata/ch3.4_constraints.py into the co-located vizdata.json, verified
 * against meta.yaml's reference_run (none max|len err| 0.384, baumgarte 0.0235,
 * seed0-vs-seed1 tip divergence 1.117, seed-0 rerun bitwise identical). No fabrication.
 *
 * THREE panels tell the whole chapter:
 *   1. THE DOUBLE PENDULUM — the recorded chaotic swing (seed 0, Baumgarte-held), its
 *      traced tip path always visible; a scrubber replays it (auto-plays unless the
 *      visitor prefers reduced motion, in which case it rests on the full-swing frame).
 *   2. CHAOTIC YET DETERMINISTIC (the headline) — two pendulums from ALMOST-identical
 *      initial angles (delta ~0.0125 rad) overlaid: they track for a beat, then diverge
 *      to a tip gap of ~1.12 over 20 s (chaos). YET each seed replays BITWISE (a byte-
 *      identical trajectory hash) — chaos is not nondeterminism. The divergence curve
 *      + the determinism badge carry the lesson without animation (reduced-motion safe).
 *   3. CONSTRAINT DRIFT — worst link-length error vs time on the SAME pendulum: the
 *      naive solve (red) stretches without bound; Baumgarte stabilization (green) holds
 *      it near zero (16x smaller). The constraint-solve honesty, made a picture.
 *
 * Colour discipline (theme-aware tokens, no hardcoded surfaces):
 *   --signal blue      → pendulum A (seed 0) + the live handles (scrubber/focus)
 *   --entity-block     → pendulum B (seed 1), the near-neighbour
 *   --alert red        → the NAIVE (unstabilized) drift curve — the links coming apart
 *   --entity-target    → the BAUMGARTE-stabilized drift curve — the links holding
 *   neutral ink        → axes, grids, the traced path, the divergence gap
 */
import "./double-pendulum.css";
import { useEffect, useRef, useState } from "preact/hooks";
// Real recorded trajectories from constraints.py, seed 0/1, cpu — see the file's
// `provenance` and the generator site/scripts/vizdata/ch3.4_constraints.py. Small text, no binary.
import viz from "../../../../curriculum/phase3_advanced/ch3.4_constraints/demo/vizdata.json";

// ---------------------------------------------------------------- typed vizdata
interface Run {
  seed: number;
  tilt_rad: number;
  frames: number[][]; // [bob0_x, bob0_y, bob1_x, bob1_y] per frame
  path: number[][];   // traced tip (bob1) path, [x, y]
  tip_final: number[];
}
const RUN_A = viz.runs.A as Run;
const RUN_B = viz.runs.B as Run;
const B = viz.bounds;
const SIM_S: number = viz.sim_seconds;
const N_FRAMES: number = RUN_A.frames.length;
const DIV = viz.chaos.divergence;
const DET = viz.chaos.determinism;
const INIT_DELTA: number = viz.chaos.init_delta_rad;
const DRIFT = viz.drift;

// -------------------------------------------------------------- arena geometry
// world (x, y) -> svg px, y up, shared by both pendulum panels so they read at one scale.
const PAD = 10;
const VW = 360;
const WW = B.xmax - B.xmin;
const WH = B.ymax - B.ymin;
const SCALE = (VW - 2 * PAD) / WW;
const VH = Math.round(WH * SCALE + 2 * PAD);
const ax = (x: number) => PAD + (x - B.xmin) * SCALE;
const ay = (y: number) => VH - PAD - (y - B.ymin) * SCALE; // world +y is up
const PIVX = ax(0);
const PIVY = ay(0);

/** One pendulum at frame f: pivot -> bob0 -> bob1, with two links and three joints. */
function Pendulum({ run, f, cls }: { run: Run; f: number; cls: string }) {
  const fr = run.frames[Math.max(0, Math.min(N_FRAMES - 1, f))];
  const b0x = ax(fr[0]), b0y = ay(fr[1]);
  const b1x = ax(fr[2]), b1y = ay(fr[3]);
  return (
    <g class={cls}>
      <line class="dp-link" x1={PIVX} y1={PIVY} x2={b0x.toFixed(1)} y2={b0y.toFixed(1)} />
      <line class="dp-link" x1={b0x.toFixed(1)} y1={b0y.toFixed(1)} x2={b1x.toFixed(1)} y2={b1y.toFixed(1)} />
      <circle class="dp-bob dp-bob-mid" cx={b0x.toFixed(1)} cy={b0y.toFixed(1)} r={5} />
      <circle class="dp-bob dp-bob-tip" cx={b1x.toFixed(1)} cy={b1y.toFixed(1)} r={6} />
    </g>
  );
}

/** The faint fixed anchor every chain hangs from. */
function Pivot() {
  return (
    <g class="dp-pivot">
      <line class="dp-ceiling" x1={PIVX - 26} y1={PIVY} x2={PIVX + 26} y2={PIVY} />
      <circle cx={PIVX} cy={PIVY} r={3.4} />
    </g>
  );
}

function pathD(pts: number[][]): string {
  return pts.map(([x, y], i) => `${i ? "L" : "M"}${ax(x).toFixed(1)} ${ay(y).toFixed(1)}`).join(" ");
}

// -------------------------------------------------- divergence chart geometry
const DV = { w: 360, h: 150 };
const DVP = { l: 34, r: 14, t: 14, b: 26 };
const DVW = DV.w - DVP.l - DVP.r;
const DVH = DV.h - DVP.t - DVP.b;
const DIST_MAX = Math.max(...(DIV.dist as number[])) * 1.06;
const dvx = (t: number) => DVP.l + (t / SIM_S) * DVW;
const dvy = (d: number) => DVP.t + (1 - Math.min(d, DIST_MAX) / DIST_MAX) * DVH;

/** per-frame tip gap (from the two synced frame streams) — keeps the head on the curve */
function tipGapAtFrame(f: number): number {
  const a = RUN_A.frames[f], b = RUN_B.frames[f];
  return Math.hypot(a[2] - b[2], a[3] - b[3]);
}
const frameTime = (f: number) => (N_FRAMES === 1 ? 0 : (f / (N_FRAMES - 1)) * SIM_S);

// -------------------------------------------------------- drift chart geometry
const DR = { w: 360, h: 168 };
const DRP = { l: 44, r: 14, t: 16, b: 30 };
const DRW = DR.w - DRP.l - DRP.r;
const DRH = DR.h - DRP.t - DRP.b;
const DR_MAX = Math.max(DRIFT.none_max, 0.05) * 1.06; // linear y: none climbs, baumgarte hugs 0
const drx = (t: number) => DRP.l + (t / SIM_S) * DRW;
const dry = (v: number) => DRP.t + (1 - Math.min(v, DR_MAX) / DR_MAX) * DRH;
function driftD(series: number[]): string {
  const T = DRIFT.t as number[];
  return series.map((v, i) => `${i ? "L" : "M"}${drx(T[i]).toFixed(1)} ${dry(v).toFixed(1)}`).join(" ");
}

// ================================================================ the island
function Toy() {
  // SSR default = the FINAL frame: JS-off shows the full swing, the two pendulums
  // far apart, and every curve complete. On hydration (with motion) we rewind + play.
  const [f, setF] = useState(N_FRAMES - 1);
  const [playing, setPlaying] = useState(false);
  const timer = useRef<number | null>(null);

  useEffect(() => {
    const reduce = typeof matchMedia === "function" && matchMedia("(prefers-reduced-motion: reduce)").matches;
    if (reduce) return; // stay on the legible final frame — no animation
    setF(0);
    setPlaying(true);
    return () => { if (timer.current != null) clearInterval(timer.current); };
  }, []);

  useEffect(() => {
    if (!playing) return;
    const id = window.setInterval(() => {
      setF((i) => {
        if (i >= N_FRAMES - 1) { setPlaying(false); return i; }
        return i + 1;
      });
    }, 55);
    timer.current = id;
    return () => clearInterval(id);
  }, [playing]);

  const gap = tipGapAtFrame(f);
  const t = frameTime(f);
  const replay = () => { setF(0); setPlaying(true); };
  const onScrub = (e: Event) => {
    setPlaying(false);
    setF(parseInt((e.currentTarget as HTMLInputElement).value, 10));
  };

  // aria-live: coarse chaos phases (stable strings per bucket, no per-frame numbers)
  // so a screen reader hears the story on phase transitions, not on every frame.
  const chaosSay =
    f >= N_FRAMES - 1
      ? `Replay complete. From an initial angle difference of ${INIT_DELTA.toFixed(4)} radians, the two tips are now ${DIV.final} apart — chaotic divergence. Yet each seed replays byte-for-byte identically: chaos is not randomness.`
      : gap < 0.05
        ? "The two pendulums start almost identical and swing together."
        : gap < 0.5
          ? "The pendulums are pulling apart — the tiny initial difference is amplifying."
          : `Fully diverged, headed for a tip gap of ${DIV.final} — a tiny initial nudge, an enormous difference.`;

  const dvPolyline = (DIV.t as number[]).map((tt, i) => `${dvx(tt).toFixed(1)},${dvy(DIV.dist[i]).toFixed(1)}`).join(" ");

  return (
    <div class="dp">
      {/* honesty banner — recorded, not a live solve */}
      <p class="dp-recorded">
        recorded trajectories · seed 0 &amp; 1 · cpu numpy — <b>replayed, not live</b>: real runs from constraints.py, matched to meta.yaml
      </p>

      {/* ---- Panel 1: the double pendulum (the chaotic swing) ---------------- */}
      <figure class="dp-panel">
        <figcaption class="dp-cap">the double pendulum · a chain of two distance constraints (seed 0)</figcaption>
        <svg
          class="dp-arena"
          viewBox={`0 0 ${VW} ${VH}`}
          role="img"
          aria-label={
            "A double pendulum hanging from a fixed pivot: two rigid links joined at a middle bob, ending in a tip bob. " +
            "Its faint traced path shows a tangled, chaotic swing that never repeats. The links stay exactly their rest length — " +
            "the constraint solver holds the chain together."
          }
        >
          <path class="dp-trace" d={pathD(RUN_A.path)} />
          <Pivot />
          <Pendulum run={RUN_A} f={f} cls="dp-pen-a" />
        </svg>
      </figure>

      {/* ---- Panel 2: chaotic YET deterministic (the headline) -------------- */}
      <figure class="dp-panel dp-panel-chaos">
        <figcaption class="dp-cap">chaotic, yet deterministic · two pendulums, nearly identical starts</figcaption>
        <div class="dp-chaos-body">
          <div class="dp-overlay-wrap">
            <svg
              class="dp-arena"
              viewBox={`0 0 ${VW} ${VH}`}
              role="img"
              aria-label={
                `Two double pendulums overlaid, started from almost-identical angles ${INIT_DELTA.toFixed(4)} radians apart. ` +
                `Pendulum A (seed 0, blue) and pendulum B (seed 1, magenta) swing together at first, then diverge completely, ` +
                `their tips ending ${DIV.final} apart.`
              }
            >
              <path class="dp-trace dp-trace-b" d={pathD(RUN_B.path)} />
              <path class="dp-trace" d={pathD(RUN_A.path)} />
              <Pivot />
              <Pendulum run={RUN_B} f={f} cls="dp-pen-b" />
              <Pendulum run={RUN_A} f={f} cls="dp-pen-a" />
            </svg>
            <div class="dp-legend" aria-hidden="true">
              <span class="dp-lg dp-lg-a">seed 0</span>
              <span class="dp-lg dp-lg-b">seed 1</span>
              <span class="dp-lg-delta">Δθ₀ = {INIT_DELTA.toFixed(4)} rad</span>
            </div>
          </div>

          <div class="dp-chaos-right">
            {/* the divergence curve — chaos made a number */}
            <svg
              class="dp-div-svg"
              viewBox={`0 0 ${DV.w} ${DV.h}`}
              role="img"
              aria-label={
                `Line chart: distance between the two tips versus time. It stays near zero for the first few seconds, ` +
                `then grows fast, reaching ${DIV.final} after ${SIM_S} seconds — exponential sensitivity to the tiny initial difference.`
              }
            >
              <line class="dp-ax" x1={DVP.l} y1={dvy(0)} x2={DV.w - DVP.r} y2={dvy(0)} />
              <line class="dp-ax" x1={DVP.l} y1={DVP.t} x2={DVP.l} y2={dvy(0)} />
              <text class="dp-ylab" x={DVP.l - 5} y={dvy(DIST_MAX) + 8} text-anchor="end">{DIST_MAX.toFixed(1)}</text>
              <text class="dp-ylab" x={DVP.l - 5} y={dvy(0) + 3} text-anchor="end">0</text>
              <text class="dp-ytitle" transform={`translate(11 ${DVP.t + DVH / 2}) rotate(-90)`} text-anchor="middle">tip gap</text>
              <polyline class="dp-div-line" points={dvPolyline} />
              {/* the replay head — sits on the curve at the current frame */}
              <line class="dp-div-drop" x1={dvx(t)} y1={dvy(gap)} x2={dvx(t)} y2={dvy(0)} />
              <circle class="dp-div-head" cx={dvx(t)} cy={dvy(gap)} r={3.6} />
              <text class="dp-div-val" x={dvx(t)} y={dvy(gap) - 7} text-anchor="middle">{gap.toFixed(2)}</text>
              <text class="dp-xtitle" x={DVP.l + DVW / 2} y={DV.h - 4} text-anchor="middle">time (s)</text>
            </svg>

            {/* the determinism badge — the OTHER half of the headline */}
            <div class="dp-det" aria-hidden="true">
              <span class="dp-det-title">same seed → bitwise identical</span>
              <span class="dp-det-body">
                seed 0 replayed twice: byte-for-byte the same trajectory
                <code class="dp-det-hash">sha256 {DET.traj_sha256_12}</code>
              </span>
              <span class="dp-det-punch">chaos ≠ nondeterminism</span>
            </div>
          </div>
        </div>

        {/* the one control: replay / scrub the divergence */}
        <div class="dp-scrub-row">
          <button type="button" class="dp-btn dp-btn--primary" onClick={replay}>
            {playing ? "playing…" : "▶ replay the divergence"}
          </button>
          <input
            class="dp-scrub"
            type="range"
            min={0}
            max={N_FRAMES - 1}
            step={1}
            value={f}
            onInput={onScrub}
            aria-label="Scrub the recorded double-pendulum replay. Drag to step through time and watch the two nearly-identical pendulums diverge."
            aria-valuetext={`${t.toFixed(1)} of ${SIM_S} seconds, tip gap ${gap.toFixed(2)}`}
          />
          <span class="dp-scrub-val">{t.toFixed(1)}s</span>
        </div>
      </figure>

      {/* ---- Panel 3: constraint drift — naive vs Baumgarte ----------------- */}
      <figure class="dp-panel">
        <figcaption class="dp-cap">constraint drift · worst link-length error vs time (same pendulum)</figcaption>
        <svg
          class="dp-drift-svg"
          viewBox={`0 0 ${DR.w} ${DR.h}`}
          role="img"
          aria-label={
            `Line chart: the worst link-length error over ${SIM_S} seconds, for two solves of the same double pendulum. ` +
            `Without stabilization (red) the error climbs without bound to ${DRIFT.none_max} — the links stretch, the pendulum comes apart in the arithmetic. ` +
            `With Baumgarte stabilization (green) it stays near zero, peaking at only ${DRIFT.baumgarte_max}, about ${DRIFT.drift_ratio} times smaller.`
          }
        >
          {/* axes + y ticks */}
          <line class="dp-ax" x1={DRP.l} y1={dry(0)} x2={DR.w - DRP.r} y2={dry(0)} />
          <line class="dp-ax" x1={DRP.l} y1={DRP.t} x2={DRP.l} y2={dry(0)} />
          {[0, DRIFT.baumgarte_max, DRIFT.none_max].map((v) => (
            <g>
              <line class="dp-grid" x1={DRP.l} y1={dry(v)} x2={DR.w - DRP.r} y2={dry(v)} />
              <text class="dp-ylab" x={DRP.l - 5} y={dry(v) + 3} text-anchor="end">{v.toFixed(2)}</text>
            </g>
          ))}
          <text class="dp-ytitle" transform={`translate(12 ${DRP.t + DRH / 2}) rotate(-90)`} text-anchor="middle">|link err| (of L=1)</text>

          {/* the two solves */}
          <path class="dp-drift-none" d={driftD(DRIFT.none as number[])} />
          <path class="dp-drift-baum" d={driftD(DRIFT.baumgarte as number[])} />

          {/* end-of-run labels */}
          <text class="dp-drift-lab dp-drift-lab-none" x={DR.w - DRP.r} y={dry(DRIFT.none_max) + 4} text-anchor="end">
            naive · {DRIFT.none_max.toFixed(2)}
          </text>
          <text class="dp-drift-lab dp-drift-lab-baum" x={DR.w - DRP.r} y={dry(0) - 6} text-anchor="end">
            Baumgarte · {DRIFT.baumgarte_max.toFixed(3)}
          </text>
          <text class="dp-xtitle" x={DRP.l + DRW / 2} y={DR.h - 4} text-anchor="middle">time (s)</text>
        </svg>
        <p class="dp-drift-note">
          A constraint force is <b>solved for</b>, not written down — and the naive acceleration-level solve lets the
          links <b>drift</b>. Baumgarte feeds the violation back and holds it (<b>{DRIFT.drift_ratio}× smaller</b>) — a
          hand-tuned gain, which is exactly why MuJoCo's constraints are soft and stabilized instead.
        </p>
      </figure>

      {/* non-visual path to the headline aha (chaos + determinism) */}
      <div class="bk-sr" aria-live="polite">{chaosSay}</div>
    </div>
  );
}

export default function DoublePendulumToy() {
  return <Toy />;
}
