/**
 * ch3.3 "Build a Physics Engine I: Unconstrained Dynamics" — the INTEGRATOR
 * ENERGY-DRIFT concept-toy (`demo: engine_energy_drift`). A recorded-data sibling
 * of ch1.5's flow-ring and ch1.6's eval-bands 2D toys: the integrator honesty
 * story, made visual. No WASM — pure SVG over curves engine.py itself produced.
 *
 * THREE panels, two controls:
 *   1. ENERGY DRIFT vs sim time, on a symmetric-log axis so all three curves read
 *      at once: explicit EULER climbs and never returns (energy injected every
 *      step); SEMI-IMPLICIT wobbles inside a bounded band around the true energy;
 *      RK4 sits flat on the baseline (drift ~1e-11). The dt slider shows Euler
 *      worsening as the step grows while the symplectic band and RK4 hold.
 *   2. PHASE-SPACE portrait: EULER SPIRALS OUTWARD (the orbit/loop grows as energy
 *      is injected), SEMI-IMPLICIT traces a bounded closed-ish loop, RK4 a clean
 *      ellipse. A recorded animated comet walks each trace (reduced-motion safe:
 *      the full static paths render regardless; only the moving dots are gated).
 *   3. The honest FREEFALL counter-example: selecting `freefall` replaces the
 *      portrait with the caveat — energy drifts under BOTH Euler (+9.3%) and
 *      semi-implicit (-9.3%), because the motion never returns. The symplectic
 *      advantage needs a bounded, oscillatory system. The toy teaches the caveat,
 *      not a fairy tale.
 *
 * Like ch1.5 this needs NO WASM: it renders REAL, pre-computed curves from
 * engine.py (seed 0, cpu, pure numpy) — regenerated by
 * site/scripts/vizdata/ch3.3_engine.py into the co-located vizdata.json, verified
 * to match meta.yaml's reference_run (orbit euler +22.1%, semi bounded ~3e-4, rk4
 * ~5e-11; freefall +/-9.3% both). So it is pure SVG + design tokens: theme-aware
 * for free, and the server-rendered default (orbit, dt 0.01) IS the JS-off
 * experience — only the selector + slider go inert without hydration. Colour by
 * MEANING: euler = --alert red (runs away), semi = --entity-target green (bounded
 * hero), rk4 = --signal blue (most accurate) — mirroring engine.py's COLORS.
 */
import "./EngineDriftToy.css";
import { useEffect, useMemo, useRef, useState } from "preact/hooks";
// Real curves from engine.py, seed 0, cpu — see the file's `provenance` and the
// generator site/scripts/vizdata/ch3.3_engine.py. Committed small text, no binary.
import viz from "../../../../curriculum/phase3_advanced/ch3.3_engine/demo/vizdata.json";

// ---------------------------------------------------------------- typed vizdata
type Integ = "euler" | "semi_implicit" | "rk4";
interface Drift { rel_final: number; rel_max: number; }
interface EnergyDt {
  t: number[];
  drift: Record<Integ, Drift>;
  euler: number[]; semi_implicit: number[]; rk4: number[];
}
interface Phase {
  kind: string; xlabel: string; ylabel: string; domain: number;
  traces: Record<Integ, number[][]>;
}
interface SysEntry { e0: number; energy: Record<string, EnergyDt>; phase: Phase | null; }

const SYSTEMS = viz.systems as string[];
const DTS = viz.dts as number[];
const INTEG = viz.integrators as Integ[];
const DATA = viz.data as Record<string, SysEntry>;
const SIM_TIME = viz.sim_time as number;
const DEFAULT_DT_IDX = Math.max(0, DTS.indexOf(viz.default_dt as number));

const CLS: Record<Integ, string> = { euler: "ed-euler", semi_implicit: "ed-semi", rk4: "ed-rk4" };
const dtKey = (dt: number) => `${dt}`;

// ------------------------------------------------------------ number formatting
function fmtPct(v: number): string {
  const p = v * 100;
  const s = p >= 0 ? "+" : "";
  const a = Math.abs(p);
  if (a >= 0.1) return `${s}${p.toFixed(1)}%`;
  if (a >= 0.001) return `${s}${p.toFixed(3)}%`;
  return `${s}${p.toExponential(1)}%`;
}
function fmtSci(v: number): string {
  if (v === 0) return "0";
  return v.toExponential(0);
}

// -------------------------------------------------------- symmetric-log y-axis
// Energy drift spans ~11 decades (Euler ~1e-1, semi ~1e-4, RK4 ~1e-11), and
// freefall's semi-implicit goes NEGATIVE — so a linear axis would hide the whole
// story under Euler's runaway. A symmetric-log axis shows all three at once:
// Euler climbing, semi in a bounded band, RK4 flat on the zero baseline.
const LIN = 1e-5; // linear-region half-width; |drift| below this reads as ~flat
function symlog(v: number): number {
  const a = Math.abs(v);
  if (a <= LIN) return (v / LIN); // linear near zero: RK4 lands here (flat)
  return Math.sign(v) * (1 + Math.log10(a / LIN));
}
// magnitude label at an integer symlog level (|level| >= 1): |drift| = 10^(level-6)
const levelExp = (level: number) => Math.abs(level) - 6;

// ================================================================ ENERGY PANEL
const EW = 470, EH = 250;
const EPAD = { l: 48, r: 14, t: 14, b: 30 };
const EPW = EW - EPAD.l - EPAD.r;
const EPH = EH - EPAD.t - EPAD.b;

function EnergyPanel({ system, dt }: { system: string; dt: number }) {
  const entry = DATA[system];
  const cur = entry.energy[dtKey(dt)];

  // Fix the symlog bounds per SYSTEM (max over all dt stops) so the axis stays
  // put while the dt slider moves — you watch Euler climb toward a fixed ceiling.
  const bounds = useMemo(() => {
    let lo = 0, hi = 0;
    for (const k of Object.keys(entry.energy)) {
      const e = entry.energy[k];
      for (const name of INTEG) {
        for (const v of e[name]) { if (v < lo) lo = v; if (v > hi) hi = v; }
      }
    }
    const sTop = symlog(hi) + 0.6;
    const sBot = Math.min(0, symlog(lo)) - 0.6;
    return { sTop, sBot };
  }, [system]);

  const { sTop, sBot } = bounds;
  const px = (t: number) => EPAD.l + (t / SIM_TIME) * EPW;
  const py = (rel: number) => EPAD.t + ((sTop - symlog(rel)) / (sTop - sBot)) * EPH;
  const yBaseline = py(0);

  const line = (name: Integ) =>
    cur[name].map((v, i) => `${px(cur.t[i]).toFixed(1)},${py(v).toFixed(1)}`).join(" ");

  // decade gridlines at every integer symlog level inside the range
  const levels: number[] = [];
  for (let n = Math.ceil(sBot); n <= Math.floor(sTop); n++) levels.push(n);
  const xTicks = [0, 5, 10, 15, 20].filter((t) => t <= SIM_TIME);

  return (
    <svg
      class="ed-svg"
      viewBox={`0 0 ${EW} ${EH}`}
      role="img"
      aria-label={
        `Energy-drift chart, relative energy error versus simulation time (0 to ${SIM_TIME} seconds), ` +
        `symmetric-log y-axis, for the ${system} system at timestep ${dt} seconds. ` +
        "The red explicit-Euler curve climbs and never returns; the green semi-implicit curve wobbles inside a " +
        "bounded band near zero; the blue RK4 curve sits flat on the zero baseline."
      }
    >
      {/* decade gridlines */}
      {levels.map((n) => {
        const y = EPAD.t + ((sTop - n) / (sTop - sBot)) * EPH;
        if (n === 0) return null;
        const exp = levelExp(n);
        return (
          <g>
            <line class="ed-grid" x1={EPAD.l} y1={y} x2={EW - EPAD.r} y2={y} />
            <text class="ed-tick" x={EPAD.l - 5} y={y + 3} text-anchor="end">
              {n < 0 ? "−" : ""}1e{exp}
            </text>
          </g>
        );
      })}
      {/* the conserved-energy baseline (symlog 0) — emphasised */}
      <line class="ed-baseline" x1={EPAD.l} y1={yBaseline} x2={EW - EPAD.r} y2={yBaseline} />
      <text class="ed-baseline-lab" x={EW - EPAD.r} y={yBaseline - 4} text-anchor="end">energy conserved</text>

      {/* x axis + time ticks */}
      <line class="ed-axis" x1={EPAD.l} y1={EH - EPAD.b} x2={EW - EPAD.r} y2={EH - EPAD.b} />
      {xTicks.map((t) => (
        <text class="ed-tick" x={px(t)} y={EH - EPAD.b + 13} text-anchor="middle">{t}s</text>
      ))}
      <text class="ed-axis-title" x={EPAD.l} y={EH - 2}>sim time →</text>
      <text class="ed-axis-title" x={EPAD.l - 44} y={EPAD.t + 4}>|ΔE/E₀|</text>

      {/* the three integrator curves — RK4 first (baseline), Euler last (on top) */}
      <polyline class={`ed-line ${CLS.rk4}`} points={line("rk4")} />
      <polyline class={`ed-line ${CLS.semi_implicit}`} points={line("semi_implicit")} />
      <polyline class={`ed-line ${CLS.euler}`} points={line("euler")} />
    </svg>
  );
}

// ================================================================= PHASE PANEL
const PV = 320;
const PPAD = 20;

function PhasePanel({ system }: { system: string }) {
  const phase = DATA[system].phase;

  // pixel-space traces (recomputed only on system change); refs drive the comet
  const eulerRef = useRef<SVGCircleElement>(null);
  const semiRef = useRef<SVGCircleElement>(null);
  const rk4Ref = useRef<SVGCircleElement>(null);
  const cometRefs: Record<Integ, typeof eulerRef> = {
    euler: eulerRef, semi_implicit: semiRef, rk4: rk4Ref,
  };

  const pixels = useMemo(() => {
    if (!phase) return null;
    const scale = (PV / 2 - PPAD) / phase.domain;
    const map = (x: number, y: number): [number, number] => [PV / 2 + x * scale, PV / 2 - y * scale];
    const out: Record<Integ, [number, number][]> = { euler: [], semi_implicit: [], rk4: [] };
    for (const name of INTEG) out[name] = phase.traces[name].map(([x, y]) => map(x, y));
    return out;
  }, [system]);

  // recorded comet — a dot walking each trace. Full static paths render always;
  // the comet is JS + rAF and is skipped entirely under prefers-reduced-motion.
  useEffect(() => {
    if (!pixels) return;
    const reduce = typeof window !== "undefined" && window.matchMedia
      && window.matchMedia("(prefers-reduced-motion: reduce)").matches;
    if (reduce) return;
    const n = pixels.euler.length;
    let raf = 0, i = 0, last = performance.now();
    const tick = (now: number) => {
      if (now - last >= 33) { // ~30 steps/s along the recorded trace
        i = (i + 1) % n;
        last = now;
        for (const name of INTEG) {
          const el = cometRefs[name].current;
          if (el) { const [cx, cy] = pixels[name][i]; el.setAttribute("cx", `${cx}`); el.setAttribute("cy", `${cy}`); }
        }
      }
      raf = requestAnimationFrame(tick);
    };
    raf = requestAnimationFrame(tick);
    return () => cancelAnimationFrame(raf);
  }, [system]);

  if (!phase || !pixels) return null;

  const path = (name: Integ) => pixels[name].map(([x, y], i) => `${i ? "L" : "M"}${x.toFixed(1)} ${y.toFixed(1)}`).join(" ");
  const [sx0, sy0] = pixels.rk4[0];

  return (
    <svg
      class="ed-svg ed-phase-svg"
      viewBox={`0 0 ${PV} ${PV}`}
      role="img"
      aria-label={
        `Phase-space portrait for the ${system} system: ${phase.xlabel} on the horizontal axis, ${phase.ylabel} on the vertical. ` +
        "The red explicit-Euler trace spirals outward as energy is injected; the green semi-implicit trace stays a bounded closed loop; " +
        "the blue RK4 trace is a clean closed ellipse."
      }
    >
      {/* orientation crosshair through the origin */}
      <line class="ed-phase-guide" x1={PPAD} y1={PV / 2} x2={PV - PPAD} y2={PV / 2} />
      <line class="ed-phase-guide" x1={PV / 2} y1={PPAD} x2={PV / 2} y2={PV - PPAD} />
      <text class="ed-phase-axlab" x={PV - PPAD} y={PV / 2 - 5} text-anchor="end">{phase.xlabel} →</text>
      <text class="ed-phase-axlab" x={PV / 2 + 5} y={PPAD + 4}>{phase.ylabel} ↑</text>

      {/* the three recorded traces (RK4 under, Euler on top) */}
      <path class={`ed-phase-line ${CLS.rk4}`} d={path("rk4")} />
      <path class={`ed-phase-line ${CLS.semi_implicit}`} d={path("semi_implicit")} />
      <path class={`ed-phase-line ${CLS.euler}`} d={path("euler")} />

      {/* shared launch point + the walking comets (motion-safe: static path stands alone) */}
      <circle class="ed-phase-start" cx={sx0.toFixed(1)} cy={sy0.toFixed(1)} r={2.6} />
      {INTEG.map((name) => (
        <circle ref={cometRefs[name]} class={`ed-comet ${CLS[name]}`}
          cx={pixels[name][0][0].toFixed(1)} cy={pixels[name][0][1].toFixed(1)} r={3.4} />
      ))}
    </svg>
  );
}

// ================================================================ FREEFALL CARD
function FreefallCaveat({ dt }: { dt: number }) {
  const d = DATA.freefall.energy[dtKey(dt)].drift;
  return (
    <div class="ed-caveat">
      <div class="ed-caveat-h">the honest counter-example</div>
      <p class="ed-caveat-p">
        Freefall never <b>returns</b> — there is no closed orbit to bound. So energy drifts under{" "}
        <b class="ed-plus">both</b> integrators: explicit Euler <b class="ed-plus">{fmtPct(d.euler.rel_final)}</b>{" "}
        and semi-implicit <b class="ed-minus">{fmtPct(d.semi_implicit.rel_final)}</b>, in opposite directions.
      </p>
      <p class="ed-caveat-p">
        The symplectic advantage needs a <b>bounded, oscillatory</b> system — that is exactly why the tidy
        story lives on the orbit and the spring, and breaks here on purpose.
      </p>
    </div>
  );
}

// ==================================================================== THE ISLAND
function EngineDriftToy() {
  const [system, setSystem] = useState<string>(viz.default_system as string);
  const [dtIdx, setDtIdx] = useState<number>(DEFAULT_DT_IDX);
  const dt = DTS[dtIdx];

  const cur = DATA[system].energy[dtKey(dt)];
  const d = cur.drift;
  const isFreefall = system === "freefall";

  const onSlide = (e: Event) => setDtIdx(parseInt((e.currentTarget as HTMLInputElement).value, 10));

  // aria-live: the qualitative ordering (+ the freefall caveat), never per-frame spam.
  const announce = isFreefall
    ? `Freefall at timestep ${dt} seconds: energy drifts under both integrators — explicit Euler ${fmtPct(d.euler.rel_final)}, ` +
      `semi-implicit ${fmtPct(d.semi_implicit.rel_final)}, in opposite directions. The symplectic advantage needs a bounded system.`
    : `${system} at timestep ${dt} seconds: explicit Euler drifts to ${fmtPct(d.euler.rel_final)} and its orbit spirals outward; ` +
      `semi-implicit stays inside a bounded band of ±${fmtPct(d.semi_implicit.rel_max).replace("+", "")}; ` +
      `RK4 is essentially flat, drift ${fmtSci(d.rk4.rel_max)}.`;

  // per-integrator readout value: Euler runs away (rel_final); semi is a bounded
  // band on orbit/spring but one-signed on freefall (rel_final); RK4 ~flat.
  const semiVal = isFreefall ? fmtPct(d.semi_implicit.rel_final) : `±${fmtPct(d.semi_implicit.rel_max).replace("+", "")}`;

  return (
    <div class="ed">
      {/* --- controls: the system selector + the dt slider --- */}
      <div class="ed-controls">
        <div class="ed-seg-row">
          <span class="ed-seg-label">system</span>
          <div class="ed-seg" role="group" aria-label="Choose the conservative test system">
            {SYSTEMS.map((s) => (
              <button
                type="button"
                class="ed-seg-btn"
                aria-pressed={system === s}
                onClick={() => setSystem(s)}
              >
                {s}
              </button>
            ))}
          </div>
          <span class="ed-seg-label">
            {isFreefall ? "the break-it: watch the advantage vanish" : "bounded → the symplectic advantage shows"}
          </span>
        </div>
        <div class="ed-slider-row">
          <label class="ed-slider-label" for="ed-dt">timestep <b>dt</b></label>
          <input
            id="ed-dt"
            class="ed-slider"
            type="range"
            min={0}
            max={DTS.length - 1}
            step={1}
            value={dtIdx}
            onInput={onSlide}
            list="ed-dt-ticks"
            aria-label="Integration timestep dt. Drag up and every integrator's drift grows — Euler worst, the symplectic band and RK4 far less."
            aria-valuetext={`dt ${dt} seconds`}
          />
          <datalist id="ed-dt-ticks">
            {DTS.map((s, i) => <option value={i} label={`${s}`} />)}
          </datalist>
          <span class="ed-dt-val">dt = {dt}s</span>
        </div>
      </div>

      {/* --- the two live panels --- */}
      <div class="ed-panels">
        <figure class="ed-panel">
          <figcaption class="ed-cap">
            <span>energy drift vs time</span>
            <b>{system} · dt {dt}s</b>
          </figcaption>
          <EnergyPanel system={system} dt={dt} />
          <div class="ed-readout" aria-hidden="true">
            <div class="ed-row">
              <span class="ed-lg ed-l-euler"><span class="ed-lg-name">explicit Euler</span></span>
              <span class="ed-v ed-bad">{fmtPct(d.euler.rel_final)}</span>
            </div>
            <div class="ed-row">
              <span class="ed-lg ed-l-semi"><span class="ed-lg-name">semi-implicit</span></span>
              <span class={`ed-v ${isFreefall ? "ed-bad" : "ed-ok"}`}>{semiVal}{isFreefall ? "" : " band"}</span>
            </div>
            <div class="ed-row">
              <span class="ed-lg ed-l-rk4"><span class="ed-lg-name">RK4</span></span>
              <span class="ed-v ed-flat">{fmtSci(d.rk4.rel_max)}</span>
            </div>
          </div>
        </figure>

        <figure class="ed-panel">
          <figcaption class="ed-cap">
            <span>{isFreefall ? "why the story breaks" : "phase-space portrait"}</span>
            <b>{isFreefall ? "freefall" : DATA[system].phase?.kind === "xy" ? "position plane" : "position · velocity"}</b>
          </figcaption>
          {isFreefall ? <FreefallCaveat dt={dt} /> : <PhasePanel system={system} />}
        </figure>
      </div>

      {/* non-visual path to the same aha — the qualitative ordering only */}
      <div class="bk-sr" aria-live="polite">{announce}</div>

      <p class="ed-note">
        {isFreefall
          ? <>Energy drifts under <b>both</b> integrators here — the symplectic advantage needs a bounded, oscillatory system. Real curves from engine.py (seed 0, cpu); poster reads with JS off.</>
          : <>Ordering is the rock: <b>Euler ≫ semi-implicit (bounded) &gt; RK4</b>. RK4 is the most <b>accurate</b> per step, not symplectic — its tiny error still creeps one direction over long runs, while semi-implicit's stays bounded. Real curves from engine.py (seed 0, cpu); poster reads with JS off.</>}
      </p>
    </div>
  );
}

export default function EngineDrift() {
  return <EngineDriftToy />;
}
