/**
 * ch1.5 "Generative Policies II: Flow Matching" — the RING + STEP-EFFICIENCY
 * concept-toy (`demo: flow_multimodality`). The sibling of ch1.4's diffusion ring
 * toy, plus the one panel unique to flow: how FEW sampling steps it needs.
 *
 * TWO linked views, one control:
 *   1. The 2D ring scatter. Flow samples (blue) land ON the unit ring across ALL
 *      eight angular modes; the same-width MSE regressor (red) collapses into the
 *      dead center — the average of every direction, the exact point no sample
 *      occupies. The grey ring is the target. (Same lesson as ch1.4, simpler
 *      sampler: an ODE, not the DDPM posterior.)
 *   2. The step-efficiency curve: modes-covered vs the number of forward-Euler
 *      steps. The ONE control is a slider over {2, 3, 5, 8, 100} Euler steps that
 *      re-renders the ring AT that step count AND highlights the curve. Full mode
 *      coverage (8/8) arrives by ~3 steps; only 2 under-resolves (Euler overshoots
 *      the curved marginal field). THE flow-specific point: sampling steps are
 *      DECOUPLED from training — this is ONE trained net re-integrated, the train
 *      loss is identical whatever the step count (measured; see meta.yaml).
 *
 * Unlike ch1.1/ch0.1, this toy needs NO WASM: it renders REAL, pre-computed points
 * from flow.py (seed 0, cpu, default config) — regenerated by
 * site/scripts/vizdata/ch1.5_flow.py into the co-located vizdata.json, verified to
 * match meta.yaml's reference_run (flow 8/8 radius 0.9359 vs regression 0/0.058).
 * So it is pure SVG + design tokens: theme-aware for free, and the server-rendered
 * default IS the JS-off experience (the scatter + curve show at the default step;
 * only the slider goes inert without hydration). Colour per the demo's scheme:
 * flow = --signal blue, regression = --alert red, target ring = neutral ink.
 */
import "./flow-ring.css";
import { useState } from "preact/hooks";
// Real toy points from flow.py, seed 0, cpu — see the file's `provenance` and the
// generator site/scripts/vizdata/ch1.5_flow.py. Committed small text, no binary.
import viz from "../../../../curriculum/phase1_imitation/ch1.5_flow/demo/vizdata.json";

// ---------------------------------------------------------------- typed vizdata
interface FlowEntry {
  pts: number[][];
  modes: number;
  ring_hit: number;
  mean_radius: number;
}
const STEPS: number[] = viz.steps;
const FLOW = viz.flow as Record<string, FlowEntry>;
const DOMAIN: number = viz.domain; // symmetric world half-extent the scatter maps
const FULL_FROM: number = viz.full_coverage_from; // first step count that covers 8/8
const DEFAULT_IDX = Math.max(0, STEPS.indexOf(5)); // boot at flow's headline: 5 steps, 8/8

// ------------------------------------------------------------- scatter geometry
const V = 440; // scatter viewBox (square)
const SCALE = V / (2 * DOMAIN);
const sx = (x: number) => V / 2 + x * SCALE;
const sy = (y: number) => V / 2 - y * SCALE; // world +y up

function Dots({ pts, cls, r }: { pts: number[][]; cls: string; r: number }) {
  return (
    <g class={cls}>
      {pts.map(([x, y]) => (
        <circle cx={sx(x).toFixed(1)} cy={sy(y).toFixed(1)} r={r} />
      ))}
    </g>
  );
}

/** Faint orientation: crosshair axes through the origin + the target unit ring,
 *  drawn under the scatter so the empty center reads as the center. */
function RingGuide() {
  return (
    <g class="fr-guide">
      <line class="fr-axis" x1={sx(-DOMAIN)} y1={sy(0)} x2={sx(DOMAIN)} y2={sy(0)} />
      <line class="fr-axis" x1={sx(0)} y1={sy(-DOMAIN)} x2={sx(0)} y2={sy(DOMAIN)} />
      <circle class="fr-ring-guide" cx={sx(0)} cy={sy(0)} r={SCALE} />
    </g>
  );
}

// ------------------------------------------------------------- efficiency curve
const CW = 440, CH = 150; // curve viewBox
const PAD = { l: 30, r: 14, t: 16, b: 30 };
const PLOT_W = CW - PAD.l - PAD.r;
const PLOT_H = CH - PAD.t - PAD.b;
const cx = (i: number) => PAD.l + (STEPS.length === 1 ? 0 : (i * PLOT_W) / (STEPS.length - 1));
const cy = (modes: number) => PAD.t + (1 - modes / 8) * PLOT_H; // 0..8 modes axis

function EfficiencyCurve({ activeIdx }: { activeIdx: number }) {
  const line = STEPS.map((s, i) => `${cx(i).toFixed(1)},${cy(FLOW[String(s)].modes).toFixed(1)}`).join(" ");
  const yFull = cy(8);
  const y0 = cy(0);
  return (
    <svg
      class="fr-curve-svg"
      viewBox={`0 0 ${CW} ${CH}`}
      role="img"
      aria-label={
        "Line chart: ring modes covered (0 to 8) versus the number of forward-Euler sampling steps. " +
        "At 2 steps flow covers only 3 of 8 modes; by 3 steps it reaches all 8 and stays there through 5, 8, and 100 steps. " +
        "Full coverage arrives at about 3 steps — flow needs very few."
      }
    >
      {/* y grid: 0, full-coverage (8) */}
      <line class="fr-cv-axis" x1={PAD.l} y1={y0} x2={CW - PAD.r} y2={y0} />
      <line class="fr-cv-full" x1={PAD.l} y1={yFull} x2={CW - PAD.r} y2={yFull} />
      <text class="fr-cv-ylab" x={PAD.l - 6} y={yFull + 3} text-anchor="end">8/8</text>
      <text class="fr-cv-ylab" x={PAD.l - 6} y={y0 + 3} text-anchor="end">0</text>
      <text class="fr-cv-full-lab" x={CW - PAD.r} y={yFull - 5} text-anchor="end">full mode coverage</text>

      {/* the modes-covered line */}
      <polyline class="fr-cv-line" points={line} />

      {/* per-step dots + x labels; the active step is highlighted */}
      {STEPS.map((s, i) => {
        const active = i === activeIdx;
        const covered = FLOW[String(s)].modes >= 8;
        return (
          <g class={`fr-cv-node${active ? " is-active" : ""}${covered ? " is-covered" : " is-under"}`}>
            {active && <line class="fr-cv-drop" x1={cx(i)} y1={cy(FLOW[String(s)].modes)} x2={cx(i)} y2={y0} />}
            <circle cx={cx(i)} cy={cy(FLOW[String(s)].modes)} r={active ? 5 : 3.2} />
            <text class="fr-cv-xlab" x={cx(i)} y={CH - PAD.b + 16} text-anchor="middle">{s}</text>
          </g>
        );
      })}
      <text class="fr-cv-xtitle" x={PAD.l + PLOT_W / 2} y={CH - 3} text-anchor="middle">Euler steps</text>
    </svg>
  );
}

// ------------------------------------------------------------------ the island
function FlowRingToy() {
  const [idx, setIdx] = useState(DEFAULT_IDX);
  const step = STEPS[idx];
  const cur = FLOW[String(step)];
  const full = cur.modes >= 8;

  const onSlide = (e: Event) => setIdx(parseInt((e.currentTarget as HTMLInputElement).value, 10));

  const announce = full
    ? `${step} Euler steps: flow covers all 8 of 8 ring modes.`
    : `${step} Euler steps: flow covers only ${cur.modes} of 8 modes — too few steps to resolve the ring.`;

  return (
    <div class="fr">
      <figure class="fr-figure" aria-label="Flow-matching ring toy: flow samples cover all eight ring modes while a regression baseline collapses to the center. A slider sets the number of sampling steps.">
        <svg
          class="fr-scatter"
          viewBox={`0 0 ${V} ${V}`}
          role="img"
          aria-label={
            "Scatter plot on a unit ring. Grey dots trace the target ring in every direction. " +
            "Blue dots are flow-matching samples — they land on the ring across all eight angular modes. " +
            "Red dots are a same-width regression baseline — they collapse into a single blob at the dead center, " +
            "the average of every direction. The blue samples shown are integrated with " +
            step + " forward-Euler steps."
          }
        >
          {/* faint target-ring guide + the real target points (neutral ink) */}
          <RingGuide />
          <Dots pts={viz.target} cls="fr-target" r={1.5} />
          {/* regression baseline — collapsed to the empty center (alert red) */}
          <Dots pts={viz.regression} cls="fr-regress" r={2} />
          {/* flow samples at the current step count — the hero (signal blue) */}
          <Dots pts={cur.pts} cls="fr-flow" r={2.2} />
          {/* the center the regressor lands on and no flow sample occupies */}
          <circle class="fr-center" cx={sx(0)} cy={sy(0)} r={2.4} />
        </svg>

        {/* live readout — modes covered at the current step (invisible made visible) */}
        <div class="fr-hud" aria-hidden="true">
          <div class="fr-hud-row">
            <span class="fr-k">Euler steps</span>
            <span class="fr-v">{step}</span>
          </div>
          <div class="fr-hud-row">
            <span class="fr-k">modes covered</span>
            <span class={`fr-v ${full ? "fr-ok" : "fr-bad"}`}>{cur.modes}/8 {full ? "✓" : "▲"}</span>
          </div>
          <div class="fr-meter" aria-hidden="true">
            <div class="fr-meter-fill" data-under={!full} style={`width:${(cur.modes / 8) * 100}%`} />
          </div>
          <div class="fr-hud-row">
            <span class="fr-k">ring quality · hit</span>
            <span class="fr-v">{cur.ring_hit.toFixed(2)}</span>
          </div>
        </div>

        {/* legend */}
        <div class="fr-legend" aria-hidden="true">
          <span class="fr-lg fr-lg-flow">flow ({step} steps)</span>
          <span class="fr-lg fr-lg-regress">regression</span>
          <span class="fr-lg fr-lg-target">target ring</span>
        </div>
      </figure>

      {/* the SECOND linked view: modes-covered vs steps */}
      <figure class="fr-curve" aria-hidden="true">
        <figcaption class="fr-curve-cap">how few steps flow needs</figcaption>
        <EfficiencyCurve activeIdx={idx} />
      </figure>

      {/* non-visual path to the same aha — only the qualitative coverage state */}
      <div class="bk-sr" aria-live="polite">{announce}</div>

      {/* THE one control — the Euler-step slider (discrete, keyboard-native) */}
      <div class="fr-controls">
        <div class="fr-slider-row">
          <label class="fr-slider-label" for="fr-steps">sampling <b>Euler steps</b></label>
          <input
            id="fr-steps"
            class="fr-slider"
            type="range"
            min={0}
            max={STEPS.length - 1}
            step={1}
            value={idx}
            onInput={onSlide}
            list="fr-step-ticks"
            aria-label="Number of forward-Euler sampling steps. Slide down to 2 to watch flow under-resolve the ring; 3 to 5 already cover all modes."
            aria-valuetext={`${step} Euler steps, ${cur.modes} of 8 modes covered`}
          />
          <datalist id="fr-step-ticks">
            {STEPS.map((s, i) => <option value={i} label={String(s)} />)}
          </datalist>
          <span class={`fr-steps-val ${full ? "" : "fr-steps-under"}`}>{step} steps</span>
        </div>
        <div class="fr-btn-row">
          <button type="button" class="fr-btn" onClick={() => setIdx(0)}>
            drop to 2 steps →
          </button>
          <button type="button" class="fr-btn" onClick={() => setIdx(DEFAULT_IDX)}>
            reset
          </button>
          <span class="fr-note">
            full coverage from ~{FULL_FROM} steps · steps are decoupled from training (one net, re-integrated) · poster reads with JS off
          </span>
        </div>
      </div>
    </div>
  );
}

export default function FlowRing() {
  return <FlowRingToy />;
}
