/**
 * ch2.6 "Sim-to-Real Intuition Lab I: Latency & Noise" — the DEGRADATION-MIRROR
 * concept-toy (`demo: cartpole_latency_degrade`). A recorded-data sibling of
 * ch3.3's engine-drift and ch1.6's eval-bands 2D toys: the reality-gap story, made
 * visual. No WASM — pure SVG over curves + rollouts perturb.py itself produced.
 *
 * This is the OPPOSITE of ch2.1's hero. There the same cartpole policy RECOVERS
 * from a shove (competence in the world it trained on). Here nothing about the
 * policy changes — only the WORLD does: its observations arrive late, or noisy, or
 * the physics is scaled. A policy that trained in one clean world has no defense it
 * was never asked to learn, so it falls apart. That gap is ch2.7's whole motivation.
 *
 * THREE panels, two controls:
 *   1. THE DEGRADATION CURVE — episode return vs perturbation magnitude for the
 *      chosen family (latency / sensor noise / gravity mismatch). A slider walks
 *      the magnitude; a signal-blue marker tracks it and the readout reads off the
 *      return + success at that point. LATENCY is the breaker: return sits at the
 *      500-step ceiling until it cliffs to the floor at 8 steps (160 ms). Sensor
 *      noise only DENTS (halves at σ=0.2). Gravity mismatch is a flat NO-OP — the
 *      honest counter-example that WHICH perturbation bites is the lesson, not that
 *      every knob hurts (mirrors ch3.3's freefall caveat).
 *   2. TWO RECORDED ROLLOUTS side by side — the same balancer on clean observations
 *      (balances the full 500-step horizon, pole flat) vs +160 ms latency (it acts
 *      on where the pole WAS, over-corrects, and falls at step 28). A recorded
 *      replay walks each cart+pole; reduced-motion / JS-off shows the poster frame
 *      (clean upright, degraded fallen) — the contrast reads without any motion.
 *   3. The sim-to-real intuition note (why latency & noise are the gap → ch2.7).
 *
 * Data: REAL curves + rollouts from perturb.py's OWN build_policy + ObsDelay +
 * perceive + evaluate + run_sweep (seed 0, cpu, the hermetic SCRIPTED baseline —
 * no policy binary ships), regenerated by site/scripts/vizdata/ch2.6_perturb.py
 * into the co-located vizdata.json and STOP-on-drift verified against meta.yaml's
 * reference_run STRUCTURE (baseline holds, latency worst and 8-step breaks it,
 * gravity a no-op, noise only dents). So it is pure SVG + design tokens: theme-
 * aware for free, and the server-rendered default (latency, clean) IS the JS-off
 * experience — only the selector + slider + replay go inert without hydration.
 * Colour by MEANING: pole = --entity-pusher amber (mirrors the ch2.1 toy),
 * balanced/clean = --entity-target green, falling/the breaker = --alert red, the
 * one live handle = --signal blue; the benign no-op curve is neutral ink.
 */
import "./LatencyDegradeToy.css";
import { useEffect, useMemo, useRef, useState } from "preact/hooks";
// Real curves + rollouts from perturb.py, seed 0, cpu, scripted baseline — see the
// file's `provenance` and the generator site/scripts/vizdata/ch2.6_perturb.py.
// Committed small text (~4.6 KB), no binary.
import viz from "../../../../curriculum/phase2_reinforcement/ch2.6_perturb/demo/vizdata.json";

// ---------------------------------------------------------------- typed vizdata
type Family = "latency" | "sensor_noise" | "model_mismatch";
interface Sweep {
  knob: string;
  label: string;
  unit: string;
  axis: string;
  ms_per_step: number | null;
  points: number[][]; // [magnitude, success_rate, mean_return]
}
interface Rollout {
  latency_steps: number;
  latency_ms: number;
  steps: number;
  fell: boolean;
  survived: boolean;
  outcome: string;
  t: number[];
  pole_angle: number[];
  cart_pos: number[];
}

const FAMILIES = viz.families as Family[];
const SWEEPS = viz.sweeps as Record<Family, Sweep>;
const BASELINE = viz.baseline as { success_rate: number; mean_return: number };
const WORST = viz.worst_perturbation as Family;
const ROLLOUTS = viz.rollouts as { clean: Rollout; degraded: Rollout };
const MAX_STEPS = viz.max_steps as number;              // 500 — the return ceiling
const ANGLE_LIMIT = viz.angle_limit_rad as number;      // 0.2095 rad — pole-fall threshold
const MS_PER_STEP = viz.ms_per_step as number;          // 20 ms/control-step @ 50 Hz
const DEFAULT_FAMILY = viz.default_family as Family;

// ------------------------------------------------------------ number formatting
const pct = (v: number) => `${Math.round(v * 100)}%`;
/** A magnitude label for a family's grid point (e.g. "4 steps · 80 ms", "σ 0.20"). */
function magLabel(family: Family, mag: number): string {
  if (family === "latency") return `${mag} step${mag === 1 ? "" : "s"} · ${Math.round(mag * MS_PER_STEP)} ms`;
  if (family === "sensor_noise") return `σ ${mag.toFixed(2)}`;
  return `${mag}× gravity`;
}
/** The qualitative verdict at a grid point — drives the aria-live announcement. */
function verdict(success: number): string {
  if (success >= 0.999) return "holds";
  if (success <= 0.001) return "breaks";
  return "dents";
}

// ============================================================= DEGRADATION CURVE
const CW = 470, CH = 244;
const CPAD = { l: 46, r: 16, t: 16, b: 34 };
const CPW = CW - CPAD.l - CPAD.r;
const CPH = CH - CPAD.t - CPAD.b;

function CurvePanel({ family, magIdx }: { family: Family; magIdx: number }) {
  const sweep = SWEEPS[family];
  const pts = sweep.points;
  const n = pts.length;

  // x is the grid INDEX (evenly spaced so every stop is legible, even where the
  // magnitudes bunch up); y is episode return on a fixed 0..MAX_STEPS scale so the
  // latency cliff reads as a genuine fall to the floor, not a rescaled squiggle.
  const px = (i: number) => CPAD.l + (n === 1 ? CPW / 2 : (i / (n - 1)) * CPW);
  const py = (ret: number) => CPAD.t + (1 - ret / MAX_STEPS) * CPH;

  const linePts = pts.map((p, i) => `${px(i).toFixed(1)},${py(p[2]).toFixed(1)}`).join(" ");
  const curClass = family === "latency" ? "ld-c-break" : family === "sensor_noise" ? "ld-c-dent" : "ld-c-noop";

  // y gridlines at 0, 250, 500 (return); x ticks label the magnitudes
  const yTicks = [0, MAX_STEPS / 2, MAX_STEPS];
  const cur = pts[magIdx];
  const cx = px(magIdx), cyTop = CPAD.t, cyBot = CH - CPAD.b;

  return (
    <svg
      class="ld-svg"
      viewBox={`0 0 ${CW} ${CH}`}
      role="img"
      aria-label={
        `Degradation curve: episode return (0 to ${MAX_STEPS}) versus ${sweep.axis} for the cartpole balancer. ` +
        (family === "latency"
          ? "The return holds at the ceiling through small delays, then falls off a cliff to the floor at 8 steps of latency."
          : family === "sensor_noise"
            ? "The return holds through moderate noise and dips at the largest noise level — a dent, not a cliff."
            : "The return is flat at the ceiling at every gravity scale — this perturbation does nothing to the balancer.")
      }
    >
      {/* y gridlines + return ticks */}
      {yTicks.map((r) => {
        const y = py(r);
        return (
          <g>
            <line class="ld-grid" x1={CPAD.l} y1={y} x2={CW - CPAD.r} y2={y} />
            <text class="ld-tick" x={CPAD.l - 6} y={y + 3} text-anchor="end">{r}</text>
          </g>
        );
      })}
      <text class="ld-axis-title" x={CPAD.l - 42} y={CPAD.t + 2}>return</text>

      {/* x axis + magnitude ticks */}
      <line class="ld-axis" x1={CPAD.l} y1={cyBot} x2={CW - CPAD.r} y2={cyBot} />
      {pts.map((p, i) => (
        <text class="ld-tick" x={px(i)} y={cyBot + 13} text-anchor="middle">{p[0]}</text>
      ))}
      <text class="ld-axis-title" x={CW - CPAD.r} y={CH - 3} text-anchor="end">{sweep.axis} →</text>

      {/* the one live handle: a signal-blue guide at the current magnitude */}
      <line class="ld-marker" x1={cx} y1={cyTop} x2={cx} y2={cyBot} />

      {/* the degradation curve + per-point dots coloured by outcome */}
      <polyline class={`ld-line ${curClass}`} points={linePts} />
      {pts.map((p, i) => {
        const succ = p[1];
        const cls = succ >= 0.999 ? "ld-dot-ok" : succ <= 0.001 ? "ld-dot-bad" : "ld-dot-mid";
        return <circle class={`ld-dot ${cls}`} cx={px(i)} cy={py(p[2])} r={i === magIdx ? 5 : 3.2} />;
      })}
      {/* the current point, emphasised with a signal ring */}
      <circle class="ld-marker-ring" cx={cx} cy={py(cur[2])} r={7.5} />
    </svg>
  );
}

// ================================================================ ROLLOUT REPLAY
// A side-view cart + pole, driven from the recorded (cart_pos, pole_angle) trace.
// Full static poster renders at a representative frame (clean upright, degraded
// fallen); the replay walks the frames via refs (no re-render) and is skipped
// entirely under prefers-reduced-motion, so the poster is the reduced-motion truth.
const RV_W = 218, RV_H = 150;
const RV_HALF = 0.62;                 // m of world half-width shown (cart stays well inside)
const RV_SCALE = RV_W / (2 * RV_HALF); // px per metre (isotropic)
const RV_RAIL_Y = RV_H * 0.74;        // rail height down the panel
const POLE_LEN_M = 1.0;               // matches the MJCF pole capsule length
const CART_HW = 0.13 * RV_SCALE, CART_HH = 0.06 * RV_SCALE;

/** cart+pole geometry (svg coords) from world cart_pos (m) and pole_angle (rad). */
function poseToSvg(cartPos: number, angle: number) {
  const cxp = RV_W / 2 + cartPos * RV_SCALE;
  const hingeY = RV_RAIL_Y - CART_HH;
  // pole tip: +sin leans toward +x, height = L*cos above the hinge (svg y up)
  const tipX = cxp + POLE_LEN_M * Math.sin(angle) * RV_SCALE;
  const tipY = hingeY - POLE_LEN_M * Math.cos(angle) * RV_SCALE;
  return { cxp, hingeY, tipX, tipY };
}

function RolloutReplay({ roll, kind }: { roll: Rollout; kind: "clean" | "degraded" }) {
  // poster frame: clean shows the upright start; degraded shows the fallen end.
  const posterIdx = kind === "clean" ? 0 : roll.pole_angle.length - 1;
  const cartRef = useRef<SVGGElement>(null);
  const poleRef = useRef<SVGLineElement>(null);
  const bobRef = useRef<SVGCircleElement>(null);

  const p0 = poseToSvg(roll.cart_pos[posterIdx], roll.pole_angle[posterIdx]);

  useEffect(() => {
    const reduce = typeof window !== "undefined" && window.matchMedia
      && window.matchMedia("(prefers-reduced-motion: reduce)").matches;
    if (reduce) return; // poster (fallen/upright) stands — reduced-motion safe
    const n = roll.pole_angle.length;
    let raf = 0, i = 0, last = performance.now();
    const hold = 700; // ms to hold the final frame before looping, so the fall reads
    let holding = 0;
    const tick = (now: number) => {
      if (holding > 0) {
        if (now - last >= holding) { holding = 0; i = 0; last = now; }
      } else if (now - last >= 45) { // ~22 frames/s along the recorded trace
        last = now;
        const { cxp, tipX, tipY } = poseToSvg(roll.cart_pos[i], roll.pole_angle[i]);
        const cart = cartRef.current, pole = poleRef.current, bob = bobRef.current;
        if (cart) cart.setAttribute("transform", `translate(${(cxp - RV_W / 2).toFixed(1)} 0)`);
        if (pole) { pole.setAttribute("x2", tipX.toFixed(1)); pole.setAttribute("y2", tipY.toFixed(1)); }
        if (bob) { bob.setAttribute("cx", tipX.toFixed(1)); bob.setAttribute("cy", tipY.toFixed(1)); }
        i += 1;
        if (i >= n) { i = n - 1; holding = hold; last = now; } // freeze on the last frame, then loop
      }
      raf = requestAnimationFrame(tick);
    };
    raf = requestAnimationFrame(tick);
    return () => cancelAnimationFrame(raf);
  }, [kind]);

  const railL = RV_W / 2 - RV_HALF * RV_SCALE;
  const railR = RV_W / 2 + RV_HALF * RV_SCALE;
  const fell = kind === "degraded";

  return (
    <svg
      class="ld-roll-svg"
      viewBox={`0 0 ${RV_W} ${RV_H}`}
      role="img"
      aria-label={
        kind === "clean"
          ? `Clean rollout: the cartpole balancer keeps the pole upright for the full ${roll.steps}-step horizon.`
          : `Degraded rollout with ${roll.latency_ms} milliseconds of observation latency: the pole over-corrects and falls at step ${roll.steps}.`
      }
    >
      {/* fall-cone guides at +/- the angle limit, from the hinge (faint) */}
      <g class="ld-fallcone">
        <line x1={RV_W / 2} y1={p0.hingeY} x2={RV_W / 2 + POLE_LEN_M * Math.sin(ANGLE_LIMIT) * RV_SCALE}
          y2={p0.hingeY - POLE_LEN_M * Math.cos(ANGLE_LIMIT) * RV_SCALE} />
        <line x1={RV_W / 2} y1={p0.hingeY} x2={RV_W / 2 - POLE_LEN_M * Math.sin(ANGLE_LIMIT) * RV_SCALE}
          y2={p0.hingeY - POLE_LEN_M * Math.cos(ANGLE_LIMIT) * RV_SCALE} />
      </g>

      {/* rail */}
      <line class="ld-rail" x1={railL} y1={RV_RAIL_Y} x2={railR} y2={RV_RAIL_Y} />
      <line class="ld-rail-end" x1={railL} y1={RV_RAIL_Y - 6} x2={railL} y2={RV_RAIL_Y + 6} />
      <line class="ld-rail-end" x1={railR} y1={RV_RAIL_Y - 6} x2={railR} y2={RV_RAIL_Y + 6} />

      {/* cart (translated by the replay) + pole hinged at its top */}
      <g ref={cartRef} transform={`translate(${(p0.cxp - RV_W / 2).toFixed(1)} 0)`}>
        <rect class="ld-cart" x={RV_W / 2 - CART_HW} y={p0.hingeY - CART_HH} width={2 * CART_HW} height={2 * CART_HH} rx={2} />
      </g>
      <line ref={poleRef} class={`ld-pole ${fell ? "ld-pole-fell" : ""}`}
        x1={p0.cxp.toFixed(1)} y1={p0.hingeY.toFixed(1)} x2={p0.tipX.toFixed(1)} y2={p0.tipY.toFixed(1)} />
      <circle ref={bobRef} class={`ld-bob ${fell ? "ld-bob-fell" : ""}`} cx={p0.tipX.toFixed(1)} cy={p0.tipY.toFixed(1)} r={5} />
    </svg>
  );
}

// ==================================================================== THE ISLAND
function LatencyDegradeToy() {
  const [family, setFamily] = useState<Family>(DEFAULT_FAMILY);
  const [magIdx, setMagIdx] = useState<number>(0); // start clean → the first drag is the aha

  const sweep = SWEEPS[family];
  const pts = sweep.points;
  const cur = pts[magIdx];
  const [mag, success, ret] = cur;
  const v = verdict(success);

  const onFamily = (f: Family) => { setFamily(f); setMagIdx(0); };
  const onSlide = (e: Event) => setMagIdx(parseInt((e.currentTarget as HTMLInputElement).value, 10));

  // aria-live: the qualitative verdict at the current stop, never per-frame spam.
  const announce = useMemo(() => {
    const worst = SWEEPS[WORST];
    const worstExtreme = worst.points[worst.points.length - 1];
    return (
      `${sweep.label} at ${magLabel(family, mag)}: episode return ${Math.round(ret)} of ${MAX_STEPS}, ` +
      `success ${pct(success)} — the balancer ${v}. ` +
      (family === "model_mismatch"
        ? "Gravity mismatch does nothing here: which perturbation bites depends on the task. "
        : "") +
      `The worst perturbation for this policy is ${worst.label}: at ${magLabel(WORST, worstExtreme[0])} ` +
      `its return collapses to ${Math.round(worstExtreme[2])} and success to ${pct(worstExtreme[1])}.`
    );
  }, [family, magIdx]);

  return (
    <div class="ld">
      {/* --- controls: the perturbation family selector + the magnitude slider --- */}
      <div class="ld-controls">
        <div class="ld-seg-row">
          <span class="ld-seg-label">perturb</span>
          <div class="ld-seg" role="group" aria-label="Choose which sim-to-real perturbation to inject">
            {FAMILIES.map((f) => (
              <button
                type="button"
                class="ld-seg-btn"
                aria-pressed={family === f}
                onClick={() => onFamily(f)}
              >
                {SWEEPS[f].label}
                {f === WORST ? <span class="ld-seg-worst" aria-hidden="true"> · worst</span> : null}
              </button>
            ))}
          </div>
        </div>
        <div class="ld-slider-row">
          <label class="ld-slider-label" for="ld-mag">magnitude</label>
          <input
            id="ld-mag"
            class="ld-slider"
            type="range"
            min={0}
            max={pts.length - 1}
            step={1}
            value={magIdx}
            onInput={onSlide}
            list="ld-mag-ticks"
            aria-label={`${sweep.label} magnitude. Drag up to inject more ${sweep.label} and watch the episode return fall.`}
            aria-valuetext={`${magLabel(family, mag)}, return ${Math.round(ret)} of ${MAX_STEPS}, success ${pct(success)}`}
          />
          <datalist id="ld-mag-ticks">
            {pts.map((p, i) => <option value={i} label={`${p[0]}`} />)}
          </datalist>
          <span class={`ld-mag-val ${v === "breaks" ? "ld-bad" : v === "dents" ? "ld-mid" : "ld-ok"}`}>
            {magLabel(family, mag)}
          </span>
        </div>
      </div>

      {/* --- panel 1: the degradation curve --- */}
      <figure class="ld-panel">
        <figcaption class="ld-cap">
          <span>episode return vs {sweep.label}</span>
          <b>{sweep.label} · {magLabel(family, mag)}</b>
        </figcaption>
        <CurvePanel family={family} magIdx={magIdx} />
        <div class="ld-readout" aria-hidden="true">
          <div class="ld-row">
            <span class="ld-k">return</span>
            <span class={`ld-v ${v === "breaks" ? "ld-bad" : v === "dents" ? "ld-mid" : "ld-ok"}`}>
              {Math.round(ret)} / {MAX_STEPS}
            </span>
          </div>
          <div class="ld-row">
            <span class="ld-k">success rate</span>
            <span class={`ld-v ${v === "breaks" ? "ld-bad" : v === "dents" ? "ld-mid" : "ld-ok"}`}>
              {pct(success)} {v === "breaks" ? "▲ fell" : v === "dents" ? "◆ shaky" : "✓ balanced"}
            </span>
          </div>
          <div class="ld-row ld-row-base">
            <span class="ld-k">clean baseline</span>
            <span class="ld-v ld-ok">{Math.round(BASELINE.mean_return)} / {MAX_STEPS} · {pct(BASELINE.success_rate)}</span>
          </div>
        </div>
      </figure>

      {/* --- panel 2: the two recorded rollouts, clean vs +160 ms latency --- */}
      <div class="ld-rolls">
        <figure class="ld-roll">
          <figcaption class="ld-roll-cap">
            <span class="ld-roll-title ld-ok">clean observations</span>
            <span class="ld-roll-sub">balances · {ROLLOUTS.clean.steps} steps</span>
          </figcaption>
          <RolloutReplay roll={ROLLOUTS.clean} kind="clean" />
        </figure>
        <figure class="ld-roll">
          <figcaption class="ld-roll-cap">
            <span class="ld-roll-title ld-bad">+{ROLLOUTS.degraded.latency_ms} ms latency</span>
            <span class="ld-roll-sub">falls · step {ROLLOUTS.degraded.steps}</span>
          </figcaption>
          <RolloutReplay roll={ROLLOUTS.degraded} kind="degraded" />
        </figure>
      </div>

      {/* non-visual path to the same aha — the qualitative verdict only */}
      <div class="bk-sr" aria-live="polite">{announce}</div>

      {/* --- panel 3: the sim-to-real intuition note --- */}
      <p class="ld-note">
        <b>Nothing about the policy changed</b> between these two rollouts — same weights, same clean-sim
        training. Only the <b>world</b> changed: the observation now arrives {ROLLOUTS.degraded.latency_ms} ms
        late. A balancer that never trained on stale state acts on where the pole <b>was</b>, over-corrects,
        and topples. That is the reality gap: sensor noise, observation <b>latency</b>, and physical mismatch
        are what a clean sim leaves out. This policy is most brittle to <b>latency</b> — a thing domain
        randomization alone does not fix — which is exactly why <b>ch2.7</b> trains <b>across</b> the gap.
        Real curves + rollouts from perturb.py (seed 0, cpu, scripted baseline); poster reads with JS off.
      </p>
    </div>
  );
}

export default function LatencyDegrade() {
  return <LatencyDegradeToy />;
}
