/**
 * ch2.3 "4096 Robots at Once: PPO on MJX" — the WALL-CLOCK CLIFF + PARALLEL-TRAINING
 * concept-toy (`demo: mjx_parallel_training`). A sibling of ch1.4's diffusion ring
 * and ch1.6's eval bands: it renders REAL, pre-computed numbers — never invented
 * shapes — as pure SVG + design tokens, so it is theme-aware for free and the
 * server-rendered default IS the JS-off experience.
 *
 * HONESTY — THIS IS RECORDED DATA, NOT A LIVE MJX SIM. MJX runs on jax/XLA and
 * CANNOT run in the browser (there is no jax-WASM path; the playground's ONNX
 * runtimes drive torch->ONNX policies only). So unlike ch1.1/ch2.1 (live MuJoCo-
 * WASM), this toy REPLAYS numbers ppo_mjx.py measured at seed 0 on CPU-jax —
 * regenerated by site/scripts/vizdata/ch2.3_mjx.py into the co-located vizdata.json,
 * verified against meta.yaml (cliff shape climbs-then-plateaus; eval 407.2 / 90.4).
 * Every panel labels this. We never fake a live 4096-env browser run.
 *
 * THREE linked panels:
 *   1. THE WALL-CLOCK CLIFF (headline) — throughput (env-steps/sec) vs num_envs on
 *      a log-x axis. It CLIMBS then PLATEAUS/REVERSES at ~256 envs (CPU cores
 *      saturate). A toggle overlays the PROJECTED GPU continuation to 4096 (dashed,
 *      log-y, labeled "not measured here — the Scale Lab"). Pick a num_envs point.
 *   2. PARALLEL TRAINING — an 8x8 = 64-env grid whose glyphs stand upright as the
 *      RECORDED return climbs, beside the return curve rising toward the 500 cap.
 *      A scrubber replays the recorded run (seed 0); auto-plays unless reduced-motion.
 *   3. THROUGHPUT vs GRADIENT QUALITY — the chapter's lesson: at a FIXED 300k
 *      env-step budget, more envs buy more data/sec but FEWER gradient updates. 256
 *      envs runs faster (105k/s) yet learns worse (9 updates -> 90) than 64 (36 -> 407).
 *
 * Colour discipline: --signal blue = the measured CPU cliff + the live handles;
 * --entity-target green = balancing envs / a solved run; --alert red = a run that
 * fails to solve; neutral ink = axes/grids/the projected (unmeasured) GPU curve.
 */
import "./mjx-parallel.css";
import { useEffect, useRef, useState } from "preact/hooks";
// Real recorded numbers from ppo_mjx.py, seed 0, cpu-jax — see the file's
// `provenance` and the generator site/scripts/vizdata/ch2.3_mjx.py. Small text, no binary.
import viz from "../../../../curriculum/phase2_reinforcement/ch2.3_mjx/demo/vizdata.json";

// ---------------------------------------------------------------- typed vizdata
interface TradeoffRow {
  num_envs: number;
  throughput: number;
  updates: number;
  eval: number | null;
  solves: boolean;
}
const CLIFF = viz.cliff;
const GPU = viz.cliff.projected_gpu;
const RC = viz.return_curve;
const GRID = viz.grid;
const TRADE = viz.tradeoff;
const ROWS = TRADE.rows as TradeoffRow[];

const CAP = RC.cap; // 500
const SOLVE = RC.solve_threshold; // 350
const N_ITERS = RC.returns.length; // 36
const DEFAULT_CLIFF = CLIFF.num_envs.indexOf(CLIFF.plateau_at); // boot at the 256-env plateau

// ------------------------------------------------------------- cliff geometry
const CV = { w: 480, h: 264 };
const CVP = { l: 54, r: 18, t: 22, b: 40 };
const CVW = CV.w - CVP.l - CVP.r;
const CVH = CV.h - CVP.t - CVP.b;
const L2 = (n: number) => Math.log2(n);
// linear-y (CPU-only view) tops just above the CPU peak; log-y (GPU view) spans to 4096
const Y_LIN_MAX = 120_000;
const LOG_MIN = Math.log10(30_000);
const LOG_MAX = Math.log10(12_000_000);

function cliffX(n: number, maxL: number): number {
  return CVP.l + ((L2(n) - L2(16)) / (maxL - L2(16))) * CVW;
}
function cliffY(t: number, log: boolean): number {
  const f = log
    ? (Math.log10(t) - LOG_MIN) / (LOG_MAX - LOG_MIN)
    : t / Y_LIN_MAX;
  return CVP.t + (1 - f) * CVH;
}
const fmtK = (t: number) => (t >= 1_000_000 ? `${(t / 1e6).toFixed(1)}M` : `${Math.round(t / 1000)}k`);

// -------------------------------------------------------------- return geometry
const RV = { w: 480, h: 150 };
const RVP = { l: 40, r: 46, t: 14, b: 26 };
const RVW = RV.w - RVP.l - RVP.r;
const RVH = RV.h - RVP.t - RVP.b;
const rcX = (i: number) => RVP.l + (N_ITERS === 1 ? 0 : (i / (N_ITERS - 1)) * RVW);
const rcY = (r: number) => RVP.t + (1 - Math.min(r, CAP) / CAP) * RVH;

// -------------------------------------------------------------- env-grid layout
const CELLS = GRID.rows * GRID.cols; // 64
// A stable pseudo-random rank per cell (0..63): as the recorded return climbs,
// the lowest-ranked cells stand upright first, so the wall fills in organically
// and deterministically (no Math.random — SSR and client agree). Also a fixed
// fall-direction per cell for the toppled glyphs.
const CELL_RANK: number[] = (() => {
  const idx = Array.from({ length: CELLS }, (_, i) => i);
  let s = 1337; // deterministic LCG shuffle
  for (let i = CELLS - 1; i > 0; i--) {
    s = (s * 1103515245 + 12345) & 0x7fffffff;
    const j = s % (i + 1);
    [idx[i], idx[j]] = [idx[j], idx[i]];
  }
  const rank = new Array<number>(CELLS);
  idx.forEach((cell, r) => (rank[cell] = r));
  return rank;
})();
const CELL_DIR: number[] = Array.from({ length: CELLS }, (_, i) => ((i * 37) % 2 ? 1 : -1));

/** How many of the 64 envs are upright at iteration `i` (recorded return / cap). */
function uprightCount(i: number): number {
  const r = RC.returns[i];
  const frac = r == null ? 0 : Math.max(0, Math.min(1, r / CAP));
  return Math.round(frac * CELLS);
}

// ========================================================== Panel 1: the cliff
function CliffPanel({
  sel,
  showGpu,
  onPick,
}: {
  sel: number;
  showGpu: boolean;
  onPick: (i: number) => void;
}) {
  const maxL = showGpu ? L2(4096) : L2(1024);
  const cpuPts = CLIFF.num_envs.map((n, i) => `${cliffX(n, maxL).toFixed(1)},${cliffY(CLIFF.throughput[i], showGpu).toFixed(1)}`);
  const gpuPts = GPU.num_envs.map((n, i) => `${cliffX(n, maxL).toFixed(1)},${cliffY(GPU.throughput[i], true).toFixed(1)}`);
  const plateauX = cliffX(CLIFF.plateau_at, maxL);
  const y0 = CVP.t + CVH;

  return (
    <svg
      class="mx-cliff-svg"
      viewBox={`0 0 ${CV.w} ${CV.h}`}
      role="img"
      aria-label={
        "Line chart, the wall-clock cliff: throughput in environment-steps per second versus the number of parallel MJX envs on a log axis. " +
        "On CPU-jax it climbs from 16 to 64 to a peak around 256 envs, then falls at 1024 as the cores saturate — the plateau. " +
        (showGpu
          ? "A dashed projected curve shows a GPU continuing to climb past the plateau to 4096 envs; that curve is not measured here."
          : "Toggle the projected GPU curve to see how a GPU keeps climbing past this CPU plateau to 4096 envs.")
      }
    >
      {/* baseline + y ticks */}
      <line class="mx-ax" x1={CVP.l} y1={y0} x2={CV.w - CVP.r} y2={y0} />
      <line class="mx-ax" x1={CVP.l} y1={CVP.t} x2={CVP.l} y2={y0} />
      {(showGpu
        ? [50_000, 500_000, 5_000_000]
        : [40_000, 80_000, 120_000]
      ).map((t) => (
        <g>
          <line class="mx-grid" x1={CVP.l} y1={cliffY(t, showGpu)} x2={CV.w - CVP.r} y2={cliffY(t, showGpu)} />
          <text class="mx-ylab" x={CVP.l - 6} y={cliffY(t, showGpu) + 3} text-anchor="end">{fmtK(t)}</text>
        </g>
      ))}
      <text class="mx-ytitle" transform={`translate(13 ${CVP.t + CVH / 2}) rotate(-90)`} text-anchor="middle">env-steps / sec</text>

      {/* the plateau marker — the headline */}
      <line class="mx-plateau" x1={plateauX} y1={CVP.t} x2={plateauX} y2={y0} />
      <text class="mx-plateau-lab" x={plateauX} y={CVP.t - 6} text-anchor="middle">CPU plateaus here</text>

      {/* PROJECTED GPU continuation (dashed, neutral — NOT measured) */}
      {showGpu && (
        <g class="mx-gpu">
          <polyline class="mx-gpu-line" points={gpuPts.join(" ")} />
          {GPU.num_envs.map((n, i) => (
            <circle class="mx-gpu-dot" cx={cliffX(n, maxL)} cy={cliffY(GPU.throughput[i], true)} r={3} />
          ))}
          <text class="mx-gpu-lab" x={cliffX(4096, maxL)} y={cliffY(GPU.throughput[2], true) - 8} text-anchor="end">
            projected · GPU (Scale Lab) — not measured
          </text>
        </g>
      )}

      {/* the MEASURED CPU cliff (signal blue) */}
      <polyline class="mx-cpu-line" points={cpuPts.join(" ")} />
      {CLIFF.num_envs.map((n, i) => {
        const active = i === sel;
        const x = cliffX(n, maxL), y = cliffY(CLIFF.throughput[i], showGpu);
        return (
          <g class={`mx-cpu-node${active ? " is-active" : ""}`} onClick={() => onPick(i)}>
            {active && <line class="mx-drop" x1={x} y1={y} x2={x} y2={y0} />}
            {/* generous invisible hit target so pointer users can click a point */}
            <circle class="mx-cpu-hit" cx={x} cy={y} r={12} />
            <circle cx={x} cy={y} r={active ? 5.5 : 3.4} />
            <text class="mx-xlab" x={x} y={CV.h - CVP.b + 16} text-anchor="middle">{n}</text>
          </g>
        );
      })}
      <text class="mx-xtitle" x={CVP.l + CVW / 2} y={CV.h - 4} text-anchor="middle">num_envs (parallel MJX worlds)</text>
    </svg>
  );
}

// ================================================== Panel 2: the env wall + curve
function EnvGrid({ iter }: { iter: number }) {
  const up = uprightCount(iter);
  const size = 300;
  const pad = 6;
  const step = (size - 2 * pad) / GRID.cols;
  const half = step * 0.34;
  return (
    <svg
      class="mx-grid-svg"
      viewBox={`0 0 ${size} ${size}`}
      role="img"
      aria-hidden="true"
    >
      {Array.from({ length: CELLS }, (_, c) => {
        const row = Math.floor(c / GRID.cols), col = c % GRID.cols;
        const cx = pad + col * step + step / 2;
        const cy = pad + row * step + step / 2 + half * 0.5;
        const upright = CELL_RANK[c] < up;
        // pole tip: straight up when balancing, toppled to the side otherwise
        const tipX = upright ? cx : cx + CELL_DIR[c] * half * 1.15;
        const tipY = upright ? cy - half * 1.7 : cy - half * 0.45;
        return (
          <g class={`mx-cell${upright ? " is-up" : ""}`}>
            <rect class="mx-cell-cart" x={cx - half * 0.7} y={cy - 1.5} width={half * 1.4} height={3} rx={1} />
            <line class="mx-cell-pole" x1={cx} y1={cy} x2={tipX} y2={tipY} />
          </g>
        );
      })}
    </svg>
  );
}

function ReturnCurve({ iter }: { iter: number }) {
  // full faint curve + the filled portion up to `iter` (nulls skipped)
  const pts = RC.returns
    .map((r, i) => (r == null ? null : `${rcX(i).toFixed(1)},${rcY(r).toFixed(1)}`))
    .filter(Boolean) as string[];
  const shown = RC.returns
    .map((r, i) => (r == null || i > iter ? null : `${rcX(i).toFixed(1)},${rcY(r).toFixed(1)}`))
    .filter(Boolean) as string[];
  const curR = RC.returns[iter] ?? 0;
  const evalY = rcY(RC.eval_return_seed0);
  return (
    <svg
      class="mx-return-svg"
      viewBox={`0 0 ${RV.w} ${RV.h}`}
      role="img"
      aria-label={
        `Line chart: episodic return versus training iteration for the recorded seed-0 run of 64 parallel envs. ` +
        `It climbs from about 22 toward the 500 cap; the solve threshold is ${SOLVE}. ` +
        `The deterministic evaluation scores ${RC.eval_return_seed0}, clearly solving the cartpole.`
      }
    >
      {/* cap + solve reference lines */}
      <line class="mx-rc-cap" x1={RVP.l} y1={rcY(CAP)} x2={RV.w - RVP.r} y2={rcY(CAP)} />
      <text class="mx-rc-ylab" x={RVP.l - 5} y={rcY(CAP) + 3} text-anchor="end">{CAP}</text>
      <line class="mx-rc-solve" x1={RVP.l} y1={rcY(SOLVE)} x2={RV.w - RVP.r} y2={rcY(SOLVE)} />
      <text class="mx-rc-solvelab" x={RV.w - RVP.r} y={rcY(SOLVE) - 4} text-anchor="end">solve · {SOLVE}</text>
      <line class="mx-ax" x1={RVP.l} y1={rcY(0)} x2={RV.w - RVP.r} y2={rcY(0)} />

      {/* faint full curve, then the replayed portion */}
      <polyline class="mx-rc-ghost" points={pts.join(" ")} />
      <polyline class="mx-rc-line" points={shown.join(" ")} />
      <circle class="mx-rc-head" cx={rcX(iter)} cy={rcY(curR)} r={3.6} />

      {/* the deterministic eval — the solved endpoint (green), beyond the noisy train curve */}
      <circle class="mx-rc-eval" cx={RV.w - RVP.r + 20} cy={evalY} r={4.5} />
      <text class="mx-rc-evallab" x={RV.w - RVP.r + 20} y={evalY - 9} text-anchor="middle">eval</text>
      <text class="mx-rc-evalval" x={RV.w - RVP.r + 20} y={evalY + 18} text-anchor="middle">{RC.eval_return_seed0}</text>
      <text class="mx-rc-xtitle" x={RVP.l + RVW / 2} y={RV.h - 4} text-anchor="middle">training iteration ({RC.updates} updates)</text>
    </svg>
  );
}

// ========================================================== the island
function Toy() {
  const [cliffSel, setCliffSel] = useState(DEFAULT_CLIFF);
  const [showGpu, setShowGpu] = useState(false);
  const [iter, setIter] = useState(N_ITERS - 1); // SSR = the solved endpoint (the poster)
  const [playing, setPlaying] = useState(false);
  const rafish = useRef<number | null>(null);

  // Post-hydration replay: rewind to iter 0 and animate the return climb — unless
  // the visitor prefers reduced motion, in which case we stay on the solved frame.
  useEffect(() => {
    const reduce = typeof matchMedia === "function" && matchMedia("(prefers-reduced-motion: reduce)").matches;
    if (reduce) return;
    setIter(0);
    setPlaying(true);
    return () => { if (rafish.current != null) clearInterval(rafish.current); };
  }, []);

  useEffect(() => {
    if (!playing) return;
    const id = window.setInterval(() => {
      setIter((i) => {
        if (i >= N_ITERS - 1) { setPlaying(false); return i; }
        return i + 1;
      });
    }, 70);
    rafish.current = id;
    return () => clearInterval(id);
  }, [playing]);

  const row = ROWS[cliffSel];
  const up = uprightCount(iter);

  // aria-live: the cliff selection (throughput / gradient-quality readout)
  const cliffSay =
    `${row.num_envs} parallel envs: ${row.throughput.toLocaleString()} env-steps per second, ` +
    `${row.updates} gradient updates at the fixed budget. ` +
    (row.eval != null
      ? row.solves
        ? `Eval ${row.eval} — solves.`
        : `Eval ${row.eval} — runs fast but does not solve.`
      : "Eval not recorded at this env count.");

  // aria-live: the training replay, coarse phases so the reader isn't spammed
  const curR = RC.returns[iter] ?? 0;
  const phase =
    iter >= N_ITERS - 1
      ? `Recorded run complete: ${up} of 64 envs balancing during rollout; deterministic eval ${RC.eval_return_seed0} solves the cartpole.`
      : curR < 60
        ? "Early training: the poles fall across almost all 64 envs."
        : curR < SOLVE * 0.6
          ? "Mid training: more envs are holding the pole up as PPO updates land."
          : "Late training: most envs balance in lockstep.";

  const replay = () => { setIter(0); setPlaying(true); };
  const onScrub = (e: Event) => {
    setPlaying(false);
    setIter(parseInt((e.currentTarget as HTMLInputElement).value, 10));
  };
  const onCliff = (e: Event) => setCliffSel(parseInt((e.currentTarget as HTMLInputElement).value, 10));

  return (
    <div class="mx">
      {/* honesty banner — recorded, not a live MJX sim */}
      <p class="mx-recorded">
        recorded run · seed 0 · cpu-jax — <b>replayed, not live</b>: MJX runs on jax/XLA, which cannot run in-browser
      </p>

      {/* ---- Panel 1: the wall-clock cliff (headline) ---------------------- */}
      <figure class="mx-panel mx-panel-cliff">
        <figcaption class="mx-cap">the wall-clock cliff · throughput vs num_envs</figcaption>
        <CliffPanel sel={cliffSel} showGpu={showGpu} onPick={setCliffSel} />
        <div class="mx-cliff-controls">
          <div class="mx-slider-row">
            <label class="mx-slider-label" for="mx-envs">pick <b>num_envs</b></label>
            <input
              id="mx-envs"
              class="mx-slider"
              type="range"
              min={0}
              max={CLIFF.num_envs.length - 1}
              step={1}
              value={cliffSel}
              onInput={onCliff}
              list="mx-env-ticks"
              aria-label="Number of parallel MJX envs to read off the throughput cliff."
              aria-valuetext={`${row.num_envs} envs, ${row.throughput.toLocaleString()} env-steps per second`}
            />
            <datalist id="mx-env-ticks">
              {CLIFF.num_envs.map((n, i) => <option value={i} label={String(n)} />)}
            </datalist>
          </div>
          <button
            type="button"
            class="mx-btn"
            aria-pressed={showGpu}
            onClick={() => setShowGpu((v) => !v)}
          >
            {showGpu ? "hide" : "show"} projected GPU curve
          </button>
        </div>
      </figure>

      {/* ---- Panel 2: parallel training — the env wall + the return curve --- */}
      <figure class="mx-panel mx-panel-train">
        <figcaption class="mx-cap">parallel training · 64 envs learning at once (recorded, seed 0)</figcaption>
        <div class="mx-train-body">
          <div class="mx-grid-wrap">
            <EnvGrid iter={iter} />
            <div class="mx-grid-read" aria-hidden="true">
              <span class="mx-grid-count">{up}<span class="mx-grid-den">/64</span></span>
              <span class="mx-grid-k">envs balancing</span>
            </div>
          </div>
          <div class="mx-return-wrap">
            <ReturnCurve iter={iter} />
          </div>
        </div>
        <div class="mx-scrub-row">
          <button type="button" class="mx-btn mx-btn--primary" onClick={replay}>
            {playing ? "playing…" : "▶ replay the run"}
          </button>
          <input
            class="mx-scrub"
            type="range"
            min={0}
            max={N_ITERS - 1}
            step={1}
            value={iter}
            onInput={onScrub}
            aria-label="Scrub the recorded training run. Drag to step through iterations and watch the envs stand upright as the return climbs."
            aria-valuetext={`Iteration ${iter + 1} of ${N_ITERS}, return ${Math.round(curR)}, ${up} of 64 envs balancing`}
          />
          <span class="mx-scrub-val">iter {iter + 1}/{N_ITERS}</span>
        </div>
      </figure>

      {/* ---- Panel 3: throughput vs gradient quality (the lesson) ---------- */}
      <figure class="mx-panel mx-panel-trade">
        <figcaption class="mx-cap">throughput ≠ learning · a fixed {TRADE.budget_env_steps.toLocaleString()} env-step budget</figcaption>
        <table class="mx-trade-table">
          <thead>
            <tr>
              <th scope="col">num_envs</th>
              <th scope="col">env-steps/s</th>
              <th scope="col">gradient updates</th>
              <th scope="col">eval return</th>
            </tr>
          </thead>
          <tbody>
            {ROWS.map((r, i) => (
              <tr class={`${i === cliffSel ? "is-sel" : ""} ${r.solves ? "is-solve" : ""}`} aria-selected={i === cliffSel}>
                <th scope="row">{r.num_envs}</th>
                <td class="mx-tnum">{r.throughput.toLocaleString()}</td>
                <td class="mx-tnum">{r.updates}</td>
                <td class="mx-tnum">
                  {r.eval == null
                    ? <span class="mx-dash">—</span>
                    : <span class={r.solves ? "mx-ok" : "mx-bad"}>{r.eval} {r.solves ? "✓ solves" : "▲"}</span>}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
        <p class="mx-trade-note">
          More envs buy more data per second — but at a fixed step budget, each PPO gradient is one big batch, so you get
          <b> fewer updates</b>. 256 envs runs fastest (105k/s) yet learns worst (9 updates → 90); 64 envs solves (36 updates → 407).
        </p>
      </figure>

      {/* non-visual paths to the two ahas (throughput selection + the return climb) */}
      <div class="bk-sr" aria-live="polite">{cliffSay}</div>
      <div class="bk-sr" aria-live="polite">{phase}</div>
    </div>
  );
}

export default function MjxParallelToy() {
  return <Toy />;
}
