/**
 * ch3.8 "Reading the Frontier" — the CHECKPOINT-PROBE concept-toy
 * (`demo: checkpoint_probe`). A recorded-data sibling of ch3.3's engine-drift and
 * ch1.6's eval-bands 2D toys: the honesty story of reading a checkpoint, made
 * visual. No WASM, no async boot — pure HTML/SVG over numbers probe.py itself
 * measured (seed 0, cpu), so it is theme-aware for free and its server-rendered
 * default IS the JS-off experience; only the one focus toggle goes inert without
 * hydration.
 *
 * THE LOAD-BEARING LESSON (the centerpiece, panel 1):
 *   A probe that recovers an INPUT proves nothing. The task-id probe hits ~1.0 on
 *   BOTH the trained checkpoint AND a random-init control — because the instruction
 *   token is a literal input to the fused layer, so any projection carries it. The
 *   read that MEANS something is the routed-coordinate R^2 (0.90 trained vs 0.16
 *   random): a value the model had to COMPUTE. The trained-vs-random contrast is
 *   the whole point, and the task-id-saturates-on-both is the lesson, not a bug.
 *
 * Panels:
 *   1. THE CAVEAT + THE SIGNAL — two linear probes of the fused layer, trained vs
 *      random-init control. task-id: both ~1.0 (recovers an input → proves nothing);
 *      routed-coord R^2: 0.90 vs 0.16 (the real, computed signal). The ONE control
 *      is a focus toggle between the two reads (both always rendered; JS-off shows
 *      the full contrast, hydration just emphasises one and updates the aria-live).
 *   2. THE FOUR MOVES (load / inspect / hook / probe) + the checkpoint's insides —
 *      the ~7.3K-param inspect table (the fused `norm` layer the hook + probe read
 *      is flagged) and the CLS-attention strip (it peaks on the TASK token).
 *   3. THE FRONTIER note — the transferable "read probing claims skeptically" lesson,
 *      mapping the four moves to pi0 (openpi) and GR00T at 14 GB.
 *
 * Colour by MEANING: the caveat probe's bars are neutral --ink-mute (they prove
 * nothing) and flagged in --alert; the signal probe's trained bar is --signal blue
 * (the real read), its random control neutral ink. Real numbers from probe.py, seed
 * 0, cpu — regenerated by site/scripts/vizdata/ch3.8_frontier.py into the co-located
 * vizdata.json, STOP-on-drift verified against meta.yaml. Committed small text.
 */
import "./ProbeToy.css";
import { useEffect, useState } from "preact/hooks";
// Real numbers from probe.py, seed 0, cpu — see the file's `provenance` and the
// generator site/scripts/vizdata/ch3.8_frontier.py. Committed small text, no binary.
import viz from "../../../../curriculum/phase3_advanced/ch3.8_frontier/demo/vizdata.json";

// ---------------------------------------------------------------- typed vizdata
interface ProbeRead {
  label: string;
  kind: "accuracy" | "r2";
  trained: number;
  control: number;
  chance?: number;
  role: "caveat" | "signal";
}
interface Shape { name: string; shape: number[]; }
interface Module { name: string; params: number; shapes: Shape[]; probed: boolean; }
interface Direct { name: string; params: number; shape: number[]; }
interface ClsAttn { labels: string[]; values: number[]; argmax_index: number; argmax_label: string; }

const PROBE = viz.probe as { task_id: ProbeRead; routed_coord: ProbeRead };
const ARCH = viz.architecture as {
  total_params: number; config: Record<string, number>; probed_module: string;
  modules: Module[]; direct_params: Direct[];
};
const CLS = viz.cls_attention as ClsAttn;
const MOVES = viz.moves as string[];
const PROV = viz.provenance as Record<string, string | number>;

// The four moves, each with the one-line WHY (mirrors probe.py's region headers).
const MOVE_DESC: Record<string, string> = {
  load: "pour the saved state_dict into an architecture skeleton you hold",
  inspect: "enumerate the modules, their shapes, and their parameter counts",
  hook: "capture a hidden layer's activations — you can't edit a released forward()",
  probe: "fit a LINEAR map from those activations to a KNOWN factor, read its score",
};

// ------------------------------------------------------------ number formatting
const pct = (v: number) => `${Math.max(0, Math.min(100, v * 100)).toFixed(1)}%`;
const fmt2 = (v: number) => v.toFixed(2);

// ============================================================ CENTERPIECE PANEL
function ProbeBars({ p, emphasised }: { p: ProbeRead; emphasised: boolean }) {
  const isSignal = p.role === "signal";
  const gap = p.trained - p.control;
  // aria-label carries the full contrast so the SVG-free bars still read for AT.
  const desc =
    `${p.label}: trained checkpoint ${fmt2(p.trained)}, random-init control ${fmt2(p.control)}` +
    (p.chance !== undefined ? `, chance ${fmt2(p.chance)}` : "") +
    (isSignal
      ? `. The gap of ${fmt2(gap)} is the real signal — a value the model had to compute; only training put it there.`
      : `. Both are about equal: this probe recovered an input token, so it proves nothing.`);

  return (
    <div class={`pt-probe pt-probe--${p.role}`} data-emph={emphasised} role="group" aria-label={desc}>
      <div class="pt-probe-head">
        <span class="pt-probe-name">{p.label}</span>
        <span class={`pt-probe-tag pt-tag--${p.role}`}>
          {isSignal ? "the real read · a COMPUTED value" : "recovers an INPUT · proves nothing"}
        </span>
      </div>

      <div class="pt-bars" aria-hidden="true">
        {(["trained", "control"] as const).map((which) => {
          const v = which === "trained" ? p.trained : p.control;
          const label = which === "trained" ? "trained" : "random-init control";
          // trained-vs-control colour: the signal probe's TRAINED bar is the one
          // real signal (blue); everything else is neutral ink (proves little).
          const hero = isSignal && which === "trained";
          return (
            <div class="pt-bar-row">
              <span class="pt-bar-lab">{label}</span>
              <div class="pt-bar-track">
                <div class={`pt-bar-fill ${hero ? "pt-fill--signal" : "pt-fill--mute"}`} style={`width:${pct(v)}`} />
                {p.chance !== undefined && (
                  <span class="pt-chance" style={`left:${pct(p.chance)}`} title={`chance ${fmt2(p.chance)}`} />
                )}
              </div>
              <span class={`pt-bar-val ${hero ? "pt-val--signal" : ""}`}>{fmt2(v)}</span>
            </div>
          );
        })}
      </div>

      <div class="pt-verdict" aria-hidden="true">
        {isSignal ? (
          <>
            <b class="pt-verdict-sig">gap {fmt2(gap)}</b> — only training makes the fused token encode the
            routed coordinate's <b>value</b>. <b class="pt-verdict-sig">This</b> is the signal.
          </>
        ) : (
          <>
            both <b class="pt-verdict-cav">≈ {fmt2(p.trained)}</b> — the instruction token is a literal input,
            so any projection carries it. A probe that recovers an input proves <b class="pt-verdict-cav">nothing</b>.
          </>
        )}
      </div>
    </div>
  );
}

// ================================================================ INSPECT TABLE
function InspectTable() {
  const rows = ARCH.modules;
  const maxP = Math.max(...rows.map((m) => m.params));
  return (
    <div class="pt-inspect" aria-hidden="true">
      {rows.map((m) => (
        <div class={`pt-mod ${m.probed ? "pt-mod--probed" : ""}`}>
          <span class="pt-mod-name">
            {m.name}
            {m.probed && <span class="pt-mod-flag">← hooked + probed</span>}
          </span>
          <div class="pt-mod-track">
            <div class={`pt-mod-fill ${m.probed ? "pt-mod-fill--probed" : ""}`} style={`width:${pct(m.params / maxP)}`} />
          </div>
          <span class="pt-mod-p">{m.params.toLocaleString()}</span>
        </div>
      ))}
      <div class="pt-mod pt-mod--total">
        <span class="pt-mod-name">
          TOTAL
          <span class="pt-mod-direct">+ cls, pos ({ARCH.direct_params.reduce((s, d) => s + d.params, 0)})</span>
        </span>
        <div class="pt-mod-track" />
        <span class="pt-mod-p">{ARCH.total_params.toLocaleString()}</span>
      </div>
    </div>
  );
}

// ============================================================= CLS ATTENTION STRIP
const AW = 300, AH = 96, AB = 22, APAD = 6;
function ClsAttention() {
  const n = CLS.values.length;
  const maxV = Math.max(...CLS.values);
  const bw = (AW - APAD * 2) / n;
  return (
    <svg
      class="pt-attn-svg"
      viewBox={`0 0 ${AW} ${AH}`}
      role="img"
      aria-label={
        `CLS-token attention over the input sequence ${CLS.labels.join(", ")}. ` +
        `It peaks on the '${CLS.argmax_label}' token (index ${CLS.argmax_index}) — the fused token looks at the instruction word to route.`
      }
    >
      {CLS.values.map((v, i) => {
        const h = (v / maxV) * (AH - AB - APAD);
        const x = APAD + i * bw;
        const y = AH - AB - h;
        const peak = i === CLS.argmax_index;
        return (
          <g>
            <rect class={`pt-attn-bar ${peak ? "pt-attn-bar--peak" : ""}`}
              x={x + 3} y={y} width={bw - 6} height={h} rx={2} />
            <text class={`pt-attn-lab ${peak ? "pt-attn-lab--peak" : ""}`}
              x={x + bw / 2} y={AH - AB + 12} text-anchor="middle">{CLS.labels[i]}</text>
          </g>
        );
      })}
    </svg>
  );
}

// ==================================================================== THE ISLAND
function ProbeToy() {
  // JS-off shows the FULL contrast (both probes, undimmed). Emphasis/dim applies
  // only after hydration, so nothing is hidden without JavaScript.
  const [mounted, setMounted] = useState(false);
  const [focus, setFocus] = useState<"caveat" | "signal">("caveat");
  useEffect(() => setMounted(true), []);

  const routed = PROBE.routed_coord;
  const task = PROBE.task_id;
  const gap = routed.trained - routed.control;

  // aria-live: the qualitative reading of the focused probe, never per-frame spam.
  const announce = !mounted
    ? ""
    : focus === "caveat"
      ? `The caveat: task-id accuracy is ${fmt2(task.trained)} for the trained checkpoint and ${fmt2(task.control)} for a random-init control — about equal. ` +
        "The instruction token is a literal input to the fused layer, so a linear probe recovers it from either. A probe that recovers an input proves nothing."
      : `The real signal: the routed-coordinate R squared is ${fmt2(routed.trained)} for the trained checkpoint versus ${fmt2(routed.control)} for the random control, a gap of ${fmt2(gap)}. ` +
        "That coordinate's value is a quantity the model had to compute — only training put it into the representation. This is the read that means something.";

  return (
    <div class="pt" data-mounted={mounted} data-focus={focus}>
      {/* --- the ONE control: focus the caveat or the real signal --- */}
      <div class="pt-controls">
        <span class="pt-seg-label">read the probe as</span>
        <div class="pt-seg" role="group" aria-label="Which read of the fused-layer probe to emphasise">
          <button
            type="button"
            class="pt-seg-btn"
            aria-pressed={focus === "caveat"}
            onClick={() => setFocus("caveat")}
          >
            the caveat
          </button>
          <button
            type="button"
            class="pt-seg-btn"
            aria-pressed={focus === "signal"}
            onClick={() => setFocus("signal")}
          >
            the real signal
          </button>
        </div>
        <span class="pt-seg-hint">
          {focus === "caveat"
            ? "a probe recovering an INPUT proves nothing"
            : "a value the model had to COMPUTE"}
        </span>
      </div>

      {/* --- PANEL 1: the centerpiece — trained vs random, two probes --- */}
      <figure class="pt-panel pt-panel--center">
        <figcaption class="pt-cap">
          <span>linear probe of the fused layer · trained vs random-init</span>
          <b>held-out split</b>
        </figcaption>
        <ProbeBars p={task} emphasised={focus === "caveat"} />
        <ProbeBars p={routed} emphasised={focus === "signal"} />
        <p class="pt-headline" aria-hidden="true">
          Same fused layer, same two checkpoints. The task-id bars are <b>equal</b> (a probe recovered an
          input) — the routed-coordinate bars are <b class="pt-verdict-sig">far apart</b> (training put a
          computed quantity there). Trust the second read, not the first.
        </p>
      </figure>

      {/* --- PANEL 2: the four moves + the checkpoint's insides --- */}
      <div class="pt-panels-2">
        <figure class="pt-panel">
          <figcaption class="pt-cap">
            <span>the four moves</span>
            <b>load · inspect · hook · probe</b>
          </figcaption>
          <ol class="pt-moves">
            {MOVES.map((m, i) => (
              <li class="pt-move">
                <span class="pt-move-i">{i + 1}</span>
                <span class="pt-move-body">
                  <b class="pt-move-name">{m}</b>
                  <span class="pt-move-desc">{MOVE_DESC[m]}</span>
                </span>
              </li>
            ))}
          </ol>
          <p class="pt-note pt-note--tight">
            Identical whether the file on disk is <b>20 KB</b> or <b>14 GB</b> — the mechanics are size-invariant.
          </p>
        </figure>

        <figure class="pt-panel">
          <figcaption class="pt-cap">
            <span>what's inside the file</span>
            <b>{ARCH.total_params.toLocaleString()} params</b>
          </figcaption>
          <InspectTable />
          <div class="pt-attn">
            <div class="pt-attn-head">the fused CLS token attends to</div>
            <ClsAttention />
            <p class="pt-note pt-note--tight" aria-hidden="true">
              It peaks on the <b class="pt-attn-peakword">{CLS.argmax_label}</b> token — an interpretable read:
              the fusion looks at the instruction word to route.
            </p>
          </div>
        </figure>
      </div>

      {/* --- PANEL 3: the frontier note (the transferable lesson) --- */}
      <figure class="pt-panel pt-panel--frontier">
        <figcaption class="pt-cap">
          <span>reading the real frontier</span>
          <b>pi0 · GR00T</b>
        </figcaption>
        <p class="pt-frontier-p">
          A released VLA — Physical Intelligence's <b>pi0</b> (openpi), NVIDIA's <b>GR00T N1</b> — is these same
          pieces, scaled and pretrained: a fused VLM token conditioning a flow-matching action head. You read it
          with the exact four moves above, and you carry the exact caveat: when someone claims a probe shows
          pi0's fused token "knows the task," ask first —{" "}
          <b class="pt-verdict-cav">did the probe just recover an input?</b> The read that survives that question
          is a value the model had to <b class="pt-verdict-sig">compute</b>.
        </p>
      </figure>

      {/* non-visual path to the same aha — the focused reading, qualitatively */}
      <div class="bk-sr" aria-live="polite">{announce}</div>

      <p class="pt-note">
        The task-id probe hitting <b>≈ 1.0 on both</b> checkpoints is the <b>lesson</b>, not a bug. The honest
        evidence of learning is the routed-coordinate R² gap (<b class="pt-verdict-sig">{fmt2(routed.trained)}</b>{" "}
        vs <b>{fmt2(routed.control)}</b>). Real numbers from probe.py (seed 0, cpu); wall-clock {String(PROV.wallclock)};
        this panel reads with JS off.
      </p>
    </div>
  );
}

export default function ProbeToyIsland() {
  return <ProbeToy />;
}
