/**
 * QuadrupedWalkToy — ch2.5 "Locomotion: The Quadruped Walks" concept-toy
 * (demo id `quadruped_walk`). THE PAYOFF of Phase 2's RL arc, made into one
 * figure: nobody scripts the gait. You write a reward, hand it to SAC, and a
 * walking motion EMERGES — the torso falls into a stride and travels forward.
 *
 * THREE panels, top to bottom:
 *   1. THE QUADRUPED WALKING — a recorded side-view replay of the learned policy's
 *      deterministic hero episode (seed 500000 = walk.py's own gait recording).
 *      The camera follows the torso so the scrolling ground + the forward-progress
 *      track read the travel; a foot-contact strip shows the periodic stride —
 *      structure a random flail never has. Reduced-motion safe: the full static
 *      mid-stride frame + progress + strip render regardless; only the rAF replay
 *      is gated, and a keyboard scrubber reaches every frame.
 *   2. FORWARD PROGRESS OVER TRAINING — eval forward distance climbing off the
 *      "just stand" floor over env steps, past the scripted-trot line: the walk
 *      taking shape. RL is non-monotonic; the curve wobbles as it climbs.
 *   3. THE HONEST FREE-TIER CEILING — the emergent gait travels FURTHER than the
 *      scripted trot (+3.02 m vs +2.15 m) but is LESS STABLE: it sprints and falls
 *      before the 500-step horizon (mean length ~249), so its RETURN (~247) sits
 *      BELOW the trot's (~307). Emergent != robust at a CPU-laptop budget; a full,
 *      robust trot is the Scale Lab. The toy tells the truth, not a fairy tale.
 *
 * Like ch3.3/ch3.6 this needs NO WASM: it renders a REAL recorded rollout + the
 * REAL training curve from walk.py (seed 0, cpu, 60k steps) — regenerated by
 * site/scripts/vizdata/ch2.5_walk.py into the co-located vizdata.json, verified to
 * match meta.yaml reference_run (mean fwd 3.0246 m, return 247.22, length 249.1,
 * trot 2.1536 m). So it is pure SVG + design tokens: theme-aware for free, and the
 * server-rendered default (static mid-stride frame + progress + curve + ceiling) IS
 * the JS-off experience; hydration only adds the replay animation + the scrubber.
 * Colour by MEANING: the emergent gait = --signal blue (the learned hero), the
 * scripted trot = --entity-target green (the reference it passes / falls short of),
 * the honest caveat = --alert red.
 *
 * Follows the FROZEN CONCEPT-TOY CONTRACT documented at the top of ../PlateIsland.tsx.
 */
import "./quadruped-walk.css";
import { useEffect, useRef, useState } from "preact/hooks";
// Real recorded gait + training curve from walk.py, seed 0, cpu — see the file's
// `provenance` and the generator site/scripts/vizdata/ch2.5_walk.py. Committed
// small text, no binary.
import viz from "../../../../curriculum/phase2_reinforcement/ch2.5_walk/demo/vizdata.json";

// ---------------------------------------------------------------- typed vizdata
interface Frame {
  t: number;
  torso: number[];          // [world x, world z (height), pitch rad]
  vx: number;
  legs: Record<string, number[][]>; // leg -> [hip[x,z], knee[x,z], foot[x,z]]
  contact: boolean[];       // per leg, in `legs order`
}
interface Geometry {
  torso_half: number[];     // [x half, z half] of the torso box (side view)
  foot_radius: number;
  floor_z: number;
  stand_height: number; target_height: number; fall_height: number;
  legs: string[];
  near_legs: string[];      // -y side (solid)
  far_legs: string[];       // +y side (faded — depth cue)
}
interface Summary {
  mean_eval_forward_dist: number; mean_eval_forward_vel: number;
  mean_eval_return: number; mean_eval_length: number;
  scripted_trot_forward_dist: number; scripted_trot_return: number;
  stand_forward_dist: number; random_forward_dist: number; horizon_steps: number;
}

const GEO = viz.geometry as Geometry;
const GAIT = viz.gait as { seed: number; forward: number; length: number; return: number; mean_vx: number; frames: Frame[] };
const CURVE = viz.curve as number[][];          // [env_step, eval_return, eval_forward_dist]
const WALKS_AT = viz.walks_at_env_steps as number | null;
const SUM = viz.summary as Summary;
const FRAMES = GAIT.frames;
const N = FRAMES.length;
const LEGS = GEO.legs;
const NEAR = new Set(GEO.near_legs);

// number formatting
const m2 = (v: number) => `${v >= 0 ? "+" : ""}${v.toFixed(2)} m`;

// ========================================================== side-view geometry
// World (x, z) → svg px, camera-following the torso so the robot stays centred and
// the ground scrolls (the forward-progress cue). Side/sagittal plane: +x forward
// (screen right), +z up (screen up).
const AW = 460, AH = 220, FLOOR_Y = 176;
const WIN_M = 1.5;                 // metres of world shown across the arena width
const S = AW / WIN_M;              // px per metre
const sx = (wx: number, camX: number) => AW / 2 + (wx - camX) * S;
const sy = (wz: number) => FLOOR_Y - wz * S;
const TORSO_W = 2 * GEO.torso_half[0] * S;
const TORSO_H = 2 * GEO.torso_half[1] * S;
const FOOT_R = Math.max(3, GEO.foot_radius * S);

/** One recorded frame drawn side-on, camera fixed on this frame's torso x. */
function Robot({ f }: { f: Frame }) {
  const camX = f.torso[0];
  const cx = sx(f.torso[0], camX), cz = sy(f.torso[1]);
  const pitchDeg = (f.torso[2] * 180) / Math.PI;
  return (
    <g>
      {/* far legs first (behind the torso), then torso, then near legs on top */}
      {LEGS.filter((l) => !NEAR.has(l)).map((l) => (
        <polyline
          class="qw-leg qw-leg--far"
          points={f.legs[l].map(([x, z]) => `${sx(x, camX).toFixed(1)},${sy(z).toFixed(1)}`).join(" ")}
        />
      ))}
      {LEGS.filter((l) => !NEAR.has(l)).map((l, i) => {
        const foot = f.legs[l][2];
        return (
          <circle
            class={`qw-foot qw-foot--far ${f.contact[LEGS.indexOf(l)] ? "qw-foot--stance" : "qw-foot--swing"}`}
            cx={sx(foot[0], camX).toFixed(1)} cy={sy(foot[1]).toFixed(1)} r={FOOT_R}
            key={`far-foot-${i}`}
          />
        );
      })}
      <rect
        class="qw-torso"
        x={(cx - TORSO_W / 2).toFixed(1)} y={(cz - TORSO_H / 2).toFixed(1)}
        width={TORSO_W.toFixed(1)} height={TORSO_H.toFixed(1)} rx={3}
        transform={`rotate(${(-pitchDeg).toFixed(1)} ${cx.toFixed(1)} ${cz.toFixed(1)})`}
      />
      {LEGS.filter((l) => NEAR.has(l)).map((l) => (
        <polyline
          class="qw-leg qw-leg--near"
          points={f.legs[l].map(([x, z]) => `${sx(x, camX).toFixed(1)},${sy(z).toFixed(1)}`).join(" ")}
        />
      ))}
      {LEGS.filter((l) => NEAR.has(l)).map((l, i) => {
        const hip = f.legs[l][0], foot = f.legs[l][2];
        const stance = f.contact[LEGS.indexOf(l)];
        return (
          <g key={`near-${i}`}>
            <circle class="qw-jhead" cx={sx(hip[0], camX).toFixed(1)} cy={sy(hip[1]).toFixed(1)} r={2.6} />
            <circle
              class={`qw-foot ${stance ? "qw-foot--stance" : "qw-foot--swing"}`}
              cx={sx(foot[0], camX).toFixed(1)} cy={sy(foot[1]).toFixed(1)} r={FOOT_R}
            />
          </g>
        );
      })}
    </g>
  );
}

/** The scrolling ground: a floor line + world-anchored tick marks (they slide past
 *  as the camera follows the torso, so the travel reads even though the robot is
 *  centred). */
function Ground({ camX }: { camX: number }) {
  const first = Math.ceil((camX - WIN_M / 2 - 0.25) / 0.25) * 0.25;
  const ticks: number[] = [];
  for (let x = first; x <= camX + WIN_M / 2 + 0.25; x += 0.25) ticks.push(Math.round(x * 100) / 100);
  return (
    <g>
      <line class="qw-floor" x1={0} y1={FLOOR_Y} x2={AW} y2={FLOOR_Y} />
      {ticks.map((tx, i) => {
        const px = sx(tx, camX);
        if (px < -4 || px > AW + 4) return null;
        const label = Math.abs(Math.round(tx * 4) % 2) === 0; // label every 0.5 m
        return (
          <g class="qw-tick" key={i}>
            <line x1={px.toFixed(1)} y1={FLOOR_Y} x2={px.toFixed(1)} y2={(FLOOR_Y + (label ? 9 : 5)).toFixed(1)} />
            {label && (
              <text class="qw-tick-lbl" x={px.toFixed(1)} y={FLOOR_Y + 19} text-anchor="middle">
                {tx.toFixed(1)}m
              </text>
            )}
          </g>
        );
      })}
    </g>
  );
}

// ============================================================ foot-contact strip
// The periodic stride: per leg, a timeline of stance (filled) vs swing over the
// hero episode. A gait is STRUCTURE — regular alternation — where random is noise.
const SW = 460, STRIP_LEFT = 26, STRIP_ROW = 12, STRIP_GAP = 3;
const STRIP_H = LEGS.length * (STRIP_ROW + STRIP_GAP) + 4;

function ContactStrip({ headIdx }: { headIdx: number }) {
  const trackW = SW - STRIP_LEFT - 6;
  const runs = (leg: number): [number, number][] => {
    const out: [number, number][] = [];
    let start = -1;
    for (let i = 0; i < N; i++) {
      const on = FRAMES[i].contact[leg];
      if (on && start < 0) start = i;
      if ((!on || i === N - 1) && start >= 0) { out.push([start, on ? i : i - 1]); start = -1; }
    }
    return out;
  };
  const headX = STRIP_LEFT + (headIdx / Math.max(1, N - 1)) * trackW;
  return (
    <svg class="qw-strip" viewBox={`0 0 ${SW} ${STRIP_H + 12}`} role="img"
      aria-label="Foot-contact timeline for the four legs over the recorded episode. Each leg alternates stance and swing in a regular pattern — the periodic structure of a gait.">
      {LEGS.map((leg, r) => {
        const y = 2 + r * (STRIP_ROW + STRIP_GAP);
        return (
          <g key={leg}>
            <text class="qw-strip-lbl" x={0} y={y + STRIP_ROW - 2}>{leg}</text>
            <rect class="qw-strip-bg" x={STRIP_LEFT} y={y} width={trackW} height={STRIP_ROW} rx={2} />
            {runs(r).map(([a, b], i) => {
              const x0 = STRIP_LEFT + (a / Math.max(1, N - 1)) * trackW;
              const x1 = STRIP_LEFT + (b / Math.max(1, N - 1)) * trackW;
              return <rect class="qw-strip-on" x={x0.toFixed(1)} y={y} width={Math.max(1.5, x1 - x0).toFixed(1)} height={STRIP_ROW} rx={2} key={i} />;
            })}
          </g>
        );
      })}
      <line class="qw-strip-head" x1={headX.toFixed(1)} y1={0} x2={headX.toFixed(1)} y2={STRIP_H} />
      <text class="qw-strip-lbl" x={STRIP_LEFT} y={STRIP_H + 10}>stance (filled) · swing — over the episode →</text>
    </svg>
  );
}

// ============================================================ training curve
const CW = 470, CH = 210;
const CPAD = { l: 44, r: 12, t: 14, b: 28 };
const CPW = CW - CPAD.l - CPAD.r, CPH = CH - CPAD.t - CPAD.b;

function TrainingCurve() {
  const steps = CURVE.map((r) => r[0]);
  const dists = CURVE.map((r) => r[2]);
  const maxStep = steps[steps.length - 1] || 1;
  const yMax = Math.max(GAIT.forward, SUM.scripted_trot_forward_dist, ...dists) + 0.35;
  const yMin = Math.min(SUM.random_forward_dist, ...dists) - 0.15;
  const cx = (s: number) => CPAD.l + (s / maxStep) * CPW;
  const cy = (d: number) => CPAD.t + ((yMax - d) / (yMax - yMin)) * CPH;
  const yTicks: number[] = [];
  for (let v = Math.ceil(yMin); v <= Math.floor(yMax); v++) yTicks.push(v);
  const xTicks = [0, 0.25, 0.5, 0.75, 1].map((f) => Math.round((f * maxStep) / 1000) * 1000).filter((s) => s <= maxStep);
  const pts = CURVE.map((r) => `${cx(r[0]).toFixed(1)},${cy(r[2]).toFixed(1)}`).join(" ");
  return (
    <svg class="qw-chart" viewBox={`0 0 ${CW} ${CH}`} role="img"
      aria-label={
        `Line chart: the emergent gait's held-out forward distance versus training env steps, from 0 to ${maxStep} steps. ` +
        `It climbs off the just-stand floor near zero, crosses the scripted-trot line at ${SUM.scripted_trot_forward_dist.toFixed(2)} metres, ` +
        `and reaches ${SUM.mean_eval_forward_dist.toFixed(2)} metres. The climb is non-monotonic — reinforcement learning wobbles as it improves.`
      }>
      {yTicks.map((v) => (
        <g key={`y${v}`}>
          <line class="qw-cgrid" x1={CPAD.l} y1={cy(v)} x2={CW - CPAD.r} y2={cy(v)} />
          <text class="qw-tick2" x={CPAD.l - 5} y={cy(v) + 3} text-anchor="end">{v}m</text>
        </g>
      ))}
      {/* reference lines: the stand floor + the scripted trot's distance */}
      <line class="qw-ref qw-ref--stand" x1={CPAD.l} y1={cy(SUM.stand_forward_dist)} x2={CW - CPAD.r} y2={cy(SUM.stand_forward_dist)} />
      <text class="qw-ref-lbl qw-ref-lbl--stand" x={CW - CPAD.r} y={cy(SUM.stand_forward_dist) - 3} text-anchor="end">just stand</text>
      <line class="qw-ref qw-ref--trot" x1={CPAD.l} y1={cy(SUM.scripted_trot_forward_dist)} x2={CW - CPAD.r} y2={cy(SUM.scripted_trot_forward_dist)} />
      <text class="qw-ref-lbl qw-ref-lbl--trot" x={CW - CPAD.r} y={cy(SUM.scripted_trot_forward_dist) - 3} text-anchor="end">scripted trot</text>

      {/* x axis */}
      <line class="qw-axis" x1={CPAD.l} y1={CH - CPAD.b} x2={CW - CPAD.r} y2={CH - CPAD.b} />
      {xTicks.map((s) => (
        <text class="qw-tick2" key={`x${s}`} x={cx(s)} y={CH - CPAD.b + 13} text-anchor="middle">
          {s === 0 ? "0" : `${Math.round(s / 1000)}k`}
        </text>
      ))}
      <text class="qw-axtitle" x={CPAD.l} y={CH - 2}>env steps →</text>
      <text class="qw-axtitle" x={CPAD.l - 40} y={CPAD.t + 2}>fwd dist</text>

      {WALKS_AT != null && (
        <g>
          <line class="qw-walkmark" x1={cx(WALKS_AT)} y1={CPAD.t} x2={cx(WALKS_AT)} y2={CH - CPAD.b} />
          <text class="qw-walkmark-lbl" x={cx(WALKS_AT) + 3} y={CPAD.t + 9}>gait clears 0.5 m</text>
        </g>
      )}

      <polyline class="qw-curve" points={pts} />
      {CURVE.map((r, i) => (
        <circle class={`qw-cpt ${i === CURVE.length - 1 ? "qw-cpt--last" : ""}`} key={i} cx={cx(r[0]).toFixed(1)} cy={cy(r[2]).toFixed(1)} r={2.4} />
      ))}
    </svg>
  );
}

// ============================================================ distance ceiling bars
function CeilingBars() {
  const rows = [
    { name: "random", val: SUM.random_forward_dist, cls: "neg" },
    { name: "just stand", val: SUM.stand_forward_dist, cls: "stand" },
    { name: "scripted trot", val: SUM.scripted_trot_forward_dist, cls: "trot" },
    { name: "emergent gait", val: SUM.mean_eval_forward_dist, cls: "gait" },
  ];
  const lo = Math.min(...rows.map((r) => r.val), 0);
  const hi = Math.max(...rows.map((r) => r.val), 0);
  const range = hi - lo || 1;
  const frac = (v: number) => (v - lo) / range;
  const zero = frac(0);
  return (
    <div class="qw-bars" role="img"
      aria-label={
        `Forward-distance comparison. Random flailing ${SUM.random_forward_dist.toFixed(2)} metres, just standing ${SUM.stand_forward_dist.toFixed(2)}, ` +
        `the scripted trot ${SUM.scripted_trot_forward_dist.toFixed(2)}, and the emergent learned gait ${SUM.mean_eval_forward_dist.toFixed(2)} — ` +
        "the emergent gait travels the furthest, past the scripted trot."
      }>
      {rows.map((r) => {
        const f = frac(r.val);
        const left = Math.min(f, zero) * 100;
        const width = Math.abs(f - zero) * 100;
        return (
          <div class={`qw-bar-row qw-bar-row--${r.cls}`} key={r.name}>
            <span class="qw-bar-name">{r.name}</span>
            <span class="qw-bar-track">
              <span class="qw-bar-zero" style={`left:${(zero * 100).toFixed(1)}%`} />
              <span class={`qw-bar-fill qw-bar-fill--${r.cls}`} style={`left:${left.toFixed(1)}%;width:${Math.max(0.8, width).toFixed(1)}%`} />
            </span>
            <span class="qw-bar-val">{r.val >= 0 ? "+" : ""}{r.val.toFixed(2)}</span>
          </div>
        );
      })}
    </div>
  );
}

// -------------------------------------------------------------------------- the toy
const PLAY_MS = 4600; // one replay pass along the recorded frames

/** Representative static frame (SSR / reduced-motion): a clear mid-stride — the
 *  frame of peak forward speed while upright, in the first three-quarters of the
 *  episode (before any late faceplant). Deterministic, so SSR and hydration agree. */
const REPR_IDX = (() => {
  let best = Math.floor(N * 0.5), bestVx = -Infinity;
  for (let i = 0; i < Math.floor(N * 0.75); i++) {
    const f = FRAMES[i];
    const upright = f.torso[1] > GEO.fall_height;
    if (upright && f.vx > bestVx) { bestVx = f.vx; best = i; }
  }
  return best;
})();

export default function QuadrupedWalkToy() {
  // booted=false is the SSR / JS-off view: the static mid-stride frame + progress +
  // curve + ceiling, all shown. Hydration flips booted=true and enables the replay.
  const [booted, setBooted] = useState(false);
  const [idx, setIdx] = useState(REPR_IDX);
  const [playing, setPlaying] = useState(false);
  const reduced = useRef(false);
  const rafRef = useRef(0);

  useEffect(() => {
    setBooted(true);
    reduced.current =
      typeof matchMedia !== "undefined" && matchMedia("(prefers-reduced-motion: reduce)").matches;
  }, []);

  // the replay loop — advance idx 0→N-1 over PLAY_MS, then stop on the last frame.
  useEffect(() => {
    if (!playing) return;
    let start = 0;
    const tick = (t: number) => {
      if (!start) start = t;
      const f = Math.min(1, (t - start) / PLAY_MS);
      setIdx(Math.round(f * (N - 1)));
      if (f < 1) rafRef.current = requestAnimationFrame(tick);
      else setPlaying(false);
    };
    rafRef.current = requestAnimationFrame(tick);
    return () => cancelAnimationFrame(rafRef.current);
  }, [playing]);

  const play = () => {
    if (reduced.current) { setPlaying(false); setIdx(REPR_IDX); return; } // no animation
    cancelAnimationFrame(rafRef.current);
    setIdx(0);
    setPlaying(true);
  };
  const onScrub = (e: Event) => {
    cancelAnimationFrame(rafRef.current);
    setPlaying(false);
    setIdx(parseInt((e.currentTarget as HTMLInputElement).value, 10));
  };

  const f = FRAMES[Math.max(0, Math.min(N - 1, idx))];
  const distSoFar = f.torso[0] - FRAMES[0].torso[0];
  const maxDist = Math.max(GAIT.forward, SUM.scripted_trot_forward_dist, 0.2) * 1.06;
  const trotPct = (SUM.scripted_trot_forward_dist / maxDist) * 100;
  const fillPct = Math.max(0, Math.min(100, (distSoFar / maxDist) * 100));

  // aria-live: the gait outcome + the honest ceiling — never per-frame spam.
  const live =
    `The learned quadruped gait walks forward ${m2(GAIT.forward).trim()} in the hero episode. ` +
    `Over the held-out evaluation it averages ${m2(SUM.mean_eval_forward_dist).trim()} — further than the scripted trot's ${m2(SUM.scripted_trot_forward_dist).trim()} — ` +
    `but it falls after about ${Math.round(SUM.mean_eval_length)} of ${SUM.horizon_steps} steps, so its return ${SUM.mean_eval_return.toFixed(0)} stays below the trot's ${SUM.scripted_trot_return.toFixed(0)}. ` +
    "The gait emerges from the reward alone; a full, robust trot is the Scale Lab.";

  return (
    <div class="qw">
      {/* PANEL 1 — the quadruped walking (recorded side-view replay) */}
      <section class="qw-panel">
        <header class="qw-head">
          <h3 class="qw-title">The quadruped walks — a gait nobody scripted</h3>
          <p class="qw-sub">
            SAC maximised the ch2.4 reward and a <b>forward stride emerged</b>. This is the
            deterministic hero episode: the camera follows the torso, so the scrolling ground and
            the progress bar read the <b>travel</b>.
          </p>
        </header>

        <svg class="qw-stage" viewBox={`0 0 ${AW} ${AH}`} role="img"
          aria-label={
            `Side view of a four-legged robot mid-stride, walking to the right across a ground marked in metres. ` +
            `The learned policy drives the torso forward; the near legs are solid, the far legs faded for depth. ` +
            `In this recorded episode the torso travels ${GAIT.forward.toFixed(2)} metres before it falls.`
          }>
          <g class="qw-grid">
            {[0.25, 0.5, 0.75, 1].map((fr) => (
              <line key={fr} x1={0} y1={FLOOR_Y * fr} x2={AW} y2={FLOOR_Y * fr} />
            ))}
          </g>
          <Ground camX={f.torso[0]} />
          <Robot f={f} />
        </svg>

        {/* forward-progress track (renders statically; the fill tracks the frame) */}
        <div class="qw-track-wrap">
          <div class="qw-track">
            <div class="qw-track-fill" style={`width:${fillPct.toFixed(1)}%`} />
            <div class="qw-track-trot" style={`left:${trotPct.toFixed(1)}%`} />
          </div>
          <div class="qw-track-lbl">
            <span>forward progress <b>{m2(distSoFar).trim()}</b></span>
            <span>hero episode reaches {m2(GAIT.forward).trim()}</span>
          </div>
        </div>

        {/* foot-contact gait strip — the periodic stride */}
        <ContactStrip headIdx={idx} />

        {/* controls — JS-only enhancement (SSR ships the static mid-stride view) */}
        <div class="qw-controls">
          <button type="button" class="qw-btn qw-btn--primary" onClick={play} disabled={!booted}>
            {playing ? "▶ walking…" : "▶ replay the gait"}
          </button>
          <input
            class="qw-scrub" type="range" min={0} max={N - 1} step={1} value={idx}
            onInput={onScrub} disabled={!booted}
            aria-label="Scrub the recorded gait frame by frame. Each step advances the walking robot; watch the torso travel forward and the feet alternate stance and swing."
            aria-valuetext={`frame ${idx + 1} of ${N}, forward ${distSoFar.toFixed(2)} metres`}
          />
          <span class="qw-control-note">recorded rollout · poster reads with JS off</span>
        </div>
      </section>

      {/* PANEL 2 — forward progress over training */}
      <section class="qw-panel">
        <header class="qw-head">
          <h3 class="qw-title">The walk taking shape</h3>
          <p class="qw-sub">
            Held-out forward distance over training. It climbs off the <b>just-stand</b> floor and
            crosses the <b>scripted-trot</b> line — the gait emerging, step by step. Reinforcement
            learning is <b>non-monotonic</b>: the curve wobbles as it improves.
          </p>
        </header>
        <TrainingCurve />
      </section>

      {/* PANEL 3 — the honest free-tier ceiling */}
      <section class="qw-panel">
        <header class="qw-head">
          <h3 class="qw-title">The honest free-tier ceiling</h3>
          <p class="qw-sub">
            Forward distance across the baselines — the emergent gait travels the <b>furthest</b>.
            But distance is not the whole story.
          </p>
        </header>
        <CeilingBars />
        <div class="qw-caveat">
          <span class="qw-caveat-h">further, but not yet robust</span>
          <p style="margin:0">
            The emergent gait <b class="qw-good">beats the trot on distance</b>
            {" "}({m2(SUM.mean_eval_forward_dist).trim()} vs {m2(SUM.scripted_trot_forward_dist).trim()}), yet it
            {" "}<b class="qw-bad">falls after ~{Math.round(SUM.mean_eval_length)} of {SUM.horizon_steps} steps</b> —
            it sprints, then topples. So its <b class="qw-bad">return {SUM.mean_eval_return.toFixed(0)}</b> sits
            {" "}below the <b class="qw-trot">trot's {SUM.scripted_trot_return.toFixed(0)}</b>. Emergence is
            {" "}the lesson; <b>emergent ≠ robust</b> at a CPU-laptop budget. A full, stable trot wants far more
            {" "}env steps on a GPU — that is the Scale Lab.
          </p>
        </div>
        <p class="qw-note">
          Real recorded gait + training curve from <b>walk.py</b> (seed 0, cpu, {viz.provenance.total_steps.toLocaleString()} steps);
          {" "}matches meta.yaml reference_run. Poster reads with JS off.
        </p>
      </section>

      {/* screen-reader live region — the gait outcome + the standing ceiling */}
      <p class="qw-sr" aria-live="polite">{booted ? live : ""}</p>
    </div>
  );
}
