/**
 * RewardHackToy — ch2.4 "Reward Design Is Programming" concept-toy
 * (demo id `quadruped_reward_hack`). THE MAP'S NAMED HERO: specification gaming,
 * made into one figure. Same quadruped, same from-scratch PPO, two reward PROGRAMS
 * — and the policy does exactly what you SAID, not what you MEANT.
 *
 * THREE panels:
 *   (1) SIDE-BY-SIDE recorded rollouts. The SHAPED reward → a forward WALK (the
 *       torso travels +x; the ground scrolls past). The HACK reward (reward raw
 *       torso height) → the robot REARS TALL and stalls, covering ~0 forward. The
 *       "did what you SAID, not what you MEANT" visual, on real seed-0 physics.
 *   (2) THE MISMATCH (the headline). The hack's own self-reward CLIMBS ~10×
 *       (105 → 1048) over training while its FORWARD DISTANCE stays a tiny
 *       fraction (−0.18 m) of the shaped +4.6 m walk. Reward up, task not done.
 *   (3) SHAPING / CURRICULUM context — forward distance per reward design: sparse
 *       barely moves, dense shaped walks, the hack goes nowhere, staging the reward
 *       (stand first, then forward) walks furthest.
 *
 * Like the ch3.3 / ch3.6 recorded toys this needs NO WASM: it renders REAL seed-0
 * rollout geometry + the REAL reward rise-curve from rewards.py, regenerated by
 * site/scripts/vizdata/ch2.4_rewards.py into the co-located vizdata.json. HONESTY
 * (see that file's `provenance`): env resets are bitwise-reproducible on CPU but
 * PPO *training* is only statistically reproducible, so every DISPLAYED number is
 * meta.yaml's cited reference_run; the geometry + curve SHAPE are a real seed-0
 * run, verified to reproduce meta's seed-robust signatures. So it is pure SVG +
 * design tokens: theme-aware for free, and the server-rendered default (rollouts
 * at their end pose + the full curve + the bars) IS the JS-off experience — only
 * the replay animation needs hydration. Colour by MEANING: the HACK is the
 * cautionary exploit → --alert red everywhere; the SHAPED walk is the behaviour
 * you wanted → --entity-target green everywhere.
 *
 * Follows the FROZEN CONCEPT-TOY CONTRACT documented at the top of ../PlateIsland.tsx.
 */
import "./RewardHackToy.css";
import { useEffect, useRef, useState } from "preact/hooks";
// Real seed-0 rollouts + reward rise-curve from rewards.py — see the file's
// `provenance` and the generator site/scripts/vizdata/ch2.4_rewards.py. Committed
// small text, no binary.
import viz from "../../../../curriculum/phase2_reinforcement/ch2.4_rewards/demo/vizdata.json";

// ---------------------------------------------------------------- typed vizdata
type Pt = number[]; // [x, z]
interface Frame {
  c: number[]; // [cx, cz, pitch]
  f: Pt[]; // front leg [hip, knee, foot]
  h: Pt[]; // hind leg  [hip, knee, foot]
}
interface Roll {
  x0: number;
  forward: number;
  steps: number;
  frames: Frame[];
}
interface Meta {
  shaped_forward_m: number;
  sparse_forward_m: number;
  hack_forward_m: number;
  hack_height_m: number;
  hack_return_first: number;
  hack_return_last: number;
  curriculum_forward_m: number;
}
interface Shaping {
  design: string;
  forward_m: number;
  note: string;
}

const GEOM = viz.geom as {
  torso_half: number[];
  leg_radius: number;
  foot_radius: number;
  floor_z: number;
  target_height: number;
  fall_height: number;
};
const META = viz.meta as Meta;
const SHAPED = viz.rollouts.shaped as Roll;
const HACK = viz.rollouts.hack as Roll;
const CURVE = viz.hack_return_curve as number[][]; // [progress, design_return]
const SHAPING = viz.shaping as Shaping[];

const HACK_RISE = META.hack_return_last / META.hack_return_first; // ~10×

// ------------------------------------------------------- side-view arena geometry
// A camera-follows-torso side view (x-z plane). The robot is drawn torso-centred
// (world x minus the torso's current x), so the SHAPED walk reads as the ground
// scrolling past, and the HACK reads as the torso rearing UP while the ground
// stays put. Uniform metres→px scale preserves the robot's proportions.
const AV_W = 300;
const AV_H = 208;
const WIN_HALF_X = 0.62; // metres visible either side of the torso
const S = AV_W / (2 * WIN_HALF_X); // px per metre (uniform)
const FLOOR_PY = AV_H - 26; // screen y of the floor (z = 0)
const zToPy = (z: number): number => FLOOR_PY - z * S;
const xLocalToPx = (worldX: number, cx: number): number => AV_W / 2 + (worldX - cx) * S;

const [THX, THZ] = GEOM.torso_half; // torso box half-extents (x, z)

/** One recorded rollout, side view, drawn up to frame `upto`. */
function RolloutArena({
  roll,
  upto,
  tone,
  title,
  subtitle,
  ariaLabel,
}: {
  roll: Roll;
  upto: number;
  tone: "shaped" | "hack";
  title: string;
  subtitle: string;
  ariaLabel: string;
}) {
  const fr = roll.frames[Math.min(upto, roll.frames.length - 1)];
  const [cx, cz, pitch] = fr.c;
  const cxScreen = AV_W / 2;
  const czPy = zToPy(cz);

  // torso box corners: centre + u·body-x + w·body-z, rotated by pitch in x-z.
  const cos = Math.cos(pitch), sin = Math.sin(pitch);
  const corner = (u: number, w: number): string => {
    const dx = u * cos - w * sin;
    const dz = u * sin + w * cos;
    return `${(cxScreen + dx * S).toFixed(1)},${(czPy - dz * S).toFixed(1)}`;
  };
  const box = [corner(-THX, -THZ), corner(THX, -THZ), corner(THX, THZ), corner(-THX, THZ)].join(" ");

  // a leg as hip→knee→foot in torso-local screen space
  const legPts = (leg: Pt[]): { line: string; foot: [number, number] } => {
    const p = leg.map(([x, z]) => [xLocalToPx(x, cx), zToPy(z)] as [number, number]);
    return { line: p.map(([x, y]) => `${x.toFixed(1)},${y.toFixed(1)}`).join(" "), foot: p[2] };
  };
  const front = legPts(fr.f);
  const hind = legPts(fr.h);

  // Scrolling ground marks every 0.25 m of world x within the window. UNLABELLED
  // by design: they convey MOTION (the shaped walker sends them streaming past, the
  // hack leaves them still) without printing a per-run distance that would fight the
  // cited meta numbers in the panels below. The quantitative story lives there.
  const ticks: number[] = [];
  const first = Math.ceil((cx - WIN_HALF_X) / 0.25) * 0.25;
  for (let m = first; m <= cx + WIN_HALF_X + 1e-6; m += 0.25) {
    ticks.push(xLocalToPx(m, cx));
  }

  const rideY = zToPy(GEOM.target_height); // the nominal ride-height reference

  return (
    <figure class={`rh-arena rh-arena--${tone}`}>
      <svg class="rh-svg" viewBox={`0 0 ${AV_W} ${AV_H}`} role="img" aria-label={ariaLabel}>
        {/* ride-height reference (where a level torso holds) */}
        <line class="rh-ride" x1={0} y1={rideY} x2={AV_W} y2={rideY} />
        <text class="rh-ride-lab" x={AV_W - 4} y={rideY - 3} text-anchor="end">ride height</text>

        {/* floor + scrolling ground marks (the "am I going anywhere?" cue) */}
        <line class="rh-floor" x1={0} y1={FLOOR_PY} x2={AV_W} y2={FLOOR_PY} />
        {ticks.map((px) => (
          <line class="rh-tickmark" x1={px} y1={FLOOR_PY + 1} x2={px} y2={FLOOR_PY + 7} />
        ))}

        {/* legs (behind the torso) */}
        <polyline class="rh-leg" points={hind.line} />
        <polyline class="rh-leg" points={front.line} />
        <circle class="rh-foot" cx={hind.foot[0].toFixed(1)} cy={hind.foot[1].toFixed(1)} r={GEOM.foot_radius * S} />
        <circle class="rh-foot" cx={front.foot[0].toFixed(1)} cy={front.foot[1].toFixed(1)} r={GEOM.foot_radius * S} />

        {/* the torso box — the hero, in this design's tone */}
        <polygon class="rh-torso" points={box} />
      </svg>
      <figcaption class="rh-arena-cap">
        <span class="rh-arena-name">{title}</span>
        <span class={`rh-arena-tag rh-tag--${tone}`}>{subtitle}</span>
      </figcaption>
    </figure>
  );
}

// ================================================================= MISMATCH PANEL
// The hero chart: the hack's self-reward CLIMBS (real curve shape, cited 105→1048
// band) while its forward distance stays pinned near zero — a fraction of the
// shaped walk. Two y-scales, one x-axis (training progress): left = self-reward
// (red, the number the hack optimises), right = forward distance (metres).
const CW = 480;
const CH = 236;
const CPAD = { l: 52, r: 54, t: 18, b: 34 };
const CPW = CW - CPAD.l - CPAD.r;
const CPH = CH - CPAD.t - CPAD.b;

function MismatchPanel() {
  const rMax = META.hack_return_last * 1.06;
  const fMax = Math.max(META.shaped_forward_m, 1) * 1.15; // forward axis holds the shaped walk
  const px = (p: number): number => CPAD.l + p * CPW;
  const pyR = (v: number): number => CPAD.t + (1 - v / rMax) * CPH;
  const pyF = (m: number): number => CPAD.t + (1 - m / fMax) * CPH;

  const rewardLine = CURVE.map(([p, v]) => `${px(p).toFixed(1)},${pyR(v).toFixed(1)}`).join(" ");
  const yFloor = CPAD.t + CPH;

  // the forward line stays near zero across training (hack never walks); its end
  // value is meta's measured −0.18 m. Drawn as the flat "task not done" trace.
  const fwdY = pyF(Math.max(0, META.hack_forward_m));
  const shapedY = pyF(META.shaped_forward_m);

  const rTicks = [0, 0.25, 0.5, 0.75, 1].map((f) => Math.round(rMax * f));
  return (
    <svg
      class="rh-chart"
      viewBox={`0 0 ${CW} ${CH}`}
      role="img"
      aria-label={
        `Training chart, x-axis training progress. The hack's own self-reward climbs from ` +
        `${META.hack_return_first} to ${META.hack_return_last}, about ${HACK_RISE.toFixed(0)} times, ` +
        `while its forward distance stays near zero — measured ${META.hack_forward_m} metres, a small ` +
        `fraction of the shaped policy's ${META.shaped_forward_m} metre walk. Reward up, task not done.`
      }
    >
      {/* left axis: self-reward */}
      <line class="rh-axis" x1={CPAD.l} y1={CPAD.t} x2={CPAD.l} y2={yFloor} />
      {rTicks.map((v) => (
        <g>
          <line class="rh-grid" x1={CPAD.l} y1={pyR(v)} x2={CW - CPAD.r} y2={pyR(v)} />
          <text class="rh-tick rh-tick--reward" x={CPAD.l - 6} y={pyR(v) + 3} text-anchor="end">{v}</text>
        </g>
      ))}
      <text class="rh-axtitle rh-axtitle--reward" x={CPAD.l} y={CPAD.t - 6} text-anchor="start">
        hack self-reward ▲
      </text>

      {/* right axis: forward distance (m) */}
      <line class="rh-axis" x1={CW - CPAD.r} y1={CPAD.t} x2={CW - CPAD.r} y2={yFloor} />
      {[0, 1, 2, 3, 4].filter((m) => m <= fMax).map((m) => (
        <text class="rh-tick rh-tick--fwd" x={CW - CPAD.r + 6} y={pyF(m) + 3} text-anchor="start">{m}m</text>
      ))}
      <text class="rh-axtitle rh-axtitle--fwd" x={CW - CPAD.r} y={CPAD.t - 6} text-anchor="end">
        forward dist
      </text>

      {/* x axis */}
      <line class="rh-axis" x1={CPAD.l} y1={yFloor} x2={CW - CPAD.r} y2={yFloor} />
      {[0, 0.5, 1].map((p) => (
        <text class="rh-tick" x={px(p)} y={yFloor + 15} text-anchor="middle">
          {p === 0 ? "start" : p === 1 ? "end" : "training →"}
        </text>
      ))}

      {/* the shaped walk reference (what forward SHOULD reach) */}
      <line class="rh-shaped-ref" x1={CPAD.l} y1={shapedY} x2={CW - CPAD.r} y2={shapedY} />
      <text class="rh-shaped-lab" x={CW - CPAD.r - 4} y={shapedY - 4} text-anchor="end">
        shaped walk +{META.shaped_forward_m}m
      </text>

      {/* forward stays near zero the whole time (task not done) */}
      <line class="rh-fwd-line" x1={CPAD.l} y1={fwdY} x2={CW - CPAD.r} y2={fwdY} />
      <circle class="rh-fwd-dot" cx={CW - CPAD.r} cy={fwdY} r={4} />
      <text class="rh-fwd-lab" x={CW - CPAD.r - 4} y={fwdY + 15} text-anchor="end">
        hack forward {META.hack_forward_m}m
      </text>

      {/* the hero: self-reward climbing */}
      <polyline class="rh-reward-line" points={rewardLine} />
      <circle class="rh-reward-dot" cx={px(1)} cy={pyR(META.hack_return_last)} r={4} />
    </svg>
  );
}

// ================================================================= SHAPING PANEL
// Forward distance per reward design (cited meta numbers): sparse barely moves,
// dense shaped walks, the hack goes nowhere, curriculum (staged) walks furthest.
function ShapingPanel() {
  const maxAbs = Math.max(...SHAPING.map((s) => Math.abs(s.forward_m)), 1);
  return (
    <div class="rh-bars">
      {SHAPING.map((s) => {
        const isHack = s.design === "hack";
        const isWalk = s.design === "shaped" || s.design === "curriculum";
        const tone = isHack ? "hack" : isWalk ? "walk" : "muted";
        const pctW = (Math.abs(s.forward_m) / maxAbs) * 100;
        return (
          <div class="rh-bar-row">
            <span class="rh-bar-name">{s.design}</span>
            <div class="rh-bar-track">
              <div class={`rh-bar-fill rh-bar--${tone}`} style={`width:${pctW.toFixed(1)}%`} />
            </div>
            <span class={`rh-bar-val rh-val--${tone}`}>
              {s.forward_m >= 0 ? "+" : ""}{s.forward_m.toFixed(2)} m
            </span>
          </div>
        );
      })}
      <p class="rh-bars-note">
        forward distance walked per reward <b>program</b> — same robot, same PPO. sparse barely
        moves; the dense shaped reward learns a walk; the height <b class="rh-ink-hack">hack</b> goes
        nowhere; staging the reward (stand first, then forward) walks furthest.
      </p>
    </div>
  );
}

// ==================================================================== THE ISLAND
const PLAY_MS = 4600;

export default function RewardHackToy() {
  // booted=false is the SSR / JS-off view: both rollouts at their END pose + the
  // full curve + the bars, all shown. Hydration flips booted=true and enables the
  // replay animation.
  const [booted, setBooted] = useState(false);
  const [frac, setFrac] = useState(1); // 0..1 along the rollouts; 1 = end pose
  const [playing, setPlaying] = useState(false);
  const reduced = useRef(false);
  const rafRef = useRef(0);

  useEffect(() => {
    setBooted(true);
    reduced.current =
      typeof matchMedia !== "undefined" && matchMedia("(prefers-reduced-motion: reduce)").matches;
  }, []);

  // replay loop — advance frac 0→1 over PLAY_MS, then rest at the end pose.
  useEffect(() => {
    if (!playing) return;
    let start = 0;
    const tick = (t: number) => {
      if (!start) start = t;
      const f = Math.min(1, (t - start) / PLAY_MS);
      setFrac(f);
      if (f < 1) rafRef.current = requestAnimationFrame(tick);
      else setPlaying(false);
    };
    rafRef.current = requestAnimationFrame(tick);
    return () => cancelAnimationFrame(rafRef.current);
  }, [playing]);

  const play = () => {
    if (reduced.current) { setFrac(1); return; } // reduced-motion: jump to the end
    setFrac(0);
    setPlaying(true);
  };

  const shapedUpto = Math.round(frac * (SHAPED.frames.length - 1));
  const hackUpto = Math.round(frac * (HACK.frames.length - 1));

  const liveSummary =
    `Same quadruped, same PPO, two reward programs. The shaped reward walks the torso forward ` +
    `${META.shaped_forward_m} metres. The hack reward — reward raw torso height — makes the robot ` +
    `rear tall and stall: its own self-reward climbs about ${HACK_RISE.toFixed(0)} times ` +
    `(${META.hack_return_first} to ${META.hack_return_last}) while forward distance stays ` +
    `${META.hack_forward_m} metres, a small fraction of the shaped walk. The policy did what you ` +
    `said — get tall — not what you meant — go forward.`;

  return (
    <div class="rh">
      {/* PANEL 1 — the two recorded rollouts, side by side */}
      <section class="rh-panel rh-panel--replay">
        <header class="rh-head">
          <h3 class="rh-title">Did what you said, not what you meant</h3>
          <p class="rh-sub">
            One quadruped, one from-scratch PPO, <b>two reward programs</b>. The
            <b class="rh-ink-shaped"> shaped</b> reward walks it forward; the
            <b class="rh-ink-hack"> hack</b> (reward raw torso height) rears it tall and stalls.
          </p>
        </header>
        <div class="rh-arenas">
          <RolloutArena
            roll={SHAPED}
            upto={shapedUpto}
            tone="shaped"
            title="shaped reward"
            subtitle={`walks · +${META.shaped_forward_m} m`}
            ariaLabel={
              "Side view of the quadruped under the shaped reward. The torso, camera-centred, holds its " +
              "ride height and walks forward while the ground marks stream past — it covers ground."
            }
          />
          <RolloutArena
            roll={HACK}
            upto={hackUpto}
            tone="hack"
            title="height-hack reward"
            subtitle={`rears · ${META.hack_forward_m} m`}
            ariaLabel={
              "Side view of the SAME quadruped under the height-hack reward. The torso rears up above its " +
              "ride height and stalls; the ground marks barely move — it covers almost no forward distance."
            }
          />
        </div>
        <div class="rh-controls">
          <button type="button" class="rh-btn rh-btn--primary" onClick={play} disabled={!booted}>
            {playing ? "▶ playing…" : "▶ replay both"}
          </button>
          <span class="rh-control-note">recorded seed-0 rollouts · poster reads with JS off</span>
        </div>
        <p class="rh-why-line">
          Both were trained by the identical PPO to <b>maximise a number</b>. The only difference is
          the reward <b>program</b> — and it is the whole difference between a walk and a stall.
        </p>
      </section>

      {/* PANEL 2 — the mismatch (the headline) */}
      <section class="rh-panel rh-panel--mismatch">
        <header class="rh-head">
          <h3 class="rh-title">Reward up, task not done</h3>
          <p class="rh-sub">
            The hack&rsquo;s <b class="rh-ink-hack">own reward</b> climbs ~{HACK_RISE.toFixed(0)}×
            over training while its <b class="rh-ink-shaped">forward distance</b> stays a tiny
            fraction of the shaped walk. That gap is the reward hack.
          </p>
        </header>
        <MismatchPanel />
        <div class="rh-verdict" aria-hidden="true">
          <span class="rh-verdict-tag">specification gaming</span>
          <span>
            self-reward <b class="rh-ink-hack">{META.hack_return_first} → {META.hack_return_last}</b>{" "}
            (~{HACK_RISE.toFixed(0)}×), forward distance{" "}
            <b class="rh-ink-hack">{META.hack_forward_m} m</b> vs the shaped{" "}
            <b class="rh-ink-shaped">+{META.shaped_forward_m} m</b> walk. The reward <em>is</em>{" "}
            optimised — it was just the wrong reward.
          </span>
        </div>
      </section>

      {/* PANEL 3 — shaping / curriculum context */}
      <section class="rh-panel rh-panel--shaping">
        <header class="rh-head">
          <h3 class="rh-title">The reward is the program</h3>
        </header>
        <ShapingPanel />
      </section>

      {/* honest-scope note */}
      <p class="rh-note">
        Real seed-0 rollouts + reward curve from <b>rewards.py</b>; the displayed numbers are
        meta.yaml&rsquo;s measured reference run. Env resets are bitwise-reproducible on CPU, but PPO
        training is only <b>statistically</b> reproducible — a fresh seed-0 run reproduces the
        <b> signatures</b> (reward rises, forward stays tiny), not the exact magnitudes. This
        free-tier quadruped is a cartoon 2-DOF/leg robot: the lesson is the reward-vs-behaviour
        <b> mismatch</b>, not a transferable gait.
      </p>

      {/* screen-reader live region — the qualitative mismatch, never per-frame spam */}
      <p class="rh-sr" aria-live="polite">{booted ? liveSummary : ""}</p>
    </div>
  );
}
