/**
 * ch2.8 "Concepts of ROS, Without ROS" — the PUB-SUB RUNTIME GRAPH concept-toy
 * (`demo: cartpole_runtime_graph`). A recorded-data sibling of ch2.6's latency-
 * degrade and ch3.3's engine-drift 2D toys: ROS's ideas made visible, WITHOUT ROS.
 * No WASM — pure SVG over REAL recorded runs of runtime.py's virtual-clock scheduler.
 *
 * THE HERO IS A KNOB, not a scrub. The chapter teaches TWO measured, graded facts
 * (meta.yaml exercise_checks) and this toy makes each one draggable:
 *
 *   1. THE CONTROL-RATE CLIFF (ex1) — the PRIMARY control, a RATE SLIDER, walks
 *      control_hz down through the measured sweep {50,25,20,15,10,5}. The same graph,
 *      the same brain, only the policy's rate changes. The pole BALANCES the whole
 *      501-step run at every rate >= 10 Hz and FALLS off the cliff at 5 Hz; the
 *      /obs drop count and the sense->act latency climb as the rate drops. Drag it
 *      down and watch the pole topple — meta.yaml:24's promised hero, finally real.
 *   2. QUEUE-DEPTH vs RATE (ex2) — a QUEUE-DEPTH TOGGLE (latest-wins depth-1 vs a
 *      deep depth-100 buffer). A deeper buffer drives obs_dropped -> 0 at every rate,
 *      yet the trajectory is BYTE-IDENTICAL (the policy always reads the LATEST msg,
 *      so the buffer changes only the drop COUNT). At the 5 Hz cliff that is the
 *      punchline: the dropped-message symptom vanishes, but the pole STILL falls at
 *      the SAME step. Throughput != control — the RATE is the killer, not the queue.
 *
 * THREE panels: the pub-sub NODE GRAPH (headline — the policy node's Hz + the two
 * topics' live rate/drop counts track the selection), the CARTPOLE it drives
 * (recorded replay of the selected run — balances or topples), and a NOTE that
 * carries the verdict + the determinism story (virtual clock => byte-reproducible).
 *
 * Data: REAL recorded runs from runtime.py's OWN build_graph + run_virtual (seed 0,
 * --clock virtual, scripted checkpoint-free balancer), regenerated by
 * site/scripts/vizdata/ch2.8_runtime.py into the co-located vizdata.json and gated
 * against meta.yaml exercise_checks (STOP on drift). So it is pure SVG + design
 * tokens: theme-aware for free, and the server-rendered default (50 Hz, balanced,
 * frame 0) IS the JS-off experience — only the slider/toggle/replay go inert without
 * hydration. Colour by MEANING: the flowing message = --signal blue, the firing node
 * = --signal, a healthy topic / balanced verdict = --entity-target green, a dropped
 * count / the fall cone / a FELL verdict = --alert red, the pole = --entity-pusher.
 */
import "./RuntimeGraphToy.css";
import { useEffect, useMemo, useRef, useState } from "preact/hooks";
// Real recorded runs from runtime.py, seed 0, --clock virtual — see the file's
// `provenance` and the generator site/scripts/vizdata/ch2.8_runtime.py. Committed
// small text (~52 KB: six recorded rollouts), no binary.
import viz from "../../../../curriculum/phase2_reinforcement/ch2.8_runtime/demo/vizdata.json";

// ---------------------------------------------------------------- typed vizdata
interface GraphNode { id: string; label: string; role: string; hz: number; priority: number; }
interface GraphTopic { id: string; from: string; to: string; }
interface SweepRun {
  control_hz: number; balanced: boolean; steps: number; fell_at_step: number | null;
  sim_time_s: number; obs_published: number; action_published: number;
  obs_dropped_shallow: number; obs_dropped_deep: number; action_dropped: number;
  obs_rate: number; action_rate: number; mean_latency_ms: number;
  cart_x: number[]; pole_angle: number[];
}
interface QueueDepth {
  control_hz: number; shallow_depth: number; deep_depth: number;
  obs_dropped_shallow: number; obs_dropped_deep: number;
  balanced: boolean; fell_at_step: number | null; mean_latency_ms: number;
}

const NODES = viz.graph.nodes as GraphNode[];
const TOPICS = viz.graph.topics as GraphTopic[];
const CLOCK = viz.clock as {
  kind: string; period_s: number; sim_time_s: number; sensor_hz: number;
  actuator_hz: number; tick_order: string[]; reproducible: boolean;
};
const CART = viz.cartpole as { dt_s: number; angle_limit_rad: number; cart_limit_m: number; pole_len_m: number; };
const SWEEP = viz.control_rate_sweep as {
  knob: string; sensor_hz: number; actuator_hz: number;
  balances_at_hz: number; falls_at_hz: number; default_hz: number; runs: SweepRun[];
};
const QUEUE = viz.queue_depth as QueueDepth;
const RUNS = SWEEP.runs;                 // ordered high -> low rate: [50,25,20,15,10,5]
const N_RATES = RUNS.length;
const SENSOR_HZ = SWEEP.sensor_hz;

// ------------------------------------------------------------ number formatting
const fmtDeg = (rad: number) => `${rad >= 0 ? "+" : "−"}${Math.abs((rad * 180) / Math.PI).toFixed(1)}°`;
const fmtHz = (hz: number) => (Number.isInteger(hz) ? `${hz}` : hz.toFixed(0));

/** /obs drops at a selection: deep queue absorbs the burst (-> 0), shallow drops. */
const obsDroppedOf = (run: SweepRun, deep: boolean) =>
  deep ? run.obs_dropped_deep : run.obs_dropped_shallow;

// ============================================================ NODE-GRAPH PANEL
// A fixed three-node row: sensor -> policy -> actuator, wired by /obs then /action.
const GW = 540, GH = 196;
const NODE_W = 118, NODE_H = 62;
const NODE_Y = 72;                       // top of the node boxes
const NODE_CY = NODE_Y + NODE_H / 2;
const NODE_CX: Record<string, number> = { sensor: 92, policy: 270, actuator: 448 };
const nodeRight = (id: string) => NODE_CX[id] + NODE_W / 2;
const nodeLeft = (id: string) => NODE_CX[id] - NODE_W / 2;

// each topic edge runs from the right of `from` to the left of `to`, along NODE_CY
const EDGE = TOPICS.map((t) => ({
  topic: t,
  x1: nodeRight(t.from) + 3, y1: NODE_CY,
  x2: nodeLeft(t.to) - 9, y2: NODE_CY, // leave room for the arrowhead
}));

/** Gaussian bump: how "lit" a node is when the pulse phase p (0..1) is near `at`. */
function litAt(p: number, at: number): number {
  let d = Math.abs(p - at);
  d = Math.min(d, 1 - d);          // wrap-around distance on the cycle
  return Math.max(0, 1 - d / 0.16);
}

interface GraphRefs {
  obsDot: { current: SVGCircleElement | null };
  actionDot: { current: SVGCircleElement | null };
  haloById: Record<string, { current: SVGRectElement | null }>;
}

/** The graph's live per-topic stats, recomputed on each (rate, queue) selection. */
interface TopicStat { rate: number; dropped: number; }

function NodeGraphPanel(
  { controlHz, obsStat, actionStat, onRefs }:
  { controlHz: number; obsStat: TopicStat; actionStat: TopicStat; onRefs: (r: GraphRefs) => void },
) {
  const obsDot = useRef<SVGCircleElement>(null);
  const actionDot = useRef<SVGCircleElement>(null);
  const sensorHalo = useRef<SVGRectElement>(null);
  const policyHalo = useRef<SVGRectElement>(null);
  const actuatorHalo = useRef<SVGRectElement>(null);
  const haloById: Record<string, typeof sensorHalo> = {
    sensor: sensorHalo, policy: policyHalo, actuator: actuatorHalo,
  };

  useEffect(() => { onRefs({ obsDot, actionDot, haloById }); }, []);

  // per-node display Hz: sensor + actuator fixed at the plant rate; the POLICY node
  // is the knob — it runs at the selected control_hz.
  const hzOf = (id: string) => (id === "policy" ? controlHz : SENSOR_HZ);
  const statOf = (topicId: string): TopicStat => (topicId === "/obs" ? obsStat : actionStat);

  return (
    <svg
      class="rg-svg rg-graph-svg"
      viewBox={`0 0 ${GW} ${GH}`}
      role="img"
      aria-label={
        "The pub-sub node graph the chapter builds, without ROS: three decoupled nodes — sensor, policy, actuator — " +
        "wired left to right by two named topics. The sensor publishes the plant state on /obs at 50 hertz; the policy " +
        `reads /obs, runs the balancer, and publishes a command on /action at the selected control rate of ${fmtHz(controlHz)} hertz; ` +
        `the actuator reads /action and steps the plant. Right now /obs is carrying ${obsStat.rate.toFixed(1)} messages per second ` +
        `with ${obsStat.dropped} dropped, and /action ${actionStat.rate.toFixed(1)} per second.`
      }
    >
      <defs>
        <marker id="rg-arrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse">
          <path class="rg-arrowhead" d="M 0 1 L 9 5 L 0 9 z" />
        </marker>
      </defs>

      <text class="rg-panel-tag" x={12} y={20}>the graph, ticking on the virtual clock</text>

      {/* topic edges (arrows) + their live labels */}
      {EDGE.map(({ topic, x1, y1, x2, y2 }) => {
        const st = statOf(topic.id);
        return (
          <g>
            <line class="rg-edge" x1={x1} y1={y1} x2={x2} y2={y2} marker-end="url(#rg-arrow)" />
            <text class="rg-topic" x={(x1 + x2) / 2} y={y1 - 12} text-anchor="middle">{topic.id}</text>
            <text class="rg-topic-meta" x={(x1 + x2) / 2} y={y1 + 22} text-anchor="middle">
              {st.rate.toFixed(1)} msg/s
            </text>
            <text
              class={`rg-topic-drop ${st.dropped > 0 ? "rg-drop-bad" : "rg-drop-ok"}`}
              x={(x1 + x2) / 2} y={y1 + 34} text-anchor="middle"
            >
              {st.dropped === 0 ? "0 dropped ✓" : `${st.dropped} dropped ▲`}
            </text>
          </g>
        );
      })}

      {/* the three node boxes */}
      {NODES.map((n) => {
        const c = NODE_CX[n.id];
        const x = c - NODE_W / 2;
        return (
          <g>
            {/* firing halo (opacity driven by the pulse) — sits under the box */}
            <rect
              ref={haloById[n.id]}
              class="rg-node-halo"
              x={x - 3} y={NODE_Y - 3} width={NODE_W + 6} height={NODE_H + 6} rx={9}
              style="opacity:0"
            />
            <rect class={`rg-node ${n.id === "policy" ? "rg-node-policy" : ""}`}
              x={x} y={NODE_Y} width={NODE_W} height={NODE_H} rx={7} />
            <text class="rg-node-name" x={c} y={NODE_Y + 24} text-anchor="middle">{n.label}</text>
            <text class="rg-node-role" x={c} y={NODE_Y + 39} text-anchor="middle">{n.role}</text>
            <text class={`rg-node-hz ${n.id === "policy" ? "rg-node-hz-knob" : ""}`}
              x={c} y={NODE_Y + 53} text-anchor="middle">{fmtHz(hzOf(n.id))} Hz</text>
          </g>
        );
      })}

      {/* the flowing messages — the one LIVE handle (signal blue). SSR/reduced-motion
          park them at each edge's midpoint so the static frame still reads "messages
          on the wire". */}
      {EDGE.map(({ x1, x2, y1 }, i) => (
        <circle
          ref={i === 0 ? obsDot : actionDot}
          class="rg-msg"
          cx={(x1 + x2) / 2} cy={y1} r={5}
        />
      ))}
    </svg>
  );
}

// ============================================================== CARTPOLE PANEL
const CW = 320, CH = 250;
const PX_PER_M = 148;                 // pole (1.0 m) = 148 px; ~1 m of rail either side is in-frame
const GROUND_Y = CH - 46;
const ORIGIN_X = CW / 2;
const cx = (wx: number) => ORIGIN_X + wx * PX_PER_M;
const CART_HALF_W_M = 0.16, CART_HALF_H_M = 0.075;
const POLE_PX = CART.pole_len_m * PX_PER_M;
const CART_W_PX = 2 * CART_HALF_W_M * PX_PER_M;
const CART_H_PX = 2 * CART_HALF_H_M * PX_PER_M;

// the +/-12 deg fall cone, drawn from the hinge (local coords, hinge at 0,0; up is -y)
const CONE_DX = Math.sin(CART.angle_limit_rad) * POLE_PX;
const CONE_DY = -Math.cos(CART.angle_limit_rad) * POLE_PX;

interface CartRefs {
  cartRef: { current: SVGGElement | null };
  poleRef: { current: SVGGElement | null };
}

function CartpolePanel(
  { run, frame0, fell, onRefs }:
  { run: SweepRun; frame0: number; fell: boolean; onRefs: (r: CartRefs) => void },
) {
  const cartRef = useRef<SVGGElement>(null);   // translates with the cart
  const poleRef = useRef<SVGGElement>(null);   // rotates about the hinge

  useEffect(() => { onRefs({ cartRef, poleRef }); }, []);

  const f = Math.min(frame0, run.cart_x.length - 1);
  const x0 = run.cart_x[f];
  const a0 = run.pole_angle[f];

  return (
    <svg
      class="rg-svg rg-cart-svg"
      viewBox={`0 0 ${CW} ${CH}`}
      role="img"
      aria-label={
        "Side view of the cartpole the node graph controls: a cart on a rail with a pole hinged upright. " +
        `This is a recorded replay of the graph run at a policy rate of ${fmtHz(run.control_hz)} hertz. ` +
        (fell
          ? `The policy is too slow: the pole leaves the plus-or-minus 12 degree fall cone and topples at control step ${run.steps}.`
          : "The pole stays deep inside the plus-or-minus 12 degree fall cone the whole run — the graph balances it.")
      }
    >
      <text class="rg-panel-tag" x={12} y={18}>the pole, driven by the graph</text>

      {/* rail */}
      <line class="rg-rail" x1={16} y1={GROUND_Y} x2={CW - 16} y2={GROUND_Y} />

      {/* cart group — translates horizontally by cart_x */}
      <g ref={cartRef} transform={`translate(${(cx(x0) - ORIGIN_X).toFixed(2)} 0)`}>
        {/* the fall cone (fixed to the hinge; faint, alert-tinted) */}
        <g transform={`translate(${ORIGIN_X} ${GROUND_Y})`}>
          <line class="rg-cone" x1={0} y1={0} x2={CONE_DX.toFixed(1)} y2={CONE_DY.toFixed(1)} />
          <line class="rg-cone" x1={0} y1={0} x2={(-CONE_DX).toFixed(1)} y2={CONE_DY.toFixed(1)} />
          <text class="rg-cone-lab" x={CONE_DX + 4} y={CONE_DY + 4}>fall limit ±12°</text>
        </g>

        {/* pole group — rotates about the hinge by the pole angle */}
        <g ref={poleRef} transform={`translate(${ORIGIN_X} ${GROUND_Y}) rotate(${((a0 * 180) / Math.PI).toFixed(2)})`}>
          <line class={`rg-pole ${fell ? "rg-pole-fell" : ""}`} x1={0} y1={0} x2={0} y2={(-POLE_PX).toFixed(1)} />
          <circle class={`rg-pole-bob ${fell ? "rg-pole-fell" : ""}`} cx={0} cy={(-POLE_PX).toFixed(1)} r={7} />
        </g>

        {/* the cart body straddling the rail */}
        <rect
          class="rg-cart"
          x={(ORIGIN_X - CART_W_PX / 2).toFixed(1)} y={(GROUND_Y - CART_H_PX / 2).toFixed(1)}
          width={CART_W_PX.toFixed(1)} height={CART_H_PX.toFixed(1)} rx={3}
        />
        <circle class="rg-hinge" cx={ORIGIN_X} cy={GROUND_Y} r={3.4} />
      </g>
    </svg>
  );
}

// ==================================================================== THE ISLAND
const PULSE_MS = 1150;                 // one visible message cycle (sensor -> policy -> actuator)
const REPLAY_STEPS_PER_S = 50;         // replay at the plant's real 50 Hz control rate
const FALL_HOLD_MS = 1200;             // hold the fallen frame before looping, so the topple reads

function prefersReduced(): boolean {
  return typeof window !== "undefined" && !!window.matchMedia
    && window.matchMedia("(prefers-reduced-motion: reduce)").matches;
}

function RuntimeGraph() {
  // Default selection = the healthy 50 Hz graph (rate index 0), shallow queue. This
  // is the server-rendered poster + the JS-off truth; the first drag is the aha.
  const DEFAULT_RATE_IDX = 0;
  const [rateIdx, setRateIdx] = useState(DEFAULT_RATE_IDX);
  const [deep, setDeep] = useState(false);
  const [reduce, setReduce] = useState(false);
  const [playing, setPlaying] = useState(true);
  const [frame, setFrame] = useState(0);      // throttled readout only (rAF drives the DOM directly)

  const run = RUNS[rateIdx];
  const nFrames = run.cart_x.length;
  const obsDropped = obsDroppedOf(run, deep);

  const graphRefs = useRef<GraphRefs | null>(null);
  const cartRefs = useRef<CartRefs | null>(null);
  const frameRef = useRef(0);
  const playingRef = useRef(true);
  const runRef = useRef<SweepRun>(run);       // rAF reads the CURRENT selection through refs
  runRef.current = run;

  const setCart = (fArg: number) => {
    const cr = cartRefs.current;
    if (!cr) return;
    const r = runRef.current;
    const fi = Math.max(0, Math.min(fArg, r.cart_x.length - 1));
    const x = r.cart_x[fi], a = r.pole_angle[fi];
    cr.cartRef.current?.setAttribute("transform", `translate(${(cx(x) - ORIGIN_X).toFixed(2)} 0)`);
    cr.poleRef.current?.setAttribute(
      "transform",
      `translate(${ORIGIN_X} ${GROUND_Y}) rotate(${((a * 180) / Math.PI).toFixed(2)})`,
    );
  };

  const setPulse = (p: number) => {
    const gr = graphRefs.current;
    if (!gr) return;
    // p in [0,0.5): obs travels sensor->policy; [0.5,1): action travels policy->actuator.
    const [obs, act] = EDGE;
    if (p < 0.5) {
      const ff = p / 0.5;
      const ox = obs.x1 + (obs.x2 - obs.x1) * ff;
      gr.obsDot.current?.setAttribute("cx", `${ox.toFixed(1)}`);
      gr.obsDot.current?.setAttribute("opacity", "1");
      gr.actionDot.current?.setAttribute("opacity", "0");
    } else {
      const ff = (p - 0.5) / 0.5;
      const ax = act.x1 + (act.x2 - act.x1) * ff;
      gr.actionDot.current?.setAttribute("cx", `${ax.toFixed(1)}`);
      gr.actionDot.current?.setAttribute("opacity", "1");
      gr.obsDot.current?.setAttribute("opacity", "0");
    }
    for (const id of CLOCK.tick_order) {
      const at = id === "sensor" ? 0 : id === "policy" ? 0.5 : 0.98;
      gr.haloById[id]?.current?.setAttribute("opacity", `${(litAt(p, at) * 0.9).toFixed(3)}`);
    }
  };

  // the rAF replay: advance the selected run's recorded trajectory. A balanced run
  // loops; a fallen run plays to the topple, holds, then loops — so the fall reads.
  useEffect(() => {
    const r = prefersReduced();
    setReduce(r);
    if (r) {
      setPlaying(false);
      playingRef.current = false;
      // settle on a representative frame: balanced -> mid-run (steady), fallen -> the topple.
      const rest = runRef.current.balanced
        ? Math.min(runRef.current.cart_x.length - 1, 120)
        : runRef.current.cart_x.length - 1;
      frameRef.current = rest;
      setFrame(rest);
      setCart(rest);
      return;
    }
    let raf = 0, last = performance.now(), pulseAcc = 0, readoutMark = 0, holding = 0;
    const tick = (now: number) => {
      const dt = Math.min(now - last, 100);
      last = now;
      if (playingRef.current) {
        const r2 = runRef.current;
        const n = r2.cart_x.length;
        if (holding > 0) {
          holding -= dt;
          if (holding <= 0) { frameRef.current = 0; }          // loop back to the start
        } else {
          let f = frameRef.current + (dt / 1000) * REPLAY_STEPS_PER_S;
          if (f >= n - 1) {
            if (r2.balanced) { f -= n; }                        // seamless loop for a balanced run
            else { f = n - 1; holding = FALL_HOLD_MS; }         // freeze on the fallen frame, then loop
          }
          frameRef.current = f;
        }
        setCart(Math.floor(frameRef.current));
        pulseAcc = (pulseAcc + dt / PULSE_MS) % 1;
        setPulse(pulseAcc);
        if (now - readoutMark >= 120) { readoutMark = now; setFrame(Math.floor(frameRef.current)); }
      }
      raf = requestAnimationFrame(tick);
    };
    raf = requestAnimationFrame(tick);
    return () => cancelAnimationFrame(raf);
  }, []);

  // when the selected rate changes, restart the replay from frame 0 of the new run
  // (reduced-motion settles on the rest frame instead).
  useEffect(() => {
    if (reduce) {
      const rest = run.balanced ? Math.min(nFrames - 1, 120) : nFrames - 1;
      frameRef.current = rest;
      setFrame(rest);
    } else {
      frameRef.current = 0;
      setFrame(0);
    }
    setCart(frameRef.current);
  }, [rateIdx]);

  const onRate = (e: Event) => {
    const idx = parseInt((e.currentTarget as HTMLInputElement).value, 10);
    setRateIdx(idx);
    if (!reduce) { playingRef.current = true; setPlaying(true); }
  };
  const togglePlay = () => {
    const next = !playingRef.current;
    playingRef.current = next;
    setPlaying(next);
  };

  const controlHz = run.control_hz;
  const balanced = run.balanced;
  const latency = run.mean_latency_ms;
  const fellAtStep = run.fell_at_step;
  const angle = run.pole_angle[Math.min(frame, nFrames - 1)];

  const obsStat: TopicStat = { rate: run.obs_rate, dropped: obsDropped };
  const actionStat: TopicStat = { rate: run.action_rate, dropped: run.action_dropped };

  const onGraphRefs = useMemo(() => (r: GraphRefs) => { graphRefs.current = r; }, []);
  const onCartRefs = useMemo(() => (r: CartRefs) => { cartRefs.current = r; }, []);

  // the cliff punchline is live only when we are AT the cliff rate with a deep queue.
  const atCliff = controlHz === SWEEP.falls_at_hz;
  const queueLine = deep
    ? atCliff
      ? `Deep queue (depth ${QUEUE.deep_depth}): /obs drops fall to 0 — yet the pole STILL topples at step ${QUEUE.fell_at_step}. A bigger buffer hid the symptom; the RATE, not the queue, is the killer.`
      : `Deep queue (depth ${QUEUE.deep_depth}): the /obs buffer absorbs the burst, so 0 messages drop. The outcome is unchanged — the queue never decides whether the pole lives.`
    : `Latest-wins queue (depth ${QUEUE.shallow_depth}): a slow policy can't keep up, so ${obsDropped} /obs messages are evicted unread. That drop count is how you SEE a rate mismatch.`;

  // aria-live: the qualitative verdict at the current selection, never per-frame spam.
  const announce = useMemo(() => {
    const cliff = RUNS[N_RATES - 1];
    return (
      `Policy rate ${fmtHz(controlHz)} hertz, ${deep ? `deep depth-${QUEUE.deep_depth}` : `latest-wins depth-${QUEUE.shallow_depth}`} /obs queue: ` +
      (balanced
        ? `the graph balances the pole for the full ${run.steps}-step run. `
        : `the policy is too slow and the pole falls at step ${fellAtStep}. `) +
      `/obs is dropping ${obsDropped} messages, sense-to-act latency is ${latency.toFixed(0)} milliseconds. ` +
      `Drag the rate down to ${fmtHz(cliff.control_hz)} hertz and the pole topples — the control-rate cliff. ` +
      `A deeper queue drives the drops to 0 but never rescues the fall: throughput is not control.`
    );
  }, [rateIdx, deep]);

  return (
    <div class="rg">
      {/* --- controls: the RATE SLIDER (hero) + the queue-depth toggle --- */}
      <div class="rg-controls">
        <div class="rg-ctl-row">
          <label class="rg-ctl-label" for="rg-rate">control rate</label>
          <input
            id="rg-rate"
            class="rg-rate"
            type="range"
            min={0}
            max={N_RATES - 1}
            step={1}
            value={rateIdx}
            onInput={onRate}
            list="rg-rate-ticks"
            aria-label="Policy control rate. Drag down to slow the policy and watch the pole fall off the control-rate cliff."
            aria-valuetext={
              `${fmtHz(controlHz)} hertz — ${balanced ? "pole balanced" : `pole fell at step ${fellAtStep}`}, ` +
              `${obsDropped} /obs dropped, ${latency.toFixed(0)} ms latency`
            }
          />
          <datalist id="rg-rate-ticks">
            {RUNS.map((rr, i) => <option value={i} label={`${fmtHz(rr.control_hz)}`} />)}
          </datalist>
          <span class={`rg-rate-val ${balanced ? "rg-ok" : "rg-bad"}`}>{fmtHz(controlHz)} Hz</span>
        </div>

        <div class="rg-ctl-row">
          <span class="rg-ctl-label" id="rg-q-label">/obs queue</span>
          <div class="rg-seg" role="group" aria-labelledby="rg-q-label">
            <button type="button" class="rg-seg-btn" aria-pressed={!deep} onClick={() => setDeep(false)}>
              latest-wins · depth {QUEUE.shallow_depth}
            </button>
            <button type="button" class="rg-seg-btn" aria-pressed={deep} onClick={() => setDeep(true)}>
              deep · depth {QUEUE.deep_depth}
            </button>
          </div>
          <button type="button" class="rg-btn rg-play" onClick={togglePlay} aria-pressed={playing}>
            {playing ? "❚❚" : "▶"}
          </button>
        </div>
      </div>

      {/* --- verdict banner: the live readout of the current selection --- */}
      <div class="rg-verdict" aria-hidden="true">
        <span class={`rg-badge ${balanced ? "rg-badge-ok" : "rg-badge-bad"}`}>
          {balanced ? "BALANCED ✓" : `FELL ▲ step ${fellAtStep}`}
        </span>
        <span class="rg-metric"><span class="rg-mk">policy</span><b>{fmtHz(controlHz)} Hz</b></span>
        <span class="rg-metric"><span class="rg-mk">/obs dropped</span>
          <b class={obsDropped > 0 ? "rg-bad" : "rg-ok"}>{obsDropped}</b></span>
        <span class="rg-metric"><span class="rg-mk">sense→act latency</span>
          <b class={latency >= 60 ? "rg-bad" : latency > 0 ? "rg-mid" : "rg-ok"}>{latency.toFixed(0)} ms</b></span>
      </div>

      {/* --- panel 1 (headline): the node graph --- */}
      <figure class="rg-panel rg-panel--graph">
        <figcaption class="rg-cap">
          <span>pub-sub node graph · ROS's ideas, without ROS</span>
          <b>virtual clock · policy {fmtHz(controlHz)} Hz</b>
        </figcaption>
        <NodeGraphPanel controlHz={controlHz} obsStat={obsStat} actionStat={actionStat} onRefs={onGraphRefs} />
        <div class="rg-flow" aria-hidden="true">
          each tick: <b class="rg-f-node">sensor</b> → <b class="rg-f-topic">/obs</b> →{" "}
          <b class="rg-f-node">policy</b> → <b class="rg-f-topic">/action</b> →{" "}
          <b class="rg-f-node">actuator</b> · sensor publishes at {SENSOR_HZ} Hz, the policy consumes at{" "}
          {fmtHz(controlHz)} Hz — the gap is what the drop count measures.
        </div>
      </figure>

      {/* --- panel 2 + 3: the cartpole replay + the note --- */}
      <div class="rg-row">
        <figure class="rg-panel rg-panel--cart">
          <figcaption class="rg-cap">
            <span>the cartpole, at {fmtHz(controlHz)} Hz</span>
            <b class={balanced ? "rg-ok" : "rg-bad"}>{balanced ? "BALANCED ✓" : "FELL"}</b>
          </figcaption>
          <CartpolePanel run={run} frame0={0} fell={!balanced} onRefs={onCartRefs} />
          <div class="rg-readout" aria-hidden="true">
            <div class="rg-row-line">
              <span class="rg-k">pole angle</span>
              <span class={`rg-v ${!balanced ? "rg-bad" : ""}`}>{fmtDeg(angle)}</span>
            </div>
            <div class="rg-row-line">
              <span class="rg-k">control step</span>
              <span class="rg-v">{Math.min(frame, nFrames - 1)} / {run.steps}</span>
            </div>
          </div>
        </figure>

        <figure class="rg-panel rg-panel--note">
          <figcaption class="rg-cap">
            <span>{atCliff ? "queue depth ≠ rescue" : "rate, drops & determinism"}</span>
            <b>{deep ? `depth ${QUEUE.deep_depth}` : `depth ${QUEUE.shallow_depth}`}</b>
          </figcaption>
          <div class="rg-det">
            <p class={`rg-det-p ${atCliff && deep ? "rg-det-punch" : ""}`}>{queueLine}</p>
            <p class="rg-det-p">
              The <b class="rg-det-key">virtual clock</b> fires the graph in a fixed order
              (<span class="rg-mono">{CLOCK.tick_order.join(" → ")}</span>), so same
              <span class="rg-mono"> --seed</span> → byte-for-byte identical run — the reference graph was
              recorded twice and matched.
            </p>
          </div>
        </figure>
      </div>

      {/* non-visual path to the same aha — the qualitative verdict only */}
      <div class="bk-sr" aria-live="polite">{announce}</div>

      <p class="rg-note">
        Drag the <b>control rate</b> down and the pole falls off the cliff at {fmtHz(SWEEP.falls_at_hz)} Hz;
        a <b>deeper /obs queue</b> erases the dropped-message symptom but never the fall — the rate keeps the
        robot alive, not the buffer. Real recorded runs from <b>runtime.py</b> (seed 0, virtual clock, scripted
        balancer); poster reads with JS off.
      </p>
    </div>
  );
}

export default function RuntimeGraphToy() {
  return <RuntimeGraph />;
}
