/**
 * SacReachToy — ch2.2 "SAC and the Off-Policy Bargain" concept-toy
 * (demo id `pusher_sac_reach`). THE off-policy bargain, made into one figure:
 * the SAC-trained pusher-reach arm driving its fingertip onto a held-out target
 * (a recorded rollout replay), and the sample-efficiency headline — SAC reaches
 * the goal in ~11x FEWER environment steps than on-policy PPO, because off-policy
 * replay reuses every stored transition dozens of times.
 *
 * THREE panels, top to bottom:
 *   (1) THE SAC ARM REACHES — a recorded rollout of the trained deterministic
 *       policy (tanh of the mean, sac.py's own eval action) on the FIRST held-out
 *       eval seed that succeeds (deterministic, not cherry-picked). A top-down
 *       arena replays the two-link arm (base → elbow → fingertip) closing on the
 *       green target, the fingertip distance falling into the success ring. Reduced-
 *       motion safe: the full fingertip trail + the final reaching pose render
 *       regardless; only the replay walk is JS + rAF and gated off.
 *   (2) THE BARGAIN — the headline. Eval fingertip-to-target distance vs
 *       ENVIRONMENT STEPS, on ONE shared env-steps axis (out to PPO's 200k budget),
 *       for off-policy SAC (blue) and a compact on-policy PPO reference (red). SAC
 *       dives under the 0.05 m solve bar at 18k env steps; PPO learns from the
 *       ~0.176 m random baseline down to a ~0.135 m plateau but never clears the
 *       bar inside 200k → SAC is ~11x more sample-efficient HERE. HONEST: distance
 *       is exactly the signal `env_steps_to_solve` is defined on.
 *   (3) THE MECHANISM + THE HONEST LEDGER — a one-line note on the three braces
 *       (replay reuse + twin-Q/target nets + auto-tuned entropy) and the caveats:
 *       SAC pays MORE compute per env step, the PPO reference is UNTUNED, and the
 *       win is THIS regime (dense reward + cheap env + heavy reuse), not always.
 *
 * Unlike ch1.1 this toy needs NO WASM: it renders REAL curves + a REAL recorded
 * rollout from sac.py + compare_ppo_sac.py (seed 0, cpu) — regenerated by
 * site/scripts/vizdata/ch2.2_sac.py into the co-located vizdata.json, verified to
 * match meta.yaml reference_run (final 0.0434 m, solved <0.05 m at 18000 env steps;
 * PPO not solved in 200k). So it is pure SVG + design tokens: theme-aware for free,
 * and the server-rendered default (full trail + end pose + both curves + the note)
 * IS the JS-off experience; hydration only adds the reach replay. Colour by MEANING:
 * SAC = --signal blue (the off-policy hero, arm + curve), PPO = --alert red (the
 * slower on-policy curve), target + success ring = --entity-target-ink green.
 *
 * Follows the FROZEN CONCEPT-TOY CONTRACT documented at the top of ../PlateIsland.tsx.
 */
import "./SacReachToy.css";
import { useEffect, useMemo, useRef, useState } from "preact/hooks";
// Real curves + a real recorded rollout from sac.py + compare_ppo_sac.py, seed 0,
// cpu — see the file's `provenance` and the generator site/scripts/vizdata/ch2.2_sac.py.
// Committed small text, no binary.
import viz from "../../../../curriculum/phase2_reinforcement/ch2.2_sac/demo/vizdata.json";

// ---------------------------------------------------------------- typed vizdata
interface Rollout {
  seed: number;
  target: number[];
  success: boolean;
  final_dist: number;
  reached_frame: number | null;
  frames: number[][]; // [elbow_x, elbow_y, fingertip_x, fingertip_y, dist]
}
interface SacCurve {
  budget: number;
  solve_step: number;
  final_dist: number;
  final_return: number;
  final_success: number;
  points: number[][]; // [env_step, eval_dist, eval_return]
}
interface PpoCurve {
  budget: number;
  solve_step: number | null;
  plateau_dist: number;
  points: number[][]; // [env_step, eval_dist]
}

const SOLVE_DIST: number = viz.solve_dist;
const SUCCESS_TOL: number = viz.success_tol;
const REACH: number = viz.reach;
const RANDOM_DIST: number = viz.baselines.random_dist;
const ROLL = viz.rollout as Rollout;
const SAC = viz.curves.sac as SacCurve;
const PPO = viz.curves.ppo as PpoCurve;
const SPEEDUP: number = viz.headline.speedup;
const SAC_SOLVE: number = viz.headline.sac_solve;
const PPO_BUDGET: number = viz.headline.ppo_budget;

// ================================================================ REACH ARENA
// Square top-down arena; world (x, y) → svg px with world +y up, base at centre.
const V = 300;
// hold the whole reach workspace + every recorded position, with margin
const WORLD_HALF = (() => {
  let m = REACH; // the reachable-workspace radius (= 2·link_len); holds the reach ring
  for (const [ex, ey, fx, fy] of ROLL.frames) m = Math.max(m, Math.abs(ex), Math.abs(ey), Math.abs(fx), Math.abs(fy));
  m = Math.max(m, Math.abs(ROLL.target[0]), Math.abs(ROLL.target[1]));
  return m * 1.12;
})();
const S = V / 2 / WORLD_HALF;
const w2s = (x: number, y: number): [number, number] => [V / 2 + x * S, V / 2 - y * S];

function ReachArena({ upto }: { upto: number }) {
  const [tx, ty] = w2s(ROLL.target[0], ROLL.target[1]);
  const [bx, by] = w2s(0, 0);
  const trail = ROLL.frames
    .slice(0, upto + 1)
    .map(([, , fx, fy]) => w2s(fx, fy).map((n) => n.toFixed(1)).join(","))
    .join(" ");
  const armAt = (i: number) => {
    const [ex, ey, fx, fy] = ROLL.frames[i];
    const [e0, e1] = w2s(ex, ey);
    const [f0, f1] = w2s(fx, fy);
    return { elbow: [e0, e1] as const, ftip: [f0, f1] as const };
  };
  const start = armAt(0);
  const now = armAt(upto);
  const reached = ROLL.reached_frame !== null && upto >= ROLL.reached_frame;
  return (
    <figure class="sr-arena" data-success={ROLL.success}>
      <svg
        class="sr-svg"
        viewBox={`0 0 ${V} ${V}`}
        role="img"
        aria-label={
          `Top-down pusher-reach arena. A two-link arm anchored at the centre drives its fingertip toward the green target ` +
          `(the dashed success ring) sampled inside the arm's reach. The SAC-trained policy reaches it: over this rollout the ` +
          `fingertip closes from ${ROLL.frames[0][4].toFixed(2)} m to ${ROLL.final_dist.toFixed(3)} m, inside the ${SUCCESS_TOL} m ring.`
        }
      >
        <g class="sr-grid">
          {Array.from({ length: 7 }, (_, i) => ((i + 1) * V) / 8).map((v) => (
            <>
              <line x1={v} y1={2} x2={v} y2={V - 2} />
              <line x1={2} y1={v} x2={V - 2} y2={v} />
            </>
          ))}
        </g>
        {/* the arm's reachable workspace (radius = total reach) */}
        <circle class="sr-reach" cx={bx} cy={by} r={REACH * S} />
        {/* the target: success ring + dot (green — the goal) */}
        <circle class="sr-tol" cx={tx} cy={ty} r={SUCCESS_TOL * S} />
        <circle class="sr-target-dot" cx={tx} cy={ty} r={3} />
        <text class="sr-target-lbl" x={tx + SUCCESS_TOL * S + 4} y={ty + 3}>target</text>
        {/* the fingertip's travelled trail so far (neutral — a map) */}
        <polyline class="sr-trail" points={trail} />
        {/* the identical start pose, ghosted */}
        <polyline class="sr-arm-ghost" points={`${bx},${by} ${start.elbow[0]},${start.elbow[1]} ${start.ftip[0]},${start.ftip[1]}`} />
        {/* the arm now — base → elbow → fingertip (blue — the SAC policy embodied) */}
        <polyline class="sr-arm" points={`${bx},${by} ${now.elbow[0]},${now.elbow[1]} ${now.ftip[0]},${now.ftip[1]}`} />
        <circle class="sr-base" cx={bx} cy={by} r={3.5} />
        <circle class="sr-joint" cx={now.elbow[0]} cy={now.elbow[1]} r={3} />
        <circle class="sr-ftip" cx={now.ftip[0]} cy={now.ftip[1]} r={4} data-reached={reached} />
      </svg>
      <figcaption class="sr-arena-cap">
        <span class="sr-arena-name">SAC · held-out seed {ROLL.seed}</span>
        <span class={`sr-arena-out ${ROLL.success ? "sr-ok" : "sr-bad"}`}>
          {ROLL.success ? "reached target ✓" : "missed target ✗"}
        </span>
      </figcaption>
    </figure>
  );
}

// ================================================================ BARGAIN CHART
// Eval distance-to-target vs ENV STEPS on one shared axis (out to PPO's budget).
// Smaller distance = closer to the goal, so the curves descend; the solve bar sits
// low. SAC dips under it at 18k; PPO never does inside 200k. Pure geometry — SSR
// renders identically.
const CW = 520;
const CH = 250;
const CPAD = { l: 46, r: 66, t: 16, b: 40 };
const CPW = CW - CPAD.l - CPAD.r;
const CPH = CH - CPAD.t - CPAD.b;
const X_MAX = PPO_BUDGET; // shared env-steps axis
const Y_MAX = 0.2; // distance ceiling (random baseline ≈ 0.176 sits just under)
const cx = (step: number) => CPAD.l + (Math.min(step, X_MAX) / X_MAX) * CPW;
const cy = (dist: number) => CPAD.t + (Math.min(dist, Y_MAX) / Y_MAX) * CPH;

function BargainChart() {
  const sacPts = SAC.points.map(([s, d]) => `${cx(s).toFixed(1)},${cy(d).toFixed(1)}`).join(" ");
  const ppoPts = PPO.points.map(([s, d]) => `${cx(s).toFixed(1)},${cy(d).toFixed(1)}`).join(" ");
  const xTicks = [0, 50_000, 100_000, 150_000, 200_000].filter((t) => t <= X_MAX);
  const yTicks = [0, 0.05, 0.1, 0.15, 0.2];
  const sacEnd = SAC.points[SAC.points.length - 1];
  const ppoEnd = PPO.points[PPO.points.length - 1];
  const solveY = cy(SOLVE_DIST);
  return (
    <svg
      class="sr-chart"
      viewBox={`0 0 ${CW} ${CH}`}
      role="img"
      aria-label={
        `Sample-efficiency chart: eval fingertip-to-target distance (metres, lower is better) versus environment steps, ` +
        `on one shared axis out to ${X_MAX.toLocaleString()} steps. The blue off-policy SAC curve falls under the ${SOLVE_DIST} m ` +
        `solve bar at ${SAC_SOLVE.toLocaleString()} environment steps. The red on-policy PPO curve learns from the random ` +
        `${RANDOM_DIST} m baseline down to about ${PPO.plateau_dist.toFixed(2)} m but never reaches the solve bar within ` +
        `${PPO_BUDGET.toLocaleString()} steps. SAC solves in roughly ${SPEEDUP} times fewer environment steps — off-policy replay ` +
        `reuses every stored transition. Honest caveats: SAC costs more compute per step, and the PPO reference is untuned.`
      }
    >
      {/* horizontal gridlines + y ticks (distance) */}
      {yTicks.map((d) => (
        <g>
          <line class="sr-grid-h" x1={CPAD.l} y1={cy(d)} x2={CW - CPAD.r} y2={cy(d)} />
          <text class="sr-tick-lbl" x={CPAD.l - 6} y={cy(d) + 3} text-anchor="end">{d.toFixed(2)}</text>
        </g>
      ))}
      {/* the random baseline (~0.176 m) */}
      <line class="sr-base-line" x1={CPAD.l} y1={cy(RANDOM_DIST)} x2={CW - CPAD.r} y2={cy(RANDOM_DIST)} />
      <text class="sr-base-lbl" x={CW - CPAD.r} y={cy(RANDOM_DIST) - 4} text-anchor="end">random ≈ {RANDOM_DIST} m</text>
      {/* the solve bar (0.05 m) */}
      <line class="sr-solve-line" x1={CPAD.l} y1={solveY} x2={CW - CPAD.r} y2={solveY} />
      <text class="sr-solve-lbl" x={CPAD.l + 4} y={solveY + 12}>solved &lt; {SOLVE_DIST} m</text>

      {/* SAC solved marker — vertical guide at 18k env steps */}
      <line class="sr-solve-mark" x1={cx(SAC_SOLVE)} y1={CPAD.t} x2={cx(SAC_SOLVE)} y2={CH - CPAD.b} />
      <text class="sr-solve-mark-lbl" x={cx(SAC_SOLVE) + 4} y={CPAD.t + 10}>
        SAC solves · {(SAC_SOLVE / 1000).toFixed(0)}k
      </text>

      {/* x axis + env-step ticks */}
      <line class="sr-axis" x1={CPAD.l} y1={CH - CPAD.b} x2={CW - CPAD.r} y2={CH - CPAD.b} />
      {xTicks.map((t) => (
        <text class="sr-tick-lbl" x={cx(t)} y={CH - CPAD.b + 14} text-anchor="middle">
          {t === 0 ? "0" : `${t / 1000}k`}
        </text>
      ))}
      <text class="sr-axis-cap" x={(CPAD.l + CW - CPAD.r) / 2} y={CH - 6} text-anchor="middle">
        environment steps →
      </text>
      <text class="sr-axis-cap" x={CPAD.l - 34} y={CPAD.t - 4}>dist (m)</text>

      {/* the two curves — PPO under, SAC on top */}
      <polyline class="sr-curve sr-curve--ppo" points={ppoPts} />
      <polyline class="sr-curve sr-curve--sac" points={sacPts} />

      {/* endpoint dots + labels */}
      <circle class="sr-dot--ppo" cx={cx(ppoEnd[0])} cy={cy(ppoEnd[1])} r={4} />
      <text class="sr-end-lbl sr-end-lbl--ppo" x={cx(ppoEnd[0]) - 6} y={cy(ppoEnd[1]) - 7} text-anchor="end">
        PPO {ppoEnd[1].toFixed(2)} m
      </text>
      <circle class="sr-dot--sac" cx={cx(sacEnd[0])} cy={cy(sacEnd[1])} r={4} />
      <text class="sr-end-lbl sr-end-lbl--sac" x={cx(sacEnd[0]) + 6} y={cy(sacEnd[1]) - 6}>
        SAC {sacEnd[1].toFixed(2)} m
      </text>
    </svg>
  );
}

// -------------------------------------------------------------------------- the toy
const PLAY_MS = 3600; // one reach-replay pass duration

export default function SacReachToy() {
  // booted=false is the SSR / JS-off view: full trail + final reaching pose + both
  // curves + the note. Hydration flips booted=true and enables the reach replay.
  const [booted, setBooted] = useState(false);
  const [frac, setFrac] = useState(1); // 0..1 along the rollout; 1 = final pose (JS-off + boot)
  const [playing, setPlaying] = useState(false);
  const reduced = useRef(false);
  const rafRef = useRef(0);

  useEffect(() => {
    setBooted(true);
    reduced.current =
      typeof matchMedia !== "undefined" && matchMedia("(prefers-reduced-motion: reduce)").matches;
  }, []);

  useEffect(() => {
    if (!playing) return;
    let start = 0;
    const tick = (t: number) => {
      if (!start) start = t;
      const f = Math.min(1, (t - start) / PLAY_MS);
      setFrac(f);
      if (f < 1) rafRef.current = requestAnimationFrame(tick);
      else setPlaying(false);
    };
    rafRef.current = requestAnimationFrame(tick);
    return () => cancelAnimationFrame(rafRef.current);
  }, [playing]);

  const nFrames = ROLL.frames.length;
  const upto = Math.round(frac * (nFrames - 1));
  const curDist = ROLL.frames[upto][4];
  const reached = ROLL.reached_frame !== null && upto >= ROLL.reached_frame;

  const play = () => {
    if (reduced.current) { setFrac(1); return; } // reduced-motion: jump to the final pose
    setFrac(0);
    setPlaying(true);
  };

  // distance meter: full at the random baseline, empty at the target (0)
  const meterPct = useMemo(() => Math.max(0, Math.min(100, (curDist / RANDOM_DIST) * 100)), [curDist]);

  const liveSummary =
    `The SAC-trained arm reaches a held-out target: the fingertip closes to ${ROLL.final_dist.toFixed(3)} metres, ` +
    `inside the ${SUCCESS_TOL} metre success ring. Off-policy SAC solves this task (eval distance under ${SOLVE_DIST} metres) ` +
    `at ${SAC_SOLVE.toLocaleString()} environment steps; on-policy PPO does not reach the bar within ${PPO_BUDGET.toLocaleString()} ` +
    `steps — about ${SPEEDUP} times more steps. The bargain: replay reuse buys sample efficiency, at more compute per step.`;

  return (
    <div class="sr">
      {/* PANEL 1 — the SAC arm reaches */}
      <section class="sr-panel sr-panel--reach">
        <header class="sr-head">
          <h3 class="sr-title">The SAC arm reaches</h3>
          <p class="sr-sub">
            The trained policy (deterministic eval — <b>tanh of the mean</b>, no sampling) on a
            <b> held-out</b> target it never trained on. Nobody wrote the gains; SAC found them by
            reaching, storing every reach, and replaying the buffer.
          </p>
        </header>
        <div class="sr-arena-wrap">
          <ReachArena upto={upto} />
          <div class="sr-side">
            <div class="sr-readout" aria-hidden="true">
              <div class="sr-row">
                <span class="sr-k">fingertip → target</span>
                <span class={`sr-v ${reached ? "sr-good" : ""}`}>
                  {curDist.toFixed(3)} m {reached ? "✓" : ""}
                </span>
              </div>
              <div class="sr-meter"><div class="sr-meter-fill" data-reached={reached} style={`width:${meterPct}%`} /></div>
              <div class="sr-row">
                <span class="sr-k">final distance</span>
                <span class="sr-v">{ROLL.final_dist.toFixed(3)} m</span>
              </div>
            </div>
            <div class="sr-braces">
              <p class="sr-brace"><b>replay buffer</b> — every transition stored, reused across many gradient steps (the off-policy bargain)</p>
              <p class="sr-brace"><b>twin-Q + target nets</b> — the min of two critics, read off slow copies, kills the divergence replay invites</p>
              <p class="sr-brace"><b>auto-tuned entropy</b> — a temperature that pays the policy to keep exploring, not collapse</p>
            </div>
          </div>
        </div>
        <div class="sr-controls">
          <button type="button" class="sr-btn sr-btn--primary" onClick={play} disabled={!booted}>
            {playing ? "▶ reaching…" : "▶ replay the reach"}
          </button>
          <span class="sr-control-note">recorded rollout · poster reads with JS off</span>
        </div>
      </section>

      {/* PANEL 2 — the bargain (the headline) */}
      <section class="sr-panel sr-panel--bargain">
        <header class="sr-head">
          <h3 class="sr-title">The bargain — {SPEEDUP}× fewer environment steps</h3>
          <p class="sr-sub">
            Eval distance to target vs <b>environment steps</b>, same task, on one shared axis.
            Off-policy <b>SAC</b> reuses its replay buffer; on-policy <b>PPO</b> discards each
            rollout. Distance is exactly the signal <b>env-steps-to-solve</b> is defined on.
          </p>
        </header>
        <BargainChart />
        <div class="sr-legend">
          <span class="sr-leg sr-leg--sac"><b>SAC</b>&nbsp;off-policy · replay reuse</span>
          <span class="sr-leg sr-leg--ppo"><b>PPO</b>&nbsp;on-policy · discards rollouts</span>
        </div>
        <div class="sr-verdict" aria-hidden="true">
          <span class="sr-verdict-tag">the bargain ✓</span>
          <span>
            SAC clears the <b>{SOLVE_DIST} m</b> solve bar at <b>{SAC_SOLVE.toLocaleString()}</b> env
            steps; PPO is still at <b>~{PPO.plateau_dist.toFixed(2)} m</b> after <b>{PPO_BUDGET.toLocaleString()}</b> —
            <b> ~{SPEEDUP}×</b> more steps, and still short. Replaying each transition dozens of times
            converts the same dense reward into far more learning per environment step.
          </span>
        </div>
      </section>

      {/* PANEL 3 — the honest ledger */}
      <section class="sr-panel sr-panel--note">
        <header class="sr-head">
          <h3 class="sr-title">Nothing is free</h3>
        </header>
        <p class="sr-note">
          The bargain is paid for. SAC takes <b>one gradient step per environment step</b> — far more
          compute per step than PPO — and off-policy learning only stays stable because of the three
          braces above (<b>twin-Q + target networks</b>, a <b>reparameterized squashed-Gaussian</b>
          policy, and an <b>auto-tuned entropy</b> temperature).
        </p>
        <p class="sr-note sr-note--caveat">
          Honest caveats: the on-policy reference is <b>untuned</b> (a tuned PPO with reward
          normalization would do better — the point is off-policy needs far less tuning to be
          sample-efficient here); and the win is <b>this regime</b> — dense reward, cheap env, heavy
          replay reuse — <b>not</b> a claim that off-policy always wins. On a sparse-reward or
          expensive-rollout task the ledger reads differently. Real curves + rollout from sac.py
          (seed 0, cpu); poster reads with JS off.
        </p>
      </section>

      {/* screen-reader live region — the reach outcome + the standing bargain */}
      <p class="sr-sr" aria-live="polite">{booted ? liveSummary : ""}</p>
    </div>
  );
}
