/**
 * SerlSampleEfficiencyToy — ch4.3 "RL Post-Training: HIL-SERL in Sim" concept-toy
 * (demo id `serl_sample_efficiency`). THE sample-efficiency story, made honest as a
 * LEARNING CURVE — deliberately NOT a live side-by-side reach.
 *
 * WHY A CURVE, NOT A LIVE REACH. SERL's lesson is SAMPLE EFFICIENCY, not a stronger
 * final policy. On this small dense-reward task both arms top out near the same
 * short-horizon SAC ceiling (final-height gap is modest), so a live side-by-side
 * would show both arms reaching similarly and MISREPRESENT the point. The honest
 * visual is the curve: eval reach-distance vs ONLINE env samples, with the threshold
 * marked and the horizontal "0 vs ~10,000 online samples" gap as the hero. The
 * corrections-as-prior put HIL-SERL below the bar at ZERO online samples; from-scratch
 * SAC has to crawl there over ~10,000 online samples. That horizontal gap IS the win.
 *
 * ONE CONTROL — an online-sample BUDGET scrubber. Drag it and read, for each arm,
 * whether it has cleared the 0.10 m reach threshold WITHIN that many online samples.
 * HIL cleared at 0 (the prior); from-scratch only clears once the budget reaches
 * ~10,000. Scrub to ~5,000 and the contrast is stark: HIL long done, scratch still
 * searching. Default-interesting: boots at 5,000 (HIL cleared, scratch not yet).
 *
 * Real measured numbers from serl.py (seed 0 curve; seeds 0-2 ledger; cpu) —
 * regenerated by site/scripts/vizdata/ch4.3_serl.py into the co-located vizdata.json
 * (the per-step curve PARSED from serl.py's run output, every scalar cross-checked
 * against meta.yaml's reference_run, STOP-on-drift). So it is pure SVG + design
 * tokens: theme-aware for free, and the server-rendered default (both full curves +
 * threshold + both samples-to-threshold markers + the gap + the readout at the
 * default budget) IS the JS-off experience; hydration only makes the budget scrub.
 * Colour by MEANING: HIL-SERL = --signal blue (the sample-efficient hero, primed by
 * the corrections), from-scratch SAC = --alert red (the slow-to-learn baseline), the
 * reach threshold = --entity-target-ink green (the bar both aim for).
 *
 * Follows the FROZEN CONCEPT-TOY CONTRACT documented at the top of ../PlateIsland.tsx.
 */
import "./SerlSampleEfficiencyToy.css";
import { useMemo, useState } from "preact/hooks";
// Real measured curve + scalars from serl.py's reference run — see the file's
// `provenance` and the generator site/scripts/vizdata/ch4.3_serl.py. Committed
// small text, no binary.
import viz from "../../../../curriculum/phase4_capstone/ch4.3_serl/demo/vizdata.json";

// ---------------------------------------------------------------- typed vizdata
const THRESHOLD: number = viz.threshold;
const RANDOM_DIST: number = viz.random_dist;
const N_POOL: number = viz.n_pooled;
const CORR_EPISODES: number = viz.corr_episodes;
const HIL: number[][] = viz.hil_curve as number[][];      // [online_samples, eval_dist]
const SCRATCH: number[][] = viz.scratch_curve as number[][];
const HIL_STS: number = viz.hil_sts;      // 0 — cleared at zero online samples
const SCRATCH_STS: number = viz.scratch_sts; // ~10,000
const PRIOR_DIST: number = viz.prior_dist;
const HIL_BEST: number = viz.hil_best;
const SCRATCH_BEST: number = viz.scratch_best;
const HIL_SUCCESS: number = viz.hil_success;
const SCRATCH_SUCCESS: number = viz.scratch_success;
const DIFF_CI: number[] = viz.diff_ci as number[];
const GAP_SIG: boolean = viz.gap_significant;
const PER = viz.per_seed as {
  sts_hil: number[];
  sts_scratch: number[];
  prior_dist: number[];
  prior_success: number[];
  scratch_best: number[];
  scratch_success: number[];
  hil_best: number[];
  hil_success: number[];
  diff_ci_note: string;
};
const SEEDS: number[] = viz.seeds as number[];

// the shared online-sample axis runs out to the from-scratch budget (its last x).
const X_MAX = SCRATCH[SCRATCH.length - 1][0]; // 12,000

// ------------------------------------------------------------ number formatting
const m = (v: number) => `${v.toFixed(3)} m`;
const k = (v: number) => (v === 0 ? "0" : `${(v / 1000).toFixed(v % 1000 ? 1 : 0)}k`);
const pct = (v: number) => `${Math.round(v * 100)}%`;
const sgn = (v: number) => `${v >= 0 ? "+" : "−"}${Math.abs(v).toFixed(2)}`;

/** eval reach-distance at an arbitrary online-sample budget, linearly interpolated
 *  between the recorded checkpoints. Before an arm's first checkpoint it has no eval
 *  yet — return null so the readout shows "warmup" rather than a made-up number. */
function distAt(curve: number[][], x: number): number | null {
  if (x < curve[0][0]) return null;
  if (x >= curve[curve.length - 1][0]) return curve[curve.length - 1][1];
  for (let i = 1; i < curve.length; i++) {
    const [x1, y1] = curve[i];
    if (x <= x1) {
      const [x0, y0] = curve[i - 1];
      const t = (x - x0) / (x1 - x0);
      return y0 + t * (y1 - y0);
    }
  }
  return curve[curve.length - 1][1];
}

// ================================================================ THE CURVE
// eval reach distance (m, lower is better) vs ONLINE env samples, one shared axis.
// Both curves DESCEND toward the reach threshold; HIL starts already below it (the
// prior), scratch crawls down and only crosses at ~10k. Pure geometry — SSR renders
// identically; the budget cursor is the only hydration-added element.
const CW = 540;
const CH = 260;
const CPAD = { l: 48, r: 60, t: 30, b: 42 };
const CPW = CW - CPAD.l - CPAD.r;
const CPH = CH - CPAD.t - CPAD.b;
const Y_MAX = 0.22; // holds the scratch start (~0.21) and the random baseline (0.176)
const cx = (step: number) => CPAD.l + (Math.min(step, X_MAX) / X_MAX) * CPW;
const cy = (dist: number) => CPAD.t + (Math.min(dist, Y_MAX) / Y_MAX) * CPH;

function Curve({ budget }: { budget: number }) {
  const hilPts = HIL.map(([s, d]) => `${cx(s).toFixed(1)},${cy(d).toFixed(1)}`).join(" ");
  const scrPts = SCRATCH.map(([s, d]) => `${cx(s).toFixed(1)},${cy(d).toFixed(1)}`).join(" ");
  const xTicks = [0, 2000, 4000, 6000, 8000, 10000, 12000].filter((t) => t <= X_MAX);
  const yTicks = [0, 0.05, 0.1, 0.15, 0.2];
  const thY = cy(THRESHOLD);
  const y0 = cy(0);
  const gapY = thY - 12; // the hero gap arrow, just above the threshold line
  return (
    <svg
      class="se-chart"
      viewBox={`0 0 ${CW} ${CH}`}
      role="img"
      aria-label={
        `Sample-efficiency learning curve: eval reach distance in metres (lower is better) versus online ` +
        `environment samples, on one shared axis out to ${X_MAX.toLocaleString()} samples. The blue HIL-SERL ` +
        `curve starts already below the ${THRESHOLD} m reach threshold at zero online samples, because the ` +
        `corrections-as-prior put it there. The red from-scratch SAC curve starts near the random ${RANDOM_DIST} m ` +
        `baseline and crawls down, crossing the threshold only at about ${SCRATCH_STS.toLocaleString()} online ` +
        `samples. That horizontal gap at the threshold — zero versus about ${SCRATCH_STS.toLocaleString()} online ` +
        `samples — is the sample-efficiency win, and it comes from the prior, not from a stronger final policy: ` +
        `both arms finish near the same distance.`
      }
    >
      {/* y grid + ticks */}
      {yTicks.map((d) => (
        <g>
          <line class="se-grid" x1={CPAD.l} y1={cy(d)} x2={CW - CPAD.r} y2={cy(d)} />
          <text class="se-tick" x={CPAD.l - 6} y={cy(d) + 3} text-anchor="end">{d.toFixed(2)}</text>
        </g>
      ))}
      {/* the random baseline (~0.176 m) — where a policy that learned nothing sits */}
      <line class="se-base-line" x1={CPAD.l} y1={cy(RANDOM_DIST)} x2={CW - CPAD.r} y2={cy(RANDOM_DIST)} />
      <text class="se-base-lbl" x={CW - CPAD.r} y={cy(RANDOM_DIST) - 4} text-anchor="end">random ≈ {RANDOM_DIST} m</text>
      {/* the reach threshold (0.10 m) — the bar samples-to-threshold is read off */}
      <line class="se-thresh-line" x1={CPAD.l} y1={thY} x2={CW - CPAD.r} y2={thY} />
      <text class="se-thresh-lbl" x={CW - CPAD.r} y={thY + 12} text-anchor="end">reach threshold {THRESHOLD} m</text>

      {/* ---- THE HERO: the horizontal samples-to-threshold gap, HIL(0) → scratch ---- */}
      <line class="se-gap" x1={cx(HIL_STS)} y1={gapY} x2={cx(SCRATCH_STS)} y2={gapY} marker-start="url(#se-cap)" marker-end="url(#se-arrow)" />
      <text class="se-gap-lbl" x={(cx(HIL_STS) + cx(SCRATCH_STS)) / 2} y={gapY - 6} text-anchor="middle">
        ≈{SCRATCH_STS.toLocaleString()} online samples — the win
      </text>

      {/* samples-to-threshold markers: HIL at 0 (the prior), scratch at ~10k */}
      <line class="se-mark se-mark--hil" x1={cx(HIL_STS)} y1={CPAD.t} x2={cx(HIL_STS)} y2={y0} />
      <text class="se-mark-lbl se-mark-lbl--hil" x={cx(HIL_STS) + 4} y={CPAD.t + 9}>HIL clears · 0</text>
      <line class="se-mark se-mark--scr" x1={cx(SCRATCH_STS)} y1={CPAD.t} x2={cx(SCRATCH_STS)} y2={y0} />
      <text class="se-mark-lbl se-mark-lbl--scr" x={cx(SCRATCH_STS) - 4} y={CPAD.t + 9} text-anchor="end">scratch clears · {k(SCRATCH_STS)}</text>

      {/* the budget cursor (hydration only — reads off both curves at `budget`) */}
      <line class="se-cursor" x1={cx(budget)} y1={CPAD.t} x2={cx(budget)} y2={y0} />

      {/* x axis + online-sample ticks */}
      <line class="se-axis" x1={CPAD.l} y1={y0} x2={CW - CPAD.r} y2={y0} />
      {xTicks.map((t) => (
        <text class="se-tick" x={cx(t)} y={y0 + 14} text-anchor="middle">{t === 0 ? "0" : k(t)}</text>
      ))}
      <text class="se-axis-cap" x={(CPAD.l + CW - CPAD.r) / 2} y={CH - 4} text-anchor="middle">online environment samples →</text>
      <text class="se-axis-cap" x={CPAD.l - 40} y={CPAD.t - 6}>dist (m)</text>

      {/* the two curves — scratch under, HIL on top */}
      <polyline class="se-curve se-curve--scr" points={scrPts} />
      <polyline class="se-curve se-curve--hil" points={hilPts} />

      {/* endpoint dots */}
      <circle class="se-dot--hil" cx={cx(HIL[0][0])} cy={cy(HIL[0][1])} r={4} />
      <text class="se-end-lbl se-end-lbl--hil" x={cx(HIL[0][0]) + 6} y={cy(HIL[0][1]) + 12}>
        prior · {PRIOR_DIST.toFixed(2)} m
      </text>
      <circle class="se-dot--scr" cx={cx(SCRATCH[0][0])} cy={cy(SCRATCH[0][1])} r={4} />

      <defs>
        <marker id="se-arrow" viewBox="0 0 8 8" refX="6" refY="4" markerWidth="7" markerHeight="7" orient="auto">
          <path class="se-arrowhead" d="M0 0 L8 4 L0 8 z" />
        </marker>
        <marker id="se-cap" viewBox="0 0 4 8" refX="2" refY="4" markerWidth="4" markerHeight="8" orient="auto">
          <path class="se-arrowhead" d="M2 0 L2 8" stroke-width="1.6" />
        </marker>
      </defs>
    </svg>
  );
}

// ==================================================================== THE ISLAND
const STEP = 500;

export default function SerlSampleEfficiencyToy() {
  // default-interesting: 5,000 online samples — HIL long cleared (at 0), scratch not
  // yet (needs ~10,000). SSR renders at this budget, so it IS the JS-off view.
  const [budget, setBudget] = useState(5000);

  const hilCleared = budget >= HIL_STS;         // true for any budget (HIL_STS = 0)
  const scrCleared = budget >= SCRATCH_STS;
  const hilLive = distAt(HIL, budget);
  const scrLive = distAt(SCRATCH, budget);
  const scrRemaining = Math.max(0, SCRATCH_STS - budget);

  const announce = useMemo(
    () =>
      `Online-sample budget ${budget.toLocaleString()}. HIL-SERL cleared the ${THRESHOLD} metre reach threshold ` +
      `at 0 online samples — the corrections-as-prior put it there. From-scratch SAC has ` +
      `${scrCleared ? `cleared it, at about ${SCRATCH_STS.toLocaleString()} online samples` : `not cleared it yet; it needs about ${scrRemaining.toLocaleString()} more online samples`}. ` +
      `The win is the sample axis — about ${SCRATCH_STS.toLocaleString()} online samples saved — not a stronger final ` +
      `policy: both arms finish near the same distance (${m(HIL_BEST)} versus ${m(SCRATCH_BEST)}).`,
    [budget, scrCleared, scrRemaining],
  );

  return (
    <div class="se">
      <header class="se-head">
        <h3 class="se-title">Sample efficiency — 0 vs ~{k(SCRATCH_STS)} online samples</h3>
        <p class="se-sub">
          Eval reach distance vs <b>online environment samples</b>, same task, one shared axis. <b>HIL-SERL</b>{" "}
          starts <b>already below</b> the reach threshold — the corrections-as-prior put it there with{" "}
          <b>zero</b> online interaction. <b>From-scratch SAC</b> must discover the reach from nothing and
          crawls to the same line over ~{k(SCRATCH_STS)} online samples. The horizontal gap <b>is</b> the win.
        </p>
      </header>

      <Curve budget={budget} />

      <div class="se-legend">
        <span class="se-leg se-leg--hil"><b>HIL-SERL</b>&nbsp;corrections prior + online</span>
        <span class="se-leg se-leg--scr"><b>from scratch</b>&nbsp;no prior, no corrections</span>
      </div>

      {/* --- the one control: the online-sample budget scrubber --- */}
      <div class="se-controls">
        <label class="se-slider-lbl" for="se-budget">online-sample budget</label>
        <input
          id="se-budget"
          class="se-slider"
          type="range"
          min={0}
          max={X_MAX}
          step={STEP}
          value={budget}
          onInput={(e) => setBudget(Number((e.target as HTMLInputElement).value))}
          aria-valuetext={
            `${budget.toLocaleString()} online samples — HIL-SERL cleared at 0, ` +
            `from-scratch ${scrCleared ? "cleared" : `${scrRemaining.toLocaleString()} short`}`
          }
        />
        <output class="se-budget-out" for="se-budget">{budget.toLocaleString()} samples</output>
      </div>

      {/* live "cleared the threshold within this budget?" readout for both arms */}
      <div class="se-status" aria-hidden="true">
        <div class="se-arm se-arm--hil" data-cleared={hilCleared}>
          <span class="se-arm-name">HIL-SERL</span>
          <span class="se-arm-badge">cleared ✓ · at 0 samples</span>
          <span class="se-arm-sub">live eval {hilLive === null ? "—" : m(hilLive)} · best {m(HIL_BEST)}</span>
        </div>
        <div class="se-arm se-arm--scr" data-cleared={scrCleared}>
          <span class="se-arm-name">from scratch</span>
          <span class="se-arm-badge">
            {scrCleared ? `cleared ✓ · at ${k(SCRATCH_STS)}` : `searching… ${scrRemaining.toLocaleString()} to go`}
          </span>
          <span class="se-arm-sub">live eval {scrLive === null ? "warmup" : m(scrLive)} · best {m(SCRATCH_BEST)}</span>
        </div>
      </div>

      {/* the seed-robust ledger — the honest "holds on every seed" */}
      <figure class="se-ledger">
        <figcaption class="se-ledger-cap">
          <span>samples-to-threshold · seeds {SEEDS.join(", ")}</span>
          <b>N = {N_POOL} pooled rollouts / seed</b>
        </figcaption>
        <div class="se-ledger-grid">
          <span class="se-lg-h" />
          {SEEDS.map((s) => <span class="se-lg-h">seed {s}</span>)}
          <span class="se-lg-rowh se-lg--hil">HIL-SERL</span>
          {PER.sts_hil.map((v) => <span class="se-lg-v se-lg--good">{v.toLocaleString()}</span>)}
          <span class="se-lg-rowh se-lg--scr">from scratch</span>
          {PER.sts_scratch.map((v) => <span class="se-lg-v se-lg--slow">{v.toLocaleString()}</span>)}
        </div>
        <p class="se-ledger-note">
          HIL-SERL clears the bar at <b>0</b> online samples on <b>every</b> seed; from-scratch needs{" "}
          <b>~10,000–11,000</b>. On the pooled eval, HIL-SERL's success ({pct(HIL_SUCCESS)} on seed 0) is at least
          from-scratch's ({pct(SCRATCH_SUCCESS)}) on all three seeds, and the difference CI excludes zero on two of them
          (seed 0: {sgn(DIFF_CI[0])}..{sgn(DIFF_CI[1])}{GAP_SIG ? " · significant" : ""}).
        </p>
      </figure>

      {/* non-visual path to the same aha — the qualitative story, never per-frame spam */}
      <div class="bk-sr" aria-live="polite">{announce}</div>

      {/* the honest framing — the load-bearing caveat */}
      <p class="se-note">
        The win is <b>sample efficiency from the corrections prior</b>, <b>not</b> a stronger final policy. On this
        small dense-reward task both arms top out near the same short-horizon SAC ceiling (HIL best {m(HIL_BEST)},
        scratch best {m(SCRATCH_BEST)}), so online fine-tuning <b>holds</b> the prior rather than beating it — and the
        HIL curve even wobbles up during the offline-to-online transition, which is why we keep the corrections in the
        replay and return the <b>best</b> checkpoint (the prior). On harder tasks — the real HIL-SERL paper's
        contact-rich manipulation and the gated capstone suite — the prior is far from optimal and the online phase is
        where the policy actually gets good. Real measured curve + scalars from serl.py ({CORR_EPISODES} corrections,
        seed 0 curve, seeds {SEEDS.join(", ")} ledger, cpu); poster reads with JS off.
      </p>
    </div>
  );
}
