/**
 * SimGapToy — ch3.6 "Full Circle: Run Your ch1.1 Policy in the Engine You Built"
 * concept-toy (demo id `pusht_sim2sim`). THE CLOSE of the whole course, made into
 * one figure: the SAME ch1.1 behavior-cloning policy — trained in MuJoCo, reloaded
 * not retrained — rolled out in BOTH MuJoCo (the ground truth) and the learner's
 * own from-scratch numpy engine (ch3.3-3.5), and the sim-to-sim gap between them.
 *
 * THREE panels, top to bottom:
 *   (1) THE SAME POLICY, TWO ENGINES — side by side. Recorded PushT rollouts replay:
 *       the T-block pushed toward the target in MuJoCo (blue) and in the learner's
 *       engine (red), from ONE shared start. The block succeeds more often in MuJoCo
 *       and struggles in the simplified engine. A rollout selector cycles three
 *       first-of-kind episodes (deterministic, not cherry-picked): the headline
 *       (MuJoCo succeeds / engine fails), one where both succeed (the engine PARTLY
 *       works), and one where neither does (the policy is imperfect in both).
 *   (2) THE SIM2SIM GAP — the headline. The two BC success rates over 50 held-out
 *       episodes with ch1.6-style Wilson 95% error bars: MuJoCo 0.54, engine 0.18.
 *       The intervals do not overlap: the gap is REAL, not sampling noise. HONEST:
 *       this is the SAME policy — only the physics changed. That is sim-to-real in
 *       miniature (the mechanism of ch2.6, measured against a sim you can read).
 *   (3) WHY — the learner's engine is a deliberately simplified two-point-mass block
 *       with frictionless normal contact. The measured ANGLE divergence (0.887 rad)
 *       dwarfs the position divergence (0.074 m): a two-mass dumbbell rotates the T
 *       with far less authority than MuJoCo's shaped body. Building the engine is
 *       what taught you what a sim approximation costs.
 *
 * Unlike ch1.1 this toy needs NO WASM: it renders REAL recorded rollouts + REAL
 * success rates from compare.py (seed 0, cpu, 50 episodes) — regenerated by
 * site/scripts/vizdata/ch3.6_compare.py into the co-located vizdata.json, verified
 * to match meta.yaml reference_run (MuJoCo 0.54 == ch1.1's own eval, engine 0.18,
 * divergence 0.074 m / 0.887 rad). So it is pure SVG + design tokens: theme-aware
 * for free, and the server-rendered default (full trails + end poses + the gap bars
 * + the why) IS the JS-off experience; hydration only adds the replay animation and
 * the rollout selector. Colour per the demo/embed.yaml scheme: MuJoCo = --signal
 * blue (the ground truth), engine = --alert red (the worse transfer), target +
 * tolerance ring = --entity-target-ink green, block trails = neutral ink.
 *
 * Follows the FROZEN CONCEPT-TOY CONTRACT documented at the top of ../PlateIsland.tsx.
 */
import "./sim-gap.css";
import { useEffect, useRef, useState } from "preact/hooks";
// Real recorded rollouts + success rates from compare.py, seed 0, cpu — see the
// file's `provenance` and the generator site/scripts/vizdata/ch3.6_compare.py.
// Committed small text, no binary.
import viz from "../../../../curriculum/phase3_advanced/ch3.6_compare/demo/vizdata.json";

// ---------------------------------------------------------------- typed vizdata
interface Rollout {
  key: string;
  seed: number;
  why: string;
  mj_success: boolean;
  engine_success: boolean;
  mj_steps: number;
  engine_steps: number;
  mj: number[][]; // [x, y, yaw] frames, subsampled
  engine: number[][];
}
interface RateStat {
  k: number;
  n: number;
  rate: number;
  ci: [number, number];
}
const WORLD_HALF: number = viz.world_half;
const POS_TOL: number = viz.pos_tol;
const TEE = viz.tee as { bar_half: number[]; stem_half: number[]; stem_offset: number };
const ROLLOUTS = viz.rollouts as Rollout[];
const MJ_STAT = viz.transfer.mujoco as RateStat;
const ENG_STAT = viz.transfer.engine as RateStat;
const N_EVAL: number = viz.episodes;
const MEAN_POS: number = viz.divergence.mean_pos_m;
const MEAN_ANG: number = viz.divergence.mean_ang_rad;

// -------------------------------------------------------------- Wilson score (ch1.6)
// Closed-form 95% Wilson score interval — a direct port of ch1.6 harness.py
// wilson_ci, so the two success rates carry the same honest error bar the eval
// module teaches. Recomputed from the stored (k, n); it reproduces the vizdata
// `ci` exactly (verified in DEV below).
const Z95 = 1.959963985; // 0.975 standard-normal quantile — same constant as ch1.6
function wilson(k: number, n: number, z: number = Z95): [number, number] {
  if (n <= 0) return [0, 1];
  const p = k / n;
  const denom = 1 + (z * z) / n;
  const center = (p + (z * z) / (2 * n)) / denom;
  const half = (z / denom) * Math.sqrt((p * (1 - p)) / n + (z * z) / (4 * n * n));
  return [Math.max(0, center - half), Math.min(1, center + half)];
}
const MJ_CI = wilson(MJ_STAT.k, MJ_STAT.n);
const ENG_CI = wilson(ENG_STAT.k, ENG_STAT.n);
// The two 95% intervals do not overlap → the gap is separable at n=50 (the
// conservative eyeball; the point is that this is NOT sampling noise).
const SEPARABLE = ENG_CI[1] < MJ_CI[0];

// Trust-but-verify at dev time only (never throws in the shipped bundle).
if (typeof import.meta !== "undefined" && (import.meta as { env?: { DEV?: boolean } }).env?.DEV) {
  const near = (a: number, b: number) => Math.abs(a - b) < 1e-3;
  // eslint-disable-next-line no-console
  console.assert(
    near(MJ_CI[0], MJ_STAT.ci[0]) && near(MJ_CI[1], MJ_STAT.ci[1]) &&
      near(ENG_CI[0], ENG_STAT.ci[0]) && near(ENG_CI[1], ENG_STAT.ci[1]),
    "[ch3.6 toy] Wilson recompute drifted from vizdata ci",
  );
}

// ------------------------------------------------------------------ arena geometry
// Square top-down arena; world (x, y) → svg px with world +y up. Same frame both
// sims share, so the two panels are directly comparable.
const V = 300;
const S = V / (2 * WORLD_HALF);
const w2s = (x: number, y: number): [number, number] => [V / 2 + x * S, V / 2 - y * S];

const BAR_W = 2 * TEE.bar_half[0] * S, BAR_H = 2 * TEE.bar_half[1] * S;
const STEM_W = 2 * TEE.stem_half[0] * S, STEM_H = 2 * TEE.stem_half[1] * S;
const STEM_Y = TEE.stem_offset * S; // stem hangs toward the block's body -y (svg down at yaw 0)

/** A PushT "T" at world (x, y) / yaw (rad), in the given class. Two boxes — bar +
 *  stem — matching pusht.xml, drawn faithfully (same construction as PlateIsland's
 *  verified PosterTee: rotate by -yawDeg so a CCW world turn reads CCW on screen). */
function Tee({ pose, cls }: { pose: number[]; cls: string }) {
  const [cx, cy] = w2s(pose[0], pose[1]);
  const yawDeg = (pose[2] * 180) / Math.PI;
  return (
    <g class={cls} transform={`translate(${cx.toFixed(1)} ${cy.toFixed(1)}) rotate(${(-yawDeg).toFixed(1)})`}>
      <rect x={-BAR_W / 2} y={-BAR_H / 2} width={BAR_W} height={BAR_H} rx={2} />
      <rect x={-STEM_W / 2} y={STEM_Y - STEM_H / 2} width={STEM_W} height={STEM_H} rx={2} />
    </g>
  );
}

/** One sim's arena: the shared target + tolerance ring, the block's travelled trail
 *  up to `upto`, a faint ghost of the identical start pose, and the block now. */
function Arena({
  poses, upto, tone, label, success, ariaLabel,
}: {
  poses: number[][];
  upto: number;
  tone: "mujoco" | "engine";
  label: string;
  success: boolean;
  ariaLabel: string;
}) {
  const trail = poses.slice(0, upto + 1).map(([x, y]) => w2s(x, y).map((n) => n.toFixed(1)).join(",")).join(" ");
  const [ox, oy] = w2s(0, 0);
  return (
    <figure class={`sg-arena sg-arena--${tone}`} data-success={success}>
      <svg class="sg-svg" viewBox={`0 0 ${V} ${V}`} role="img" aria-label={ariaLabel}>
        {/* faint graph paper */}
        <g class="sg-grid">
          {Array.from({ length: 7 }, (_, i) => ((i + 1) * V) / 8).map((v) => (
            <>
              <line x1={v} y1={2} x2={v} y2={V - 2} />
              <line x1={2} y1={v} x2={V - 2} y2={v} />
            </>
          ))}
        </g>
        {/* the target: tolerance ring + dashed T at the origin (green — the goal) */}
        <circle class="sg-tol" cx={ox} cy={oy} r={POS_TOL * S} />
        <Tee pose={[0, 0, 0]} cls="sg-target" />
        {/* the block's travelled path so far (neutral ink — a map, not an entity) */}
        <polyline class="sg-trail" points={trail} />
        {/* the identical start pose, ghosted, so the shared origin reads */}
        <Tee pose={poses[0]} cls="sg-ghost" />
        {/* the block now — the hero, in the sim's tone */}
        <Tee pose={poses[upto]} cls="sg-block" />
      </svg>
      <figcaption class="sg-arena-cap">
        <span class="sg-arena-name">{label}</span>
        <span class={`sg-arena-out ${success ? "sg-ok" : "sg-bad"}`}>
          {success ? "reached target ✓" : "missed target ✗"}
        </span>
      </figcaption>
    </figure>
  );
}

// --------------------------------------------------------------- success-rate chart
// The sim2sim gap: two success rates on a 0..1 axis with Wilson 95% whiskers — the
// ch1.6 error-bar idiom. Pure geometry; server-renders identically.
const CW = 480;
const GUT_L = 132;
const GUT_R = 92;
const AX0 = GUT_L;
const AX1 = CW - GUT_R;
const r2x = (r: number): number => AX0 + r * (AX1 - AX0);
const pct = (r: number): string => `${Math.round(r * 100)}%`;

function GapChart() {
  const rows = [
    { label: "MuJoCo", sub: "ground truth", tone: "mujoco", rate: MJ_STAT.rate, ci: MJ_CI, k: MJ_STAT.k },
    { label: "your engine", sub: "ch3.3–3.5", tone: "engine", rate: ENG_STAT.rate, ci: ENG_CI, k: ENG_STAT.k },
  ];
  const rowH = 52;
  const top = 16;
  const axisY = top + rows.length * rowH + 6;
  const H = axisY + 30;
  const ticks = [0, 0.25, 0.5, 0.75, 1];
  return (
    <svg
      class="sg-chart"
      viewBox={`0 0 ${CW} ${H}`}
      role="img"
      aria-label={
        `The same behavior-cloning policy's success rate over ${N_EVAL} held-out episodes, in two sims, with Wilson 95 percent intervals. ` +
        `MuJoCo, the ground truth: ${MJ_STAT.rate.toFixed(2)}, interval ${MJ_CI[0].toFixed(2)} to ${MJ_CI[1].toFixed(2)}. ` +
        `Your from-scratch engine: ${ENG_STAT.rate.toFixed(2)}, interval ${ENG_CI[0].toFixed(2)} to ${ENG_CI[1].toFixed(2)}. ` +
        (SEPARABLE
          ? "The two intervals do not overlap: the gap is real, not sampling noise. Only the physics changed, not the policy."
          : "")
      }
    >
      <line class="sg-axis" x1={AX0} y1={axisY} x2={AX1} y2={axisY} />
      {ticks.map((t) => (
        <g class="sg-tick">
          <line x1={r2x(t)} y1={axisY} x2={r2x(t)} y2={axisY + 5} />
          <text class="sg-tick-lbl" x={r2x(t)} y={axisY + 18} text-anchor="middle">{pct(t)}</text>
        </g>
      ))}
      <text class="sg-axis-cap" x={(AX0 + AX1) / 2} y={H - 2} text-anchor="middle">
        BC success rate (n={N_EVAL})
      </text>

      {rows.map((row, i) => {
        const y = top + i * rowH + rowH / 2;
        const px = r2x(row.rate);
        const lo = r2x(row.ci[0]);
        const hi = r2x(row.ci[1]);
        return (
          <g class={`sg-row sg-row--${row.tone}`}>
            <text class="sg-row-lbl" x={AX0 - 12} y={y - 2} text-anchor="end">{row.label}</text>
            <text class="sg-row-sub" x={AX0 - 12} y={y + 12} text-anchor="end">{row.sub}</text>
            <g class="sg-whisker">
              <line x1={lo} y1={y} x2={hi} y2={y} />
              <line x1={lo} y1={y - 7} x2={lo} y2={y + 7} />
              <line x1={hi} y1={y - 7} x2={hi} y2={y + 7} />
            </g>
            <circle class="sg-point" cx={px} cy={y} r={6} />
            <text class="sg-row-val" x={AX1 + 12} y={y + 4}>{row.rate.toFixed(2)}</text>
          </g>
        );
      })}
    </svg>
  );
}

// -------------------------------------------------------------------------- the toy
const PLAY_MS = 4200; // one replay pass duration (both traces finish together)

export default function SimGapToy() {
  // booted=false is the SSR / JS-off view: full trails + end poses + gap bars + why,
  // all shown. Hydration flips booted=true and enables replay + the rollout selector.
  const [booted, setBooted] = useState(false);
  const [idx, setIdx] = useState(0); // which rollout (0 = the headline, mj-success/engine-fail)
  const [frac, setFrac] = useState(1); // 0..1 along the rollout; 1 = end state (JS-off + boot)
  const [playing, setPlaying] = useState(false);
  const reduced = useRef(false);
  const rafRef = useRef(0);

  useEffect(() => {
    setBooted(true);
    reduced.current =
      typeof matchMedia !== "undefined" && matchMedia("(prefers-reduced-motion: reduce)").matches;
  }, []);

  // the replay loop — advance frac 0→1 over PLAY_MS, then stop at the end state.
  useEffect(() => {
    if (!playing) return;
    let start = 0;
    const tick = (t: number) => {
      if (!start) start = t;
      const f = Math.min(1, (t - start) / PLAY_MS);
      setFrac(f);
      if (f < 1) rafRef.current = requestAnimationFrame(tick);
      else setPlaying(false);
    };
    rafRef.current = requestAnimationFrame(tick);
    return () => cancelAnimationFrame(rafRef.current);
  }, [playing, idx]);

  const roll = ROLLOUTS[idx];
  const mjUpto = Math.round(frac * (roll.mj.length - 1));
  const engUpto = Math.round(frac * (roll.engine.length - 1));

  const play = () => {
    if (reduced.current) { setFrac(1); return; } // reduced-motion: jump to the end, no animation
    setFrac(0);
    setPlaying(true);
  };
  const showRollout = (i: number) => {
    cancelAnimationFrame(rafRef.current);
    setPlaying(false);
    setIdx(i);
    if (reduced.current) setFrac(1); // no auto-replay under reduced motion
    else { setFrac(0); setPlaying(true); }
  };

  // aria-live summary — the outcome of the shown rollout + the standing gap.
  const liveSummary =
    `${roll.key} rollout, seed ${roll.seed}: in MuJoCo the policy ${roll.mj_success ? "reached" : "did not reach"} the target; ` +
    `in your engine it ${roll.engine_success ? "reached" : "did not reach"} it. Same policy, only the physics changed. ` +
    `Over ${N_EVAL} episodes MuJoCo succeeds ${pct(MJ_STAT.rate)} and your engine ${pct(ENG_STAT.rate)} — ` +
    (SEPARABLE ? "a real gap at these error bars, not noise." : "");

  return (
    <div class="sg">
      {/* PANEL 1 — the same policy, two engines, side by side */}
      <section class="sg-panel sg-panel--replay">
        <header class="sg-head">
          <h3 class="sg-title">The same policy, two engines</h3>
          <p class="sg-sub">
            Your ch1.1 BC policy, replayed from one shared start in <b>MuJoCo</b> and in the
            <b> engine you built</b>. It succeeds more often in MuJoCo and struggles in the
            simplified engine.
          </p>
        </header>
        <div class="sg-arenas">
          <Arena
            poses={roll.mj}
            upto={mjUpto}
            tone="mujoco"
            label="MuJoCo"
            success={roll.mj_success}
            ariaLabel={`Top-down PushT arena. The T-block's path as the ch1.1 policy pushes it in MuJoCo, from the shared start toward the green dashed target at the center. This rollout ${roll.mj_success ? "reaches" : "does not reach"} the target.`}
          />
          <Arena
            poses={roll.engine}
            upto={engUpto}
            tone="engine"
            label="your engine"
            success={roll.engine_success}
            ariaLabel={`Top-down PushT arena. The T-block's path as the SAME policy pushes it in your from-scratch two-point-mass engine, from the identical start. This rollout ${roll.engine_success ? "reaches" : "does not reach"} the target — the block drifts and rotates differently.`}
          />
        </div>

        {/* controls — JS-only enhancement (the SSR view ships the full trails + end poses) */}
        <div class="sg-controls">
          <button type="button" class="sg-btn sg-btn--primary" onClick={play} disabled={!booted}>
            {playing ? "▶ playing…" : "▶ replay both"}
          </button>
          <div class="sg-seg" role="group" aria-label="Choose which recorded rollout to compare">
            {ROLLOUTS.map((r, i) => (
              <button
                type="button"
                class={`sg-seg-btn ${i === idx ? "is-active" : ""}`}
                aria-pressed={i === idx}
                disabled={!booted}
                onClick={() => showRollout(i)}
                title={r.why}
              >
                {r.key === "headline" ? "MuJoCo wins" : r.key === "both" ? "both win" : "both miss"}
              </button>
            ))}
          </div>
          <span class="sg-control-note">recorded rollouts · poster reads with JS off</span>
        </div>
        <p class="sg-why-line">{roll.why}.</p>
      </section>

      {/* PANEL 2 — the sim2sim gap (the headline) */}
      <section class="sg-panel sg-panel--gap">
        <header class="sg-head">
          <h3 class="sg-title">The sim-to-sim gap</h3>
          <p class="sg-sub">
            BC success over {N_EVAL} held-out episodes, same policy in both sims, with Wilson
            95% intervals (the ch1.6 error bar).
          </p>
        </header>
        <GapChart />
        <div
          class={`sg-verdict ${SEPARABLE ? "sg-verdict--real" : "sg-verdict--soft"}`}
          aria-hidden="true"
        >
          <span class="sg-verdict-tag">{SEPARABLE ? "real gap ✓" : "gap"}</span>
          <span>
            the SAME policy keeps <b>{pct(ENG_STAT.rate)}</b> of MuJoCo&rsquo;s <b>{pct(MJ_STAT.rate)}</b> —
            only the <b>physics</b> changed. The intervals do not overlap, so this is not sampling
            noise. This is <b>sim-to-real in miniature</b>: a policy meeting dynamics its training
            never showed it (the mechanism of ch2.6).
          </span>
        </div>
      </section>

      {/* PANEL 3 — why the gap exists (the honest reason) */}
      <section class="sg-panel sg-panel--why">
        <header class="sg-head">
          <h3 class="sg-title">Why &mdash; your engine is a simplification</h3>
        </header>
        <p class="sg-why">
          Your engine&rsquo;s T-block is <b>two point masses</b> on a ch3.4 rigid link, pushed by
          <b> frictionless normal contact</b> &mdash; a deliberately simpler PushT than MuJoCo&rsquo;s
          shaped, welded body. That is the whole reason for the gap, and it is diagnostic: the
          measured <b>angle</b> divergence, <b>{MEAN_ANG.toFixed(2)} rad</b>, dwarfs the
          <b> position</b> divergence, <b>{MEAN_POS.toFixed(3)} m</b>. A two-mass dumbbell rotates
          the T with far less authority than MuJoCo&rsquo;s box does, so the policy aligns the block
          much worse in your engine. Building the engine is what taught you what a sim approximation
          costs &mdash; the gap is a quantity to measure and respect, not a bug to erase.
        </p>
      </section>

      {/* screen-reader live region — the rollout outcome + the standing gap */}
      <p class="sg-sr" aria-live="polite">{booted ? liveSummary : ""}</p>
    </div>
  );
}
