/**
 * ch1.8 "The Tiny VLA II: Train It" — the VLA ROLLOUT REPLAY + FUSION-ATTENTION
 * concept-toy (`demo: vla_rollout`).
 *
 * HONESTY FIRST — THIS IS A RECORDED REPLAY, NOT LIVE INFERENCE. A live in-browser
 * VLA is future work, BLOCKED on: (1) a sampler-aware contract-v2 runtime — an ODE
 * flow sampler, strictly more than ch1.5's; (2) offscreen RGB rendering to featurize
 * each frame, which MuJoCo-WASM does not expose; and (3) a tokenizer port. The
 * chapter's OWN demo/embed.yaml recommends shipping this recorded panel instead. So
 * every frame here is a DETERMINISTIC RECORDING of one eval episode of the trained
 * tiny VLA (seed 0), replayed through the same top-down PushT canvas the ch1.1 toy
 * draws with — it LOOKS live, and the labels say plainly that it is not.
 *
 * TWO panels, one control:
 *   1. THE ROLLOUT REPLAY (canvas): play back the recorded episode — the pusher
 *      pushing the T toward the target, step by step. The ONE control is a scrub
 *      slider over the recorded frames; play/pause auto-advances it. Keyboard: space
 *      = play/pause, ← → = scrub, Home/End = jump. An aria-live line announces
 *      progress + the recorded outcome (success).
 *   2. THE FUSION ATTENTION (DOM bars): the CLS token's attention over the fused
 *      sequence [CLS, vision, state, tok_0..tok_15] — vla.py's `fusion/cls_attention`
 *      — grouped into vision / state / language, plus the per-word language bars. The
 *      money shot of what the VLA "looks at". Honest caption: --break blind == sighted
 *      (meta.yaml), so the random-init vision channel is NOT load-bearing.
 *
 * Unlike the ch1.1/ch0.1 toys this needs NO WASM, NO onnx, NO heavy import: it replays
 * REAL pre-computed geometry from vla.py (seed 0, cpu, DEFAULT config), regenerated by
 * site/scripts/vizdata/ch1.8_vla.py into the co-located vizdata.json and verified to
 * match meta.yaml's reference_run (PushT trained 0.58 vs untrained 0.0; ALOHA 0.0). NO
 * frame/image binaries: the replay is pure vector geometry (pusher/tee x,y,yaw).
 *
 * JS-off: the whole toy server-renders. Panel 1's SSR poster is an SVG of the RECORDED
 * PATH (the tee's traced route + start/end poses + the target) — the rollout's story
 * without motion; panel 2's attention bars are plain DOM, so the entire attention
 * lesson is present with JS off. JS only adds the animated canvas + the scrubber.
 * Theme-aware: the poster + bars read the page's flipping design tokens (light
 * fallbacks throughout); the canvas re-resolves those tokens every frame so a theme
 * toggle is reflected live. Reduced-motion: boots PAUSED (no autoplay) and the bar
 * transitions are disabled.
 */
import "./VlaRolloutToy.css";
import { useEffect, useRef, useState } from "preact/hooks";
// Real recorded rollout + fusion attention from vla.py, seed 0, cpu, default config —
// see the file's `provenance` and the generator site/scripts/vizdata/ch1.8_vla.py.
// Committed small text, no binary.
import vizRaw from "../../../../curriculum/phase1_imitation/ch1.8_vla/demo/vizdata.json";

// ------------------------------------------------------------------- data shape
interface VrData {
  provenance: string;
  seed: number;
  live_blocked: string;
  world_half_extent_m: number;
  meta: {
    pusht_success_rate: number;
    pusht_success_ci_lo: number;
    pusht_success_ci_hi: number;
    baseline_pusht_success_rate: number;
    aloha_success_rate: number;
    break_blind_pusht_success_rate: number;
    final_train_loss: number;
    flow_steps: number;
    model_dim: number;
    num_examples: number;
    eval_episodes: number;
    feature_dim: number;
  };
  tee: { bar_half: [number, number]; stem_half: [number, number]; stem_offset_y: number };
  target: { x: number; y: number; yaw: number };
  rollout: {
    episode: number;
    ep_seed: number;
    instruction: string;
    success: boolean;
    mean_return: number;
    steps: number;
    kept: number;
    pos_err0: number;
    pos_err_final: number;
    frames: number[][]; // [pusher_x, pusher_y, tee_x, tee_y, tee_yaw]
  };
  attention: {
    labels: string[];
    weights: number[];
    sum: number;
    cls: number;
    vision: number;
    state: number;
    language: number;
    tokens: { word: string; weight: number }[];
    n_language_tokens: number;
  };
}
const DATA = vizRaw as unknown as VrData;

const WORLD_HALF = DATA.world_half_extent_m; // 0.45 m
const FRAMES = DATA.rollout.frames;
const N = FRAMES.length;
const BAR_HALF = DATA.tee.bar_half;
const STEM_HALF = DATA.tee.stem_half;
const STEM_OY = DATA.tee.stem_offset_y;
const CANVAS_PX = 512;
const PLAY_FPS = 14; // recorded frames advanced per second during playback

const pct = (v: number) => `${(v * 100).toFixed(0)}%`;
const pct1 = (v: number) => `${(v * 100).toFixed(1)}%`;

// --------------------------------------------------------------- palette tokens
type PaletteKey =
  | "--entity-pusher" | "--entity-block" | "--entity-target"
  | "--signal" | "--ink-mute" | "--rule-strong" | "--paper" | "--paper-2";
const PALETTE_FALLBACK: Record<PaletteKey, string> = {
  "--entity-pusher": "#b0560f",
  "--entity-block": "#a5257d",
  "--entity-target": "#0c7d5f",
  "--signal": "#1f56de",
  "--ink-mute": "#6d6252",
  "--rule-strong": "#c8bc9e",
  "--paper": "#f7f3ea",
  "--paper-2": "#f0e9d9",
};

// ------------------------------------------------------------- shared SVG poster
// Square viewBox; world (x,y) -> svg px with world +y up. Same +-WORLD_HALF frame as
// the live canvas, so the poster is a faithful preview (no reflow on boot).
const PV = 500;
const PS = PV / (2 * WORLD_HALF);
const w2s = (x: number, y: number): [number, number] => [PV / 2 + x * PS, PV / 2 - y * PS];

/** A PushT "T" in SVG px at (world) center/yaw, from the recorded tee geometry. */
function PosterTee({ x, y, yaw, className }: { x: number; y: number; yaw: number; className: string }) {
  const [cx, cy] = w2s(x, y);
  const barW = 2 * BAR_HALF[0] * PS, barH = 2 * BAR_HALF[1] * PS;
  const stemW = 2 * STEM_HALF[0] * PS, stemH = 2 * STEM_HALF[1] * PS;
  // world +y is up (svg down), so a +yaw (CCW in world) is a -rotate in svg
  return (
    <g class={className} transform={`translate(${cx.toFixed(1)} ${cy.toFixed(1)}) rotate(${(-yaw * 180 / Math.PI).toFixed(1)})`}>
      <rect x={-barW / 2} y={-barH / 2} width={barW} height={barH} rx={2} />
      <rect x={-stemW / 2} y={-STEM_OY * PS - stemH / 2} width={stemW} height={stemH} rx={2} />
    </g>
  );
}

/** The static, captioned poster — SSR output + the JS-off experience. Shows the
 *  RECORDED PATH (the tee's traced route + start/end poses + the pusher's path), so
 *  the rollout's story reads without any motion. */
function Poster() {
  const start = FRAMES[0], end = FRAMES[N - 1];
  const teePath = FRAMES.map(([, , tx, ty]) => w2s(tx, ty).map((n) => n.toFixed(1)).join(",")).join(" ");
  const pusherPath = FRAMES.map(([px, py]) => w2s(px, py).map((n) => n.toFixed(1)).join(",")).join(" ");
  const [pex, pey] = w2s(end[0], end[1]);
  return (
    <svg
      class="vr-poster-svg"
      viewBox={`0 0 ${PV} ${PV}`}
      role="img"
      aria-label={
        "Top-down PushT arena. A recorded rollout of the trained tiny VLA: the magenta T-block is traced along the path it took " +
        "from its start pose to the green dashed target at the center, with the amber pusher's path behind it. " +
        "This is a recorded replay, not live inference."
      }
    >
      <title>ch1.8 tiny VLA — recorded PushT rollout (seed 0)</title>
      <desc>
        One evaluation episode of the from-scratch tiny VLA on PushT, recorded at seed 0.
        The block's traced route and start/end poses show the policy pushing the T onto
        the target. A live in-browser rollout is future work (needs a flow-sampler
        runtime + offscreen rendering); this is a deterministic recording.
      </desc>

      <rect class="vr-arena" x={2} y={2} width={PV - 4} height={PV - 4} rx={6} />
      <g class="vr-grid">
        {Array.from({ length: 9 }, (_, i) => ((i + 1) * PV) / 10).map((v) => (
          <>
            <line x1={v} y1={2} x2={v} y2={PV - 2} />
            <line x1={2} y1={v} x2={PV - 2} y2={v} />
          </>
        ))}
      </g>

      {/* target pose (fixed at origin) — dashed emerald */}
      <PosterTee x={DATA.target.x} y={DATA.target.y} yaw={DATA.target.yaw} className="vr-target" />
      <text class="vr-target-label" x={w2s(0.03, 0.02)[0]} y={w2s(0.03, 0.02)[1]}>target</text>

      {/* the recorded paths — the rollout's route (pusher behind block) */}
      <polyline class="vr-pusher-path" points={pusherPath} />
      <polyline class="vr-tee-path" points={teePath} />

      {/* start (faint) + end (solid) block poses */}
      <PosterTee x={start[2]} y={start[3]} yaw={start[4]} className="vr-tee vr-tee-start" />
      <PosterTee x={end[2]} y={end[3]} yaw={end[4]} className="vr-tee vr-tee-end" />

      {/* the pusher at the end of the recorded path */}
      <g transform={`translate(${pex.toFixed(1)} ${pey.toFixed(1)})`}>
        <circle class="vr-pusher-ring" r={0.028 * PS} />
        <circle class="vr-pusher-core" r={0.015 * PS} />
      </g>

      <text class="vr-poster-cap" x={PV / 2} y={PV - 14} text-anchor="middle">
        recorded rollout · seed 0 · press play
      </text>
    </svg>
  );
}

// ------------------------------------------------------------------ replay canvas
function ReplayPanel() {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const [booted, setBooted] = useState(false);
  const [idx, setIdx] = useState(0);
  const [playing, setPlaying] = useState(false);
  const [announce, setAnnounce] = useState("");
  const reducedRef = useRef(false);

  // ---- draw one recorded frame through the ch1.1 PushT top-down renderer ----
  const draw = (i: number) => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext("2d");
    if (!ctx) return;
    const w = canvas.width, h = canvas.height;
    const scale = w / (2 * WORLD_HALF);
    const w2c = (x: number, y: number): [number, number] => [w / 2 + x * scale, h / 2 - y * scale];

    // resolve tokens each frame so a theme toggle is reflected live
    const cs = getComputedStyle(canvas);
    const col = (k: PaletteKey) => (cs.getPropertyValue(k).trim() || PALETTE_FALLBACK[k]);
    const PUSHER = col("--entity-pusher"), BLOCK = col("--entity-block"),
      TARGET = col("--entity-target"), SIGNAL = col("--signal"),
      INK = col("--ink-mute"), PAPER = col("--paper"), PAPER2 = col("--paper-2");

    const teeCorners = (cx: number, cy: number, yaw: number, hx: number, hy: number, ox: number, oy: number) => {
      const c = Math.cos(yaw), s = Math.sin(yaw);
      return [[ox - hx, oy - hy], [ox + hx, oy - hy], [ox + hx, oy + hy], [ox - hx, oy + hy]]
        .map(([lx, ly]) => w2c(cx + lx * c - ly * s, cy + lx * s + ly * c));
    };
    const fillPoly = (pts: number[][], style: string) => {
      ctx.beginPath();
      pts.forEach(([x, y], k) => (k ? ctx.lineTo(x, y) : ctx.moveTo(x, y)));
      ctx.closePath();
      ctx.fillStyle = style;
      ctx.fill();
    };
    const strokePoly = (pts: number[][], style: string, lw: number) => {
      ctx.beginPath();
      pts.forEach(([x, y], k) => (k ? ctx.lineTo(x, y) : ctx.moveTo(x, y)));
      ctx.closePath();
      ctx.strokeStyle = style;
      ctx.lineWidth = lw;
      ctx.stroke();
    };
    const drawTee = (cx: number, cy: number, yaw: number, style: string) => {
      fillPoly(teeCorners(cx, cy, yaw, BAR_HALF[0], BAR_HALF[1], 0, 0), style);
      fillPoly(teeCorners(cx, cy, yaw, STEM_HALF[0], STEM_HALF[1], 0, STEM_OY), style);
    };

    // arena background (warm paper) + faint graph paper
    ctx.fillStyle = PAPER2;
    ctx.fillRect(0, 0, w, h);
    ctx.fillStyle = PAPER;
    ctx.fillRect(0, 0, w, h);
    ctx.save();
    ctx.globalAlpha = 0.5;
    ctx.strokeStyle = INK;
    ctx.lineWidth = 1;
    ctx.beginPath();
    for (let g = 1; g < 10; g++) {
      const p = (g * w) / 10;
      ctx.moveTo(p, 0); ctx.lineTo(p, h);
      ctx.moveTo(0, p); ctx.lineTo(w, p);
    }
    ctx.globalAlpha = 0.12;
    ctx.stroke();
    ctx.restore();

    // target (fixed at origin) — dashed emerald outline
    ctx.save();
    ctx.setLineDash([5, 4]);
    strokePoly(teeCorners(DATA.target.x, DATA.target.y, DATA.target.yaw, BAR_HALF[0], BAR_HALF[1], 0, 0), TARGET, 2);
    strokePoly(teeCorners(DATA.target.x, DATA.target.y, DATA.target.yaw, STEM_HALF[0], STEM_HALF[1], 0, STEM_OY), TARGET, 2);
    ctx.restore();

    // the recorded trail up to the current frame — the block's route so far (signal)
    if (i > 0) {
      ctx.save();
      ctx.globalAlpha = 0.5;
      ctx.strokeStyle = SIGNAL;
      ctx.lineWidth = 1.5;
      ctx.beginPath();
      for (let k = 0; k <= i; k++) {
        const [tx, ty] = FRAMES[k].slice(2, 4);
        const [cx, cy] = w2c(tx, ty);
        k ? ctx.lineTo(cx, cy) : ctx.moveTo(cx, cy);
      }
      ctx.stroke();
      ctx.restore();
    }

    const [px, py, tx, ty, tyaw] = FRAMES[i];
    // block (tee) — magenta
    drawTee(tx, ty, tyaw, BLOCK);
    // pusher (agent) — amber
    const [ppx, ppy] = w2c(px, py);
    const rPx = 0.015 * scale;
    ctx.save();
    ctx.globalAlpha = 0.5;
    ctx.strokeStyle = PUSHER;
    ctx.lineWidth = 1.5;
    ctx.beginPath();
    ctx.arc(ppx, ppy, rPx * 1.9, 0, Math.PI * 2);
    ctx.stroke();
    ctx.restore();
    ctx.fillStyle = PUSHER;
    ctx.beginPath();
    ctx.arc(ppx, ppy, rPx, 0, Math.PI * 2);
    ctx.fill();
  };

  // ---- boot: size the canvas, respect reduced-motion, render frame 0 ----
  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    canvas.width = CANVAS_PX;
    canvas.height = CANVAS_PX;
    reducedRef.current =
      typeof matchMedia === "function" && matchMedia("(prefers-reduced-motion: reduce)").matches;
    setBooted(true);
    setPlaying(!reducedRef.current); // autoplay unless the reader prefers reduced motion
  }, []);

  // ---- render on every frame-index change (scrub or playback) ----
  useEffect(() => { if (booted) draw(idx); }, [idx, booted]);

  // ---- playback loop: advance the recorded frame index at PLAY_FPS ----
  // The loop persists across idx changes (idx is not a dep); it stops when the idx
  // effect below flips `playing` off at the last frame, which tears this down.
  useEffect(() => {
    if (!playing || !booted) return;
    let raf = 0, last = performance.now(), acc = 0;
    const dt = 1 / PLAY_FPS;
    const tick = (now: number) => {
      acc += Math.min(now - last, 200) / 1000;
      last = now;
      while (acc >= dt) { acc -= dt; setIdx((i) => Math.min(N - 1, i + 1)); }
      raf = requestAnimationFrame(tick);
    };
    raf = requestAnimationFrame(tick);
    return () => cancelAnimationFrame(raf);
  }, [playing, booted]);

  // stop cleanly when the recording reaches its last frame
  useEffect(() => { if (idx >= N - 1 && playing) setPlaying(false); }, [idx, playing]);

  // ---- announce progress + the recorded outcome (screen-reader path) ----
  useEffect(() => {
    if (!booted) return;
    const atEnd = idx >= N - 1;
    const posErr = atEnd ? DATA.rollout.pos_err_final : undefined;
    if (atEnd) {
      setAnnounce(
        DATA.rollout.success
          ? `Recorded rollout complete: the tiny VLA pushed the T onto the target — success, final position error ${posErr!.toFixed(3)} metres.`
          : `Recorded rollout complete: final position error ${posErr!.toFixed(3)} metres.`,
      );
    } else if (playing) {
      setAnnounce(`Playing recorded rollout, frame ${idx + 1} of ${N}.`);
    } else {
      setAnnounce(`Recorded rollout paused at frame ${idx + 1} of ${N}.`);
    }
  }, [idx, playing, booted]);

  const onScrub = (e: Event) => {
    setPlaying(false);
    setIdx(parseInt((e.currentTarget as HTMLInputElement).value, 10));
  };
  const togglePlay = () => {
    if (idx >= N - 1) { setIdx(0); setPlaying(true); return; } // replay from the top
    setPlaying((p) => !p);
  };
  const restart = () => { setIdx(0); setPlaying(!reducedRef.current); };

  const onKeyDown = (e: KeyboardEvent) => {
    if (e.key === " " || e.key === "Spacebar") { e.preventDefault(); togglePlay(); }
    else if (e.key === "ArrowRight") { e.preventDefault(); setPlaying(false); setIdx((i) => Math.min(N - 1, i + 1)); }
    else if (e.key === "ArrowLeft") { e.preventDefault(); setPlaying(false); setIdx((i) => Math.max(0, i - 1)); }
    else if (e.key === "Home") { e.preventDefault(); setPlaying(false); setIdx(0); }
    else if (e.key === "End") { e.preventDefault(); setPlaying(false); setIdx(N - 1); }
  };

  const frameStep = Math.round((idx / Math.max(1, N - 1)) * DATA.rollout.steps);

  return (
    <div class="vr-panel">
      <figure
        class="vr-figure"
        tabIndex={0}
        role="application"
        aria-label={
          `Recorded PushT rollout of the trained tiny VLA, instruction "${DATA.rollout.instruction}". ` +
          "This is a deterministic recording, not live inference. Press space to play or pause, " +
          "the arrow keys to scrub frame by frame, Home and End to jump to the start or end."
        }
        onKeyDown={onKeyDown}
      >
        {/* SSR poster — the JS-off experience (the recorded PATH) + pre-boot frame */}
        <div class="vr-poster" hidden={booted}><Poster /></div>

        {/* live replay canvas — shown once booted */}
        <canvas ref={canvasRef} class="vr-canvas" hidden={!booted} aria-hidden="true" />

        {/* recorded-not-live badge — the honest label, always visible on the figure */}
        <div class="vr-badge" aria-hidden="true">recorded replay · not live inference</div>

        {/* live HUD (the poster carries the caption for the JS-off path) */}
        {booted && (
          <div class="vr-hud" aria-hidden="true">
            <div class="vr-hud-row">
              <span class="vr-k">frame</span>
              <span class="vr-v">{idx + 1}/{N}</span>
            </div>
            <div class="vr-hud-row">
              <span class="vr-k">step</span>
              <span class="vr-v">{frameStep}/{DATA.rollout.steps}</span>
            </div>
            <div class="vr-hud-row">
              <span class="vr-k">outcome</span>
              <span class={`vr-v ${DATA.rollout.success ? "vr-ok" : ""}`}>
                {idx >= N - 1 ? (DATA.rollout.success ? "success ✓" : "ended") : "…"}
              </span>
            </div>
          </div>
        )}

        <div class="vr-legend" aria-hidden="true">
          <span class="vr-lg vr-lg-tee">T-block</span>
          <span class="vr-lg vr-lg-pusher">pusher</span>
          <span class="vr-lg vr-lg-target">target</span>
        </div>
      </figure>

      {/* the ONE control — play/pause + the frame scrubber (keyboard-native) */}
      <div class="vr-controls">
        <button type="button" class="vr-btn vr-btn--primary" onClick={togglePlay} disabled={!booted}>
          {idx >= N - 1 ? "↻ replay" : playing ? "❚❚ pause" : "► play"}
        </button>
        <input
          class="vr-scrub"
          type="range"
          min={0}
          max={N - 1}
          step={1}
          value={idx}
          onInput={onScrub}
          disabled={!booted}
          aria-label="Scrub the recorded rollout frame by frame."
          aria-valuetext={`Frame ${idx + 1} of ${N}`}
        />
        <button type="button" class="vr-btn" onClick={restart} disabled={!booted}>
          ⤺ restart
        </button>
      </div>
      <p class="vr-note" aria-hidden="true">
        recorded rollout, seed {DATA.seed} (episode {DATA.rollout.episode}, held-out eval
        seed {DATA.rollout.ep_seed}) · a <b>live</b> in-browser VLA is future work — it
        needs a sampler-aware contract-v2 runtime (the flow ODE sampler) plus offscreen
        RGB rendering, which MuJoCo-WASM does not expose · poster reads with JS off
      </p>

      {/* non-visual path: progress + the recorded outcome */}
      <div class="bk-sr" aria-live="polite">{announce}</div>
    </div>
  );
}

// ------------------------------------------------------------- attention panel
/** One grouped attention bar (vision / state / language). Pure DOM so it fully
 *  server-renders — the whole attention lesson is present with JS off. */
function GroupBar({ label, weight, cls, note }: { label: string; weight: number; cls: string; note?: string }) {
  return (
    <div class="vr-abar-row">
      <span class="vr-abar-lab">{label}</span>
      <div class="vr-abar-track">
        <div class={`vr-abar-fill ${cls}`} style={`width:${Math.max(1.5, weight * 100)}%`} />
      </div>
      <span class="vr-abar-val">{pct(weight)}</span>
      {note && <span class="vr-abar-note">{note}</span>}
    </div>
  );
}

function AttentionPanel() {
  const a = DATA.attention;
  // per-word language bars scaled to the biggest single word weight (readability)
  const maxWord = Math.max(1e-6, ...a.tokens.map((t) => t.weight));
  return (
    <div class="vr-att">
      <div class="vr-att-head">
        <div class="vr-att-title" aria-hidden="true">what the fusion looks at</div>
        <div class="vr-att-sub" aria-hidden="true">
          the CLS token's attention over <code>[vision, state, language]</code> — from
          vla.py's <code>fusion/cls_attention</code>
        </div>
      </div>

      {/* the hero: the three grouped weights (vision vs state vs language) */}
      <div class="vr-abar" aria-hidden="true">
        <GroupBar label="vision" weight={a.vision} cls="vr-abar-vision"
          note="not load-bearing" />
        <GroupBar label="state" weight={a.state} cls="vr-abar-state" />
        <GroupBar label="language" weight={a.language} cls="vr-abar-lang" />
        {a.cls > 0.0005 && (
          <GroupBar label="CLS (self)" weight={a.cls} cls="vr-abar-cls" />
        )}
      </div>

      {/* per-word language breakdown — one small bar per instruction word */}
      <div class="vr-words" aria-hidden="true">
        <div class="vr-words-cap">language, word by word — "{DATA.rollout.instruction}"</div>
        <div class="vr-words-grid">
          {a.tokens.map((t, i) => (
            <div class="vr-word" key={i}>
              <span class="vr-word-w">{t.word}</span>
              <div class="vr-word-track">
                <div class="vr-word-fill" style={`width:${(t.weight / maxWord) * 100}%`} />
              </div>
              <span class="vr-word-val">{pct1(t.weight)}</span>
            </div>
          ))}
        </div>
      </div>

      <p class="vr-att-cap" aria-hidden="true">
        The CLS read-out token spreads its attention across the fused inputs, and the
        <b> vision</b> feature gets {pct(a.vision)} of it. But that channel is a
        <em> frozen, random-init</em> CNN — and the Break-It proves it is not doing the
        work: <b>--break blind</b> zeros the vision feature and PushT success is
        UNCHANGED ({pct1(DATA.meta.break_blind_pusht_success_rate)} == the sighted
        {" "}{pct1(DATA.meta.pusht_success_rate)}). PushT is solvable from
        <b> state</b> alone, so attention weight on vision is not the same as vision
        mattering. That gap is exactly why real VLAs adapt a <em>pretrained</em>
        {" "}backbone (the SmolVLA Scale Lab).
      </p>
      <div class="vr-att-prov" aria-hidden="true">
        weights sum to {a.sum.toFixed(3)} · sequence [CLS, vision, state, tok_0..tok_15] ·
        seed {DATA.seed}, measured from vla.py (matches meta.yaml reference_run)
      </div>

      {/* non-visual summary of the attention picture */}
      <div class="bk-sr">
        Fusion attention: the CLS token attends {pct(a.vision)} to vision, {pct(a.state)}
        {" "}to state, and {pct(a.language)} to language. The vision channel is a frozen
        random-init CNN and is not load-bearing — the Break-It zeroing vision leaves
        PushT success unchanged, {pct1(DATA.meta.break_blind_pusht_success_rate)}, equal
        to the sighted rate.
      </div>
    </div>
  );
}

// ------------------------------------------------------------------ the toy shell
function VlaRollout() {
  const m = DATA.meta;
  return (
    <div class="vr">
      <ReplayPanel />
      <AttentionPanel />
      <div class="vr-foot" aria-hidden="true">
        from-scratch tiny VLA · PushT trained <b>{pct(m.pusht_success_rate)}</b>
        {" "}(95% CI [{pct(m.pusht_success_ci_lo)}, {pct(m.pusht_success_ci_hi)}], N=
        {m.eval_episodes}) vs untrained {pct(m.baseline_pusht_success_rate)} · ALOHA
        {" "}{pct(m.aloha_success_rate)} · {m.num_examples} examples, {m.flow_steps} flow
        steps · the exact PushT % is a noisy 12-episode rate — read the interval
      </div>
    </div>
  );
}

// ============================================================================
// WIRE ME IN — PlateIsland.tsx (the shared dispatch; do NOT edit here):
//   import VlaRolloutToy from "./toys/VlaRolloutToy";            // with the other toy imports
//   if (demo === "vla_rollout") return <VlaRolloutToy />;         // ch1.8 recorded VLA rollout + fusion attention
// (No lazy/heavy deps: this toy replays a static-JSON recording — no WASM, no onnx —
//  so it is safe to import eagerly like the other data toys and fully server-renders
//  the poster + attention bars for the JS-off path.)
// ============================================================================
export default function VlaRolloutToy() {
  return <VlaRollout />;
}
