/**
 * ch3.1 "World Models I: Learning the Simulator" — the RECONSTRUCTION-vs-PREDICTION
 * concept-toy (`demo: world_model_prediction`), told HONESTLY. A recorded-data
 * sibling of ch3.3's EngineDriftToy: no WASM, pure SVG over numbers wm.py itself
 * measured (seed 0, cpu), regenerated by site/scripts/vizdata/ch3.1_world_models.py
 * into the co-located vizdata.json and gated against meta.yaml's seed-sweep bands.
 *
 * THE ONE THING THIS TOY MUST NOT LET YOU MISBELIEVE. The aggregate "world model
 * beats copy-last ~2.4x" headline is TRUE but MISLEADING on its own: the entire win
 * is carried by the PUSHER dims (whose next position is a trivial integral of the
 * commanded velocity — easy). On the OBJECT/block dims (the tee pose — the contact
 * dynamics PushT is actually about) COPY-LAST WINS on every seed. So this toy LEADS
 * with that split, not the aggregate: it learned the easy half (pusher kinematics),
 * not the hard half (block dynamics). That honest split is the chapter's lesson.
 *
 * THREE panels (the split first, deliberately):
 *   1. THE HONEST SPLIT (headline) — two groups, world-model vs copy-last bars:
 *      PUSHER (WM ~8x lower, a win) vs OBJECT (COPY-LAST wins — an honest loss).
 *   2. PREDICTION vs COPY-LAST per horizon k — the aggregate crossover curves:
 *      copy-last wins at k=1 (nothing moved), the world model overtakes it by k=3
 *      and the gap widens. A k scrubber reads out both errors + who wins at each k.
 *   3. RECONSTRUCTION (posterior) is easy/low vs prediction — the recon-vs-prediction
 *      distinction; + the pixel Scale Lab note (pixels can't beat copy-last free-tier).
 *
 * Colour by MEANING: --signal blue = the WORLD MODEL, --ink-mute = COPY-LAST
 * (baseline), --entity-target green = a WIN badge (pusher), --alert red = the honest
 * LOSS badge (object). The server-rendered default (k = crossover) IS the JS-off
 * experience; only the k scrubber goes inert without hydration.
 */
import "./WorldModelToy.css";
import { useState } from "preact/hooks";
// Real numbers from wm.py, seed 0, cpu — see the file's `provenance` and the
// generator site/scripts/vizdata/ch3.1_world_models.py. Committed small text, no binary.
import viz from "../../../../curriculum/phase3_advanced/ch3.1_world_models/demo/vizdata.json";

// ---------------------------------------------------------------- typed vizdata
interface Group {
  label: string; sublabel: string; dims: number[];
  wm: number; copy: number; ratio_copy_over_wm: number; wm_wins: boolean;
}
const K = viz.k as number[];
const HORIZON = viz.horizon as number;
const AGG = viz.aggregate as {
  world_model: number[]; copy_last: number[]; crossover_k: number;
  wm_mean: number; copy_mean: number; ratio_copy_over_wm: number;
};
const SPLIT = viz.split as { pusher: Group; object: Group; headline: string };
const RECON = viz.reconstruction as {
  val_recon: number; prediction_mean: number; prediction_floor: number; note: string;
};

const fmt = (v: number) => v.toFixed(3);
const fmtx = (v: number) => `${v.toFixed(1)}×`;

// ============================================================ split bar group
function SplitGroup({ g }: { g: Group }) {
  const max = Math.max(g.wm, g.copy);
  const wmPct = (g.wm / max) * 100;
  const copyPct = (g.copy / max) * 100;
  // pusher: WM wins by ratio copy/wm; object: copy-last wins by wm/copy.
  const winRatio = g.wm_wins ? g.ratio_copy_over_wm : g.wm / Math.max(g.copy, 1e-9);
  return (
    <div class="wm-group" data-loss={!g.wm_wins}>
      <div class="wm-group-title">
        <span class="wm-group-name">{g.label}</span>
        <span class="wm-badge" data-kind={g.wm_wins ? "win" : "loss"}>
          {g.wm_wins ? "WORLD MODEL WINS" : "COPY-LAST WINS"} · {fmtx(winRatio)} lower
        </span>
      </div>
      <div class="wm-group-sub">{g.sublabel}</div>
      <div class="wm-bars">
        <div class="wm-bar-row">
          <span class="wm-bar-lab">world model</span>
          <span class="wm-bar-track"><span class="wm-bar-fill" data-series="wm" style={`width:${wmPct.toFixed(1)}%`} /></span>
          <span class="wm-bar-val" data-winner={g.wm_wins}>{fmt(g.wm)}</span>
        </div>
        <div class="wm-bar-row">
          <span class="wm-bar-lab">copy-last</span>
          <span class="wm-bar-track"><span class="wm-bar-fill" data-series="copy" style={`width:${copyPct.toFixed(1)}%`} /></span>
          <span class="wm-bar-val" data-winner={!g.wm_wins}>{fmt(g.copy)}</span>
        </div>
      </div>
    </div>
  );
}

// ============================================================ aggregate chart
const CW = 470, CH = 250;
const CP = { l: 44, r: 74, t: 18, b: 30 };
const CPW = CW - CP.l - CP.r;
const CPH = CH - CP.t - CP.b;
const Y_MAX = Math.ceil((Math.max(...AGG.copy_last) * 1.02) / 0.05) * 0.05;
const cx = (k: number) => CP.l + ((k - 1) / (HORIZON - 1)) * CPW;
const cy = (v: number) => CP.t + (1 - v / Y_MAX) * CPH;

function AggregateChart({ selK }: { selK: number }) {
  const wmPts = AGG.world_model.map((v, i) => `${cx(K[i]).toFixed(1)},${cy(v).toFixed(1)}`).join(" ");
  const copyPts = AGG.copy_last.map((v, i) => `${cx(K[i]).toFixed(1)},${cy(v).toFixed(1)}`).join(" ");
  const yTicks: number[] = [];
  for (let v = 0; v <= Y_MAX + 1e-9; v += 0.05) yTicks.push(Number(v.toFixed(2)));
  const xTicks = K.filter((k) => k === 1 || k % 3 === 0 || k === HORIZON);
  const xc = cx(selK);
  const i = selK - 1;
  return (
    <svg
      class="wm-svg"
      viewBox={`0 0 ${CW} ${CH}`}
      role="img"
      aria-label={
        `Prediction error versus horizon k, from k=1 to k=${HORIZON}. The neutral dashed copy-last ` +
        `baseline wins at k=1 (nothing has moved yet) then climbs steeply; the blue world-model curve ` +
        `dips and overtakes copy-last at k=${AGG.crossover_k}, and the gap widens after. This aggregate ` +
        `win is carried by the pusher dimensions — on the block dimensions copy-last still wins (see the split above).`
      }
    >
      {/* y gridlines + ticks */}
      {yTicks.map((v) => (
        <g>
          <line class="wm-grid" x1={CP.l} y1={cy(v)} x2={CW - CP.r} y2={cy(v)} />
          <text class="wm-tick" x={CP.l - 5} y={cy(v) + 3} text-anchor="end">{v.toFixed(2)}</text>
        </g>
      ))}
      {/* x axis + ticks */}
      <line class="wm-axis" x1={CP.l} y1={CH - CP.b} x2={CW - CP.r} y2={CH - CP.b} />
      {xTicks.map((k) => (
        <text class="wm-tick" x={cx(k)} y={CH - CP.b + 13} text-anchor="middle">{k}</text>
      ))}
      <text class="wm-axis-title" x={CW - CP.r} y={CH - 3} text-anchor="end">horizon k →</text>
      <text class="wm-axis-title" x={CP.l - 40} y={CP.t + 2}>MSE</text>

      {/* crossover marker */}
      <line class="wm-cross" x1={cx(AGG.crossover_k)} y1={CP.t} x2={cx(AGG.crossover_k)} y2={CH - CP.b} />
      <text class="wm-cross-lab" x={cx(AGG.crossover_k) + 3} y={CP.t + 9}>overtakes at k={AGG.crossover_k}</text>

      {/* the two curves */}
      <polyline class="wm-line wm-l-copy" points={copyPts} />
      <polyline class="wm-line wm-l-wm" points={wmPts} />

      {/* end labels */}
      <text class="wm-series-lab wm-l-copy" x={cx(HORIZON) + 4} y={cy(AGG.copy_last[HORIZON - 1]) + 3}>copy-last</text>
      <text class="wm-series-lab wm-l-wm" x={cx(HORIZON) + 4} y={cy(AGG.world_model[HORIZON - 1]) + 3}>world model</text>

      {/* scrub cursor + dots at the selected k */}
      <line class="wm-cursor" x1={xc} y1={CP.t} x2={xc} y2={CH - CP.b} />
      <circle class="wm-dot wm-l-copy" cx={xc} cy={cy(AGG.copy_last[i])} r={3.4} />
      <circle class="wm-dot wm-l-wm" cx={xc} cy={cy(AGG.world_model[i])} r={3.4} />
    </svg>
  );
}

// ============================================================ reconstruction card
function ReconCard() {
  const max = Math.max(RECON.val_recon, RECON.prediction_mean);
  const rPct = (RECON.val_recon / max) * 100;
  const pPct = (RECON.prediction_mean / max) * 100;
  return (
    <div class="wm-recon">
      <div class="wm-recon-bars">
        <div class="wm-recon-row">
          <span class="wm-recon-lab">reconstruction</span>
          <span class="wm-recon-track"><span class="wm-recon-fill" data-kind="recon" style={`width:${rPct.toFixed(1)}%`} /></span>
          <span class="wm-recon-val">{fmt(RECON.val_recon)}</span>
        </div>
        <div class="wm-recon-row">
          <span class="wm-recon-lab">prediction (mean k)</span>
          <span class="wm-recon-track"><span class="wm-recon-fill" data-kind="pred" style={`width:${pPct.toFixed(1)}%`} /></span>
          <span class="wm-recon-val">{fmt(RECON.prediction_mean)}</span>
        </div>
      </div>
      <div class="wm-scale-note">
        Reconstruction (the <b>posterior</b> — it has <b>seen</b> the frame) is the easy half and
        stays low. Prediction (the <b>prior</b>, rolled forward on actions alone) is the real test.
        And on <b>pixels</b> even the reconstruction can’t beat copy-last free-tier — that is the
        <b> Scale Lab</b> (“why world models eat compute”).
      </div>
    </div>
  );
}

// ==================================================================== THE ISLAND
function WorldModelToy() {
  const [selK, setSelK] = useState<number>(AGG.crossover_k);
  const i = selK - 1;
  const wmV = AGG.world_model[i];
  const copyV = AGG.copy_last[i];
  const wmWins = wmV < copyV;

  const onSlide = (e: Event) => setSelK(parseInt((e.currentTarget as HTMLInputElement).value, 10));

  const pusher = SPLIT.pusher, object = SPLIT.object;
  const objWinRatio = object.wm / Math.max(object.copy, 1e-9); // copy-last's advantage on the block dims

  // aria-live: the split summary (the lesson) + the current-k qualitative readout.
  const announce =
    `The world model beats copy-last only where it is easy. On the pusher dimensions its error is ` +
    `${fmt(pusher.wm)} versus copy-last ${fmt(pusher.copy)} — a ${fmtx(pusher.ratio_copy_over_wm)} win. ` +
    `On the object/block dimensions copy-last wins, ${fmt(object.copy)} versus the world model's ` +
    `${fmt(object.wm)}. At horizon k=${selK}, world-model error is ${fmt(wmV)} and copy-last is ` +
    `${fmt(copyV)}; ${wmWins ? "the world model wins here" : "copy-last still wins here"}.`;

  return (
    <div class="wm">
      {/* ---- PANEL 1 (headline): the honest split ---- */}
      <figure class="wm-split">
        <figcaption class="wm-split-h">
          <span>where the aggregate win actually lives</span>
          <b>seed 0 · cpu · per obs group</b>
        </figcaption>
        <div class="wm-groups">
          <SplitGroup g={pusher} />
          <SplitGroup g={object} />
        </div>
        <p class="wm-headline">
          It learned the <b class="wm-easy">easy half</b> (pusher kinematics — a first-order
          integral of the commanded velocity), <b>not</b> the <b class="wm-hard">hard half</b>{" "}
          (block dynamics — the contact/pushing PushT is about). The ~{fmtx(AGG.ratio_copy_over_wm)}{" "}
          aggregate win is the pusher; on the block dims copy-last wins by {fmtx(objWinRatio)}.
        </p>
      </figure>

      {/* ---- PANEL 2 + 3: aggregate crossover + reconstruction ---- */}
      <div class="wm-lower">
        <figure class="wm-panel">
          <figcaption class="wm-cap">
            <span>prediction vs copy-last · per horizon k</span>
            <b>the aggregate curves</b>
          </figcaption>
          <AggregateChart selK={selK} />

          <div class="wm-slider-row">
            <label class="wm-slider-label" for="wm-k">horizon <b>k</b></label>
            <input
              id="wm-k"
              class="wm-slider"
              type="range"
              min={1}
              max={HORIZON}
              step={1}
              value={selK}
              onInput={onSlide}
              aria-label={`Prediction horizon k, from 1 to ${HORIZON}. At k=1 copy-last wins; drag right and the world model overtakes it around k=${AGG.crossover_k}, then the gap widens.`}
              aria-valuetext={`k equals ${selK}`}
            />
          </div>
          <div class="wm-readout" aria-hidden="true">
            <span class="wm-ro-k">k = {selK}</span>
            <span class="wm-ro-v wm-l-wm">world model {fmt(wmV)}</span>
            <span class="wm-ro-v wm-l-copy">copy-last {fmt(copyV)}</span>
            <span class="wm-ro-win" data-who={wmWins ? "wm" : "copy"}>
              {wmWins ? "world model wins" : "copy-last wins"}
            </span>
          </div>
        </figure>

        <figure class="wm-panel">
          <figcaption class="wm-cap">
            <span>reconstruction is easy · prediction is the test</span>
            <b>posterior vs prior</b>
          </figcaption>
          <ReconCard />
        </figure>
      </div>

      {/* non-visual path to the same aha — the split + the current-k readout */}
      <div class="bk-sr" aria-live="polite">{announce}</div>

      <p class="wm-note">
        The honest lesson: this tiny model learned the <b>pusher kinematics</b>, not the{" "}
        <b>block dynamics</b> — so the aggregate crossover is <b>not</b> “it learned the simulator.”
        Real numbers from wm.py (seed 0, cpu), matching meta.yaml; the whole toy reads with JS off,
        only the k scrubber needs it.
      </p>
    </div>
  );
}

export default function WorldModel() {
  return <WorldModelToy />;
}
